version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5001:5000" # Map gunicorn port 8000 to host port 5001 (so it doesn't conflict with other possible Flask apps)
    env_file:
      - .env
    depends_on:
      - redis
      - worker
      # - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    env_file:
      - .envcelery
    depends_on:
      - redis
      # - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: development
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: