# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install GCC and other build dependencies
RUN apt-get update && apt-get install -y \
  gcc \
  libc-dev \
  libffi-dev \
  && rm -rf /var/lib/apt/lists/*

# Install PostgreSQL client
RUN apt-get update -y && apt-get install -y postgresql-client

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Copy the initialization and entrypoint scripts
COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

# Run entrypoint script when the container launches
CMD ["./entrypoint.sh"]