# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install GCC and other build dependencies
RUN apt-get update && apt-get install -y \
  gcc \
  libc-dev \
  libffi-dev \
  && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Upgrade the db with the latest migrations
# RUN flask db upgrade

# Make port 8000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Run app.py when the container launches
# CMD ["flask", "run", "--host=0.0.0.0"]

# Run gunicorn when the container launches
CMD ["gunicorn", "-w", "8", "-b", "0.0.0.0:5000", "--timeout", "60", "--reload", "app:app"]
