scheduling_key_words = [
    "today",
    "tomorrow",
    "@",
    "week",
    "month",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "hear more",
]

demo_key_words = [
    "agreed on the call",
    "agreed on the appointment",
    "organized a call",
    "demo time booked",
    "can do tomorrow",
    "@",
    "organized the meeting",
    "booked the appointment",
    "scheduled the demo",
    "agreed on the schedule",
    "planned the schedule",
    "book a slot",
    "call slot reserved",
    "meeting slot booked",
    "arrange a meeting",
    "demo time set",
    "participate in our meeting",
    "appointment time booked",
    "call slot arranged",
    "meeting slot set",
    "connect for the call",
    "appointment time fixed",
    "looking forward to s",
    "demo scheduled",
    "planned the demo",
    "attend the meeting",
    "appointment slot reserved",
    "set the appointment",
    "can do monday",
    "confirmed the appointment",
    "call confirmed",
    "scheduled the meeting",
    "demo time fixed",
    "demo set for",
    "sent the details",
    "connect for our meeting",
    "finalized the call",
    "call time fixed",
    "placeholder",
    "fixed the time",
    "set the schedule",
    "hop on our meeting",
    "shared the calendar",
    "appointment slot booked",
    "meeting time set",
    "booked the meeting",
    "finalized the appointment",
    "appointment set",
    "call slot set",
    "set the demo",
    "reserved the appointment",
    "looking forward to our meeting",
    "appointment slot set",
    "arranged the call",
    "looking forward to our call",
    "demo time reserved",
    "booked the demo",
    "call time booked",
    "call slot booked",
    "reserved the time",
    "dial into the meeting",
    "organized the call",
    "can do today",
    "confirmed the call",
    "my email",
    "confirmed for call",
    "sent",
    "meeting slot reserved",
    "meeting slot arranged",
    "appointment confirmed",
    "participate in our call",
    "call time set",
    "calendar invite",
    "can do wednesday",
    "meeting scheduled",
    "arranged the schedule",
    "scheduled our call",
    "meeting time fixed",
    "dial into our call",
    "appointment time reserved",
    "call scheduled",
    "reserved the slot",
    "scheduled the schedule",
    "meeting link",
    "demo slot reserved",
    "arranged the demo",
    "arranged the appointment",
    "fixed the call",
    "meeting time arranged",
    "demo slot arranged",
    "call time reserved",
    "log into the call",
    "would be great",
    "call time arranged",
    "set for",
    "can do thursday",
    "fixed the schedule",
    "organized the appointment",
    "set up a time",
    "email is",
    "hop on the call",
    "your time today",
    "demo slot booked",
    "meeting slot fixed",
    "call slot fixed",
    "planned the call",
    "meeting time reserved",
    "confirmed for demo",
    "forward to chatting",
    "put time on",
    "confirmed the time",
    "booked the schedule",
    "can do friday",
    "just booked",
    "finalized the schedule",
    "appointment time arranged",
    "agreed on a time",
    "demo appointment",
    "participate in the discussion",
    "see you then",
    "set the date",
    "appointment slot fixed",
    "can do tuesday",
    "connect on our call",
    "meeting confirmed",
    "planned the meeting",
    "confirmed the schedule",
    "meeting set",
    "connect on the call",
    "appointment time set",
    "scheduled the call",
    "attend our call",
    "join our meeting",
    "demo slot set",
    "meeting arranged",
    "join our discussion",
    "participate in our discussion",
    "scheduled the appointment",
    "reserved the schedule",
    "time set",
    "join our call",
    "fixed the appointment",
    "attend our meeting",
    "meeting time booked",
    "appointment slot arranged",
    "call time confirmed",
    "hop on our call",
    "sent out an invite",
    "demo slot fixed",
    "finalized the meeting",
    "organized the schedule",
    "sent an invite",
    "scheduled on",
    "log into our meeting",
    "demo time arranged",
    "talk soon",
    "reserved a time",
    "thanks"
]
