SAMPLE_LINKEDIN_RESEARCH_PAYLOAD = {
    "profile_id": "matthewdbarlow",
    "entity_urn": "ACoAABN_roYBM8h9NCJvwp-3L5JGb0fGtyLbBJc",
    "object_urn": "327134854",
    "first_name": "Matthew",
    "last_name": "Barlow, CSM, Lean Six Sigma Certified",
    "sub_title": "Senior Manager - Global Sales Compensation & Administration at Sungard Availability Services",
    "birth_date": None,
    "profile_picture": "https://media-exp1.licdn.com/dms/image/C4E03AQFBqCNmbLAA5g/profile-displayphoto-shrink_400_400/0/1571096888821?e=1670457600&v=beta&t=zDNNzhW1CbL7kk9e3D57FdCbwKF3y3rJWfh5OnL4ecY",
    "summary": "Highly successful, dependable, with a strong work ethic and noted leadership skills. Strategic minded with an eye to the optimal future state.  Experience in managing processes and systems, with background in Lean Six Sigma and Scrum. Organized and detail-oriented. Focused on benefiting the team dynamic and quality of work through effective communication and a high level of integrity. \r\n\r\nTop 5 Strengths: \r\nAchiever \u2013 Responsibility \u2013 Learner \u2013 Discipline \u2013 Analytical",
    "location": {
        "country": "United States",
        "short": "Coatesville, Pennsylvania",
        "city": "Coatesville",
        "state": "Pennsylvania",
        "default": "Coatesville, Pennsylvania, United States",
    },
    "premium": False,
    "influencer": False,
    "treasury_media": [],
    "languages": {
        "primary_locale": {"country": "US", "language": "en"},
        "supported_locales": [{"country": "US", "language": "en"}],
        "profile_languages": [],
    },
    "industry": "Information Technology & Services",
    "education": [
        {
            "date": {
                "start": {"month": None, "year": 2003},
                "end": {"month": None, "year": 2005},
            },
            "school": {
                "name": "West Chester University of Pennsylvania",
                "logo": "https://media-exp1.licdn.com/dms/image/C510BAQHav2ipdBSUFw/company-logo_400_400/0/1519856603484?e=1672876800&v=beta&t=ZjTIaEdxuojMP_nsyQQSJp44jnV8AUBIqEPXj470oww",
            },
            "degree_name": "Bachelor's degree",
            "field_of_study": "Communication, General",
        }
    ],
    "patents": [],
    "awards": [
        {
            "title": "2020 President's Club Award Winner",
            "description": "North American Sales Operations Employee of the Year",
            "issuer": "Sungard Availability Services",
            "date": {"year": 2021, "month": 1},
        }
    ],
    "certifications": [
        {
            "name": "Lean Six Sigma Certification",
            "date": {
                "start": {"month": 6, "year": 2020},
                "end": {"month": None, "year": None},
            },
            "authority": "Penn State Great Valley",
            "url": None,
            "license_number": None,
            "display_source": None,
            "company": {
                "name": "Penn State Great Valley",
                "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQGMo7Fr-FTarw/company-logo_400_400/0/1519891333393?e=1672876800&v=beta&t=ySm2QBBNA8-xSpPkfvQdEXynOd0oIRClI2J_KvRE-l8",
            },
        },
        {
            "name": "Xactly Analytics Certification Exam: Level 1",
            "date": {
                "start": {"month": 5, "year": 2021},
                "end": {"month": 5, "year": 2022},
            },
            "authority": "Xactly Corp",
            "url": None,
            "license_number": None,
            "display_source": None,
            "company": {
                "name": "Xactly Corp",
                "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHetrqDFxOMuw/company-logo_400_400/0/1657647486969?e=1672876800&v=beta&t=SnGxbQs-HLItFPZYuTR_kFJSPdXGFFy5plfKYoxVjmA",
            },
        },
        {
            "name": "Xactly Incent Certification Exam: Level 1",
            "date": {
                "start": {"month": 5, "year": 2021},
                "end": {"month": 5, "year": 2022},
            },
            "authority": "Xactly Corp",
            "url": None,
            "license_number": None,
            "display_source": None,
            "company": {
                "name": "Xactly Corp",
                "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHetrqDFxOMuw/company-logo_400_400/0/1657647486969?e=1672876800&v=beta&t=SnGxbQs-HLItFPZYuTR_kFJSPdXGFFy5plfKYoxVjmA",
            },
        },
        {
            "name": "Certified ScrumMaster (CSM)",
            "date": {
                "start": {"month": 12, "year": 2019},
                "end": {"month": 12, "year": 2021},
            },
            "authority": "Scrum Alliance",
            "url": "http://bcert.me/sjbeimuxq",
            "license_number": "1159213",
            "display_source": "bcert.me",
            "company": {
                "name": "Scrum Alliance",
                "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHoLJQjSDYtpg/company-logo_400_400/0/1653513869114?e=1672876800&v=beta&t=9f0iImGswyPxFYpEb78akYT7_tstv3Kf6yHedZHYY7E",
            },
        },
    ],
    "organizations": [],
    "projects": [],
    "publications": [],
    "courses": [],
    "test_scores": [],
    "position_groups": [
        {
            "company": {
                "name": "Sungard Availability Services",
                "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQFdvtSNcOMBWw/company-logo_400_400/0/1519855930181?e=1672876800&v=beta&t=ApUp0FCd4c0ZCQDrOHlTn7V8Do1nitwTW-ajnZxCduo",
                "url": "https://www.linkedin.com/company/sungard-availability-services/",
                "employees": {"start": 1001, "end": 5000},
            },
            "company_url": "https://www.linkedin.com/company/sungard-availability-services/",
            "date": {
                "start": {"month": 10, "year": 2017},
                "end": {"month": None, "year": None},
            },
            "profile_positions": [
                {
                    "location": "Wayne, Pennsylvania, United States",
                    "date": {
                        "start": {"month": 10, "year": 2020},
                        "end": {"month": None, "year": None},
                    },
                    "company": "Sungard Availability Services",
                    "description": "- Lead Lean Six Sigma Project to improve process around critical commission by product data, and move from tedious manual process to push button automated reporting\n- Led to completion Lean Six Sigma Project to convert multiple regional compensation processes into a single streamlined global process\n- Develop yearly Sales Compensation plan which aligns with company objectives, driving necessary change and focus on the future\n- Created company first systematic compensation exception request process within company\u2019s CRM environment\n- Develop and configure all aspects of company\u2019s Xactly Incent environment\n- Provide detailed reporting around sales compensation and sales performance data\n- Ensure accurate calculation and timely payment of internal and external sales commissions",
                    "title": "Senior Manager - Global Sales Compensation & Administration",
                },
                {
                    "location": "Wayne, Pennsylvania, United States",
                    "date": {
                        "start": {"month": 4, "year": 2020},
                        "end": {"month": 10, "year": 2020},
                    },
                    "company": "Sungard Availability Services",
                    "description": "- Awarded Presidents Club Award for Sales Operations in 2020\n- Collaborated interdepartmentally within Sales Operations, Channel Operations and Finance organizations to improve efficiency and accuracy of Channel Partner commission payment process\n- Lead data cleanup project to streamline 7,000+ reports and 2,000+ dashboards and develop efficient folder structure for remaining items\n- Serve as a \u201cright hand\u201d and key support to North American commercial sales leadership\n- Provide analysis and actionable interpretation of sales performance metrics and key performance indicators\n- Develop relevant and insightful dashboards and reports for reliable short and long-term sales forecasts, productivity analysis, and attainment of goals\n- Manage accuracy of sales forecast data for North American commercial sales organization with multimillion (15M+) dollar run rate account base of 1,800+ contracts\n- Champion adoption and compliance of sales and CRM process \n- Collaborate with diverse organizations within Sales and Sales Operations departments for resolution of disputes with respect to account or opportunity ownership, and sales compensation issues\n- Serve as a change agent for the design and implementation of critical sales processes and initiative improvements\n- Provide analysis of account base and contract values to be used in development of account assignments, sales quotas, and compensation rates",
                    "title": "Regional Sales Operations Director",
                },
                {
                    "location": "Wayne, Pennsylvania",
                    "date": {
                        "start": {"month": 2, "year": 2019},
                        "end": {"month": 4, "year": 2020},
                    },
                    "company": "Sungard Availability Services",
                    "description": "-Collaborated with internal IT to create company first reporting tool to track and stack rank Partner base by overall contribution, rather than individual metrics\n-Serve as change agent for new organizational strategy to increase Channel program focus and overall profitability\n-Manage relationship with primary Channel program vendor, including maintenance and improvement of online Partner Portal and negotiation of contact renewal to reduce unnecessary spend and decease overall cost\n-Create and socialize process documentation for all new process and system enhancements within Channel program\n-Held primary responsibility for tracking and analysis of Channel program Sales and Operational metrics for presentation to leadership through the use multiple reporting tools and live presentation\n-Implemented Channel program first process for tracking of return on investment related to budget spend on outside events\n-Manage Partner commissions process including audit of payments for correct percentage, and cross functional work with Sales Operations to ensure accurate payment details communicated to Partner base via Partner Portal\n-Serve as liaison between Channel organization and internal Sales Operations, IT and Pricing Desk\n-Oversight of Channel Sales Operations process to ensure accuracy and compliance with internal policies and Partner contracts regarding compensation eligibility of internal Channel Sales staff and Channel Partners\n-Thought leadership and change management around process and system improvements within the Channel organization",
                    "title": "Manager - Global Channel Programs (Channel Operations)",
                },
                {
                    "location": "Wayne, Pennsylvania",
                    "date": {
                        "start": {"month": 10, "year": 2017},
                        "end": {"month": 2, "year": 2019},
                    },
                    "company": "Sungard Availability Services",
                    "description": "-Ensure integrity of CRM data by identifying gaps, and coordinating with Account Executives to obtain missing information\n-Enable efficient sales process by ensuring timely lead conversion and creation of renewal opportunities in customized Salesforce.com platform, and by ensuring proper forecasting per company policy\n-Provide resolution and root cause analysis for customer billing issues\n-Triage credit requests to validate for accuracy and completeness prior to routing for approval\n-Provide general sales support and process guidance for Commercial Sales and Channel Sales organization\n-Review SFDC sales opportunities to determine commissions eligibility for channel partners and internal channel sales personnel\n-Provide POS reporting to key Technology Alliance partners in order to support partner relationship and maintain company's partner status\n-Create and update process documentation as needed",
                    "title": "Sales Operations Specialist",
                },
            ],
        },
        {
            "company": {
                "name": "Verizon Wireless",
                "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHAiVb75wIpDQ/company-logo_400_400/0/1645721742845?e=1672876800&v=beta&t=MgTvt-qxgp406H6V9UhMeU7v3PbVsE8vT4KpFmayx5Y",
                "url": "https://www.linkedin.com/company/verizon/",
                "employees": {"start": 10001, "end": None},
            },
            "company_url": "https://www.linkedin.com/company/verizon/",
            "date": {
                "start": {"month": 10, "year": 2006},
                "end": {"month": 5, "year": 2017},
            },
            "profile_positions": [
                {
                    "location": "Downingtown, Pennsylvania",
                    "date": {
                        "start": {"month": 11, "year": 2016},
                        "end": {"month": 5, "year": 2017},
                    },
                    "company": "Verizon",
                    "description": "Managed store inventory and operations. Assisted with customer service interactions and retail floor management duties. Maintained store appearance through merchandising and coordination of facilities and IT issues. Identified and escalated Inventory and Point of Sale systems issues. Provided recommendations for enhancement to upper management. Executed store inventory system conversion to SAP.\n-Subject Matter Expert on operational policy and procedure\n-Maintained company inventory shrink goal of 0.10%\n-Consistently received highest performance rating on annual performance reviews\n-Exceeded company standard of excellence in Net Promoter customer satisfaction rating for seven straight quarters",
                    "title": "Retail Support Specialist",
                },
                {
                    "location": "Downingtown, Pennsylvania",
                    "date": {
                        "start": {"month": 3, "year": 2014},
                        "end": {"month": 11, "year": 2016},
                    },
                    "company": "Verizon",
                    "description": "Managed all aspects of store inventory including daily shipping and receiving, stocking, storeroom organization, cycle counts and discrepancy research. Supported daily sales operations by compiling data and creating detailed reports on key metrics. Coached personnel and disseminated updates on company polices and procedures. Advised Management on strategies to successfully control costs.\n-Awarded Operations MVP July 2016\n-Second place nominee Winner\u2019s Circle 2015\n-Awarded Top Level A Store Operations 2014\n-Selected as one of six retail store employees to participate in special project to establish new internal customer support hotline\n-Selected as one of fifteen retail store employees to participate in focus and feedback group to identify opportunities in driving effective communications and streamlining frontline processes\n-On an interim basis completed Operations Sr Analyst responsibilities\n-Invited to participate in multiple store builds within Philadelphia retail territory",
                    "title": "Operations Specialist",
                },
                {
                    "location": "Pottstown, Pennsylvania",
                    "date": {
                        "start": {"month": 8, "year": 2010},
                        "end": {"month": 3, "year": 2014},
                    },
                    "company": "Verizon",
                    "description": "Assisted with customer service transactions and operational support. Conducted detailed account research to assist with customer and employee inquiries. Performed inventory shipping and receiving duties.",
                    "title": "Universal Care Representative",
                },
                {
                    "location": "Pottstown, Pennsylvania",
                    "date": {
                        "start": {"month": 12, "year": 2007},
                        "end": {"month": 8, "year": 2010},
                    },
                    "company": "Verizon",
                    "description": "Performed daily audits to ensure compliance of all company policies and procedures. Assisted with management duties including cash reconciliation and retail opening and closing procedures. Worked to resolve customer escalations. Received weekly inventory shipments and processed product return shipments.",
                    "title": "Assistant - Retail Sales Operations",
                },
                {
                    "location": "King Of Prussia, Pennsylvania",
                    "date": {
                        "start": {"month": 10, "year": 2006},
                        "end": {"month": 12, "year": 2007},
                    },
                    "company": "Verizon",
                    "description": "Assisted with daily customer service and sales support transactions. Assisted Management with daily opening and closing duties in a keyholder role. Assisted with daily Operational tasks in the absence of Operations staff.",
                    "title": "Customer Service Representative",
                },
            ],
        },
    ],
    "volunteer_experiences": [],
    "skills": [
        "Sales Operations",
        "Microsoft Excel",
        "Process Guidance",
        "Inventory Control",
        "Inventory Management",
        "Operational Excellence",
        "Operational Risk",
        "Research",
        "Vendor Management",
        "Change Management",
        "Operations Management",
        "Data Analysis",
        "Data Visualization",
        "Project Management",
        "Microsoft Office",
        "Microsoft Outlook",
        "Microsoft Word",
        "Microsoft Access",
        "Salesforce.com",
        "Leadership",
    ],
    "network_info": {
        "followable": True,
        "followers_count": 1139,
        "connections_count": 500,
    },
    "recommendations": [],
    "contact_info": {"websites": [], "email": None, "twitter": None},
    "related_profiles": [
        {
            "profile_id": "markadefrank",
            "first_name": "Mark",
            "last_name": "DeFrank",
            "title": "Senior Director - Global Sales Operations, Finance & Channels at Sungard Availability Services",
            "image_url": None,
        },
        {
            "profile_id": "darpanthaker",
            "first_name": "Darpan",
            "last_name": "T.",
            "title": "Cyber Resiliency Thought Leader | Solution Architecture | Service Development | Service Management",
            "image_url": None,
        },
        {
            "profile_id": "mark-stoecklein-3a4b541",
            "first_name": "Mark",
            "last_name": "Stoecklein",
            "title": "Consulting",
            "image_url": None,
        },
        {
            "profile_id": "meg-stclair",
            "first_name": "Meg",
            "last_name": "St. Clair, CRA",
            "title": "Grants Manager at University of Pennsylvania",
            "image_url": None,
        },
        {
            "profile_id": "heather-morris-2976a331",
            "first_name": "Heather",
            "last_name": "Morris",
            "title": "Sales Compensation Principal Analyst",
            "image_url": None,
        },
        {
            "profile_id": "ckpenkert",
            "first_name": "Kaitlyn",
            "last_name": "Penkert",
            "title": "Compensation Analyst",
            "image_url": None,
        },
        {
            "profile_id": "matt-barlow50",
            "first_name": "Matt",
            "last_name": "Barlow",
            "title": "Social Media Manager at Rabbit Hole Distillery",
            "image_url": None,
        },
        {
            "profile_id": "beverly-williams-b8084331",
            "first_name": "beverly",
            "last_name": "williams",
            "title": "accounts receivable rep at SunGard Financial Systems",
            "image_url": None,
        },
        {
            "profile_id": "juan-camilo-correa-985b2210",
            "first_name": "Juan Camilo",
            "last_name": "Correa",
            "title": "Sr Financial Analyst",
            "image_url": "https://media-exp1.licdn.com/dms/image/C4D03AQF44keCYVS5Ag/profile-displayphoto-shrink_400_400/0/1573152636789?e=1670457600&v=beta&t=kNEQ8dN9YrU9ekO-pn7UPSRmmdhlkCihJiis9DbqfWk",
        },
        {
            "profile_id": "paul-mcginnis-b253a02",
            "first_name": "Paul",
            "last_name": "McGinnis",
            "title": "Sr. Billing and Collections Specialist",
            "image_url": "https://media-exp1.licdn.com/dms/image/C5603AQEpkAnMVZHBTA/profile-displayphoto-shrink_400_400/0/1516262376372?e=1670457600&v=beta&t=Ojptbl4UVflAOPxC8XnYA14k5ugMM8StZqDKLYwGJbY",
        },
    ],
}
