"""Added bump_framework_templates table

Revision ID: 016315384ab6
Revises: 2eb16dfa4fc4
Create Date: 2023-10-02 13:46:46.786918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "016315384ab6"
down_revision = "2eb16dfa4fc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bump_framework_templates",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("raw_prompt", sa.String(), nullable=False),
        sa.Column("human_readable_prompt", sa.String(), nullable=False),
        sa.Column("length", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bump_framework_templates")
    # ### end Alembic commands ###
