"""Added final prompt column

Revision ID: 02981daadb14
Revises: e42bfa08a14e
Create Date: 2023-06-06 10:18:14.036112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02981daadb14'
down_revision = 'e42bfa08a14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_builder_samples', sa.Column('sample_final_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_builder_samples', 'sample_final_prompt')
    # ### end Alembic commands ###
