"""Added contract size

Revision ID: 03948a4376f9
Revises: 9e23084a0108
Create Date: 2023-08-21 14:13:12.007661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03948a4376f9'
down_revision = '9e23084a0108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('contract_size', sa.Integer(), server_default='10000', nullable=False))
    op.add_column('client_archetype', sa.Column('contract_size', sa.Integer(), server_default='10000', nullable=False))
    op.add_column('prospect', sa.Column('contract_size', sa.Integer(), server_default='10000', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'contract_size')
    op.drop_column('client_archetype', 'contract_size')
    op.drop_column('client', 'contract_size')
    # ### end Alembic commands ###
