"""Added generated_message_type to generated_message_job_queue

Revision ID: 0395830de173
Revises: b37c37bcbbda
Create Date: 2023-09-05 10:25:59.194964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0395830de173"
down_revision = "b37c37bcbbda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_message_job_queue",
        sa.Column(
            "generated_message_type",
            sa.Enum("LINKEDIN", "EMAIL", name="generatedmessagetype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_message_job_queue", "generated_message_type")
    # ### end Alembic commands ###
