"""emAdded client_sdr_id to bump_framework

Revision ID: 04ab5ffa9f19
Revises: d86122449acf
Create Date: 2023-04-02 21:35:12.557201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04ab5ffa9f19"
down_revision = "d86122449acf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bump_framework", sa.Column("client_sdr_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "bump_framework", "client_sdr", ["client_sdr_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bump_framework", type_="foreignkey")
    op.drop_column("bump_framework", "client_sdr_id")
    # ### end Alembic commands ###
