"""Add linkedin_active and email_active

Revision ID: 0622d9cf2fa3
Revises: bdd8c0c8507b
Create Date: 2023-11-09 14:47:22.920859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0622d9cf2fa3'
down_revision = 'bdd8c0c8507b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('linkedin_active', sa.Boolean(), nullable=True))
    op.add_column('client_archetype', sa.Column('email_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'email_active')
    op.drop_column('client_archetype', 'linkedin_active')
    # ### end Alembic commands ###
