"""Add auto_mark_as_scheduling_on_acceptance to generated_message_cta

Revision ID: 0801ca665ef2
Revises: 3b971ac45a6c
Create Date: 2023-10-03 13:14:41.357157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0801ca665ef2"
down_revision = "3b971ac45a6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_message_cta",
        sa.Column("auto_mark_as_scheduling_on_acceptance", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_message_cta", "auto_mark_as_scheduling_on_acceptance")
    # ### end Alembic commands ###
