"""Add OutboundQuotaSnapshot

Revision ID: 08fba3e39b21
Revises: 223900d8835f
Create Date: 2024-03-18 16:18:54.403349

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "08fba3e39b21"
down_revision = "223900d8835f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_quota_snapshot",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_linkedin_quota", sa.Integer(), nullable=False),
        sa.Column("total_email_quota", sa.Integer(), nullable=False),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbound_quota_snapshot")
    # ### end Alembic commands ###
