"""empty message

Revision ID: 0ad474745a60
Revises: 972f333eb440
Create Date: 2022-10-31 14:47:48.627526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad474745a60'
down_revision = '972f333eb440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message_cta', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_message_cta', 'active')
    # ### end Alembic commands ###
