"""Add domain to Client

Revision ID: 0b41a1a83941
Revises: 8dcdac4d5202
Create Date: 2024-01-04 09:34:58.514573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b41a1a83941"
down_revision = "8dcdac4d5202"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("domain", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "domain")
    # ### end Alembic commands ###
