"""add cycle data analytics table

Revision ID: 0b571e01cc08
Revises: 5be9d490f504
Create Date: 2024-08-05 16:48:33.774105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b571e01cc08'
down_revision = '5be9d490f504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_data_analytics',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('cycle_data_analytics')
    # ### end Alembic commands ###
