"""Added instruction column to voice_builder_onboarding

Revision ID: 0d043320fd84
Revises: db4494bdb337
Create Date: 2023-05-01 11:10:48.869606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d043320fd84"
down_revision = "db4494bdb337"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_builder_onboarding", sa.Column("instruction", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_builder_onboarding", "instruction")
    # ### end Alembic commands ###
