""" Add AI approved column to generated message

Revision ID: 0dbd4aafd0eb
Revises: 268caa231761
Create Date: 2023-03-17 09:39:51.500698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbd4aafd0eb'
down_revision = '268caa231761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('ai_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_message', 'ai_approved')
    # ### end Alembic commands ###
