"""Added internal_notes and requires_review to selix_session_task

Revision ID: 0dbf27eb084b
Revises: 4f286f5e2b30
Create Date: 2024-08-09 15:35:57.547538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbf27eb084b'
down_revision = '4f286f5e2b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selix_session_task', sa.Column('internal_notes', sa.String(), nullable=True))
    op.add_column('selix_session_task', sa.Column('requires_review', sa.Boolean(), nullable=True))
    op.execute("ALTER TYPE selixsessiontaskstatus ADD VALUE 'IN_PROGRESS_REVIEW_NEEDED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selix_session_task', 'requires_review')
    op.drop_column('selix_session_task', 'internal_notes')
    # ### end Alembic commands ###
