""" Add bump length to bump framework

Revision ID: 0e4658bbbfe7
Revises: 5ff0c9991ca4
Create Date: 2023-05-08 13:10:37.459552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0e4658bbbfe7'
down_revision = '5ff0c9991ca4'
branch_labels = None
depends_on = None


def upgrade():
    bump_length = postgresql.ENUM('SHORT', 'MEDIUM', 'LONG', name='bumplength')
    bump_length.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bump_framework', sa.Column('bump_length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='bumplength'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bump_framework', 'bump_length')
    # ### end Alembic commands ###
