"""Add magic subject line. 

Revision ID: 0eff055f1e50
Revises: 677d212bac54
Create Date: 2024-06-19 18:05:58.956716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0eff055f1e50'
down_revision = '677d212bac54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_subject_line_template', sa.Column('is_magic_subject_line', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_subject_line_template', 'is_magic_subject_line')
    # ### end Alembic commands ###
