"""Added linkedin initial message template library

Revision ID: 0f49ede5510a
Revises: c0f2a3066285
Create Date: 2023-11-07 13:21:59.677081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0f49ede5510a'
down_revision = 'c0f2a3066285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_initial_message_template_library',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw_prompt', sa.String(), nullable=False),
    sa.Column('human_readable_prompt', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('transformer_blocklist', sa.ARRAY(postgresql.ENUM('CURRENT_JOB_DESCRIPTION', 'CURRENT_JOB_SPECIALTIES', 'CURRENT_JOB_INDUSTRY', 'CURRENT_EXPERIENCE_DESCRIPTION', 'LINKEDIN_BIO_SUMMARY', 'YEARS_OF_EXPERIENCE', 'YEARS_OF_EXPERIENCE_AT_CURRENT_JOB', 'LIST_OF_PAST_JOBS', 'RECENT_PATENTS', 'RECENT_RECOMMENDATIONS', 'GENERAL_WEBSITE_TRANSFORMER', 'COMMON_EDUCATION', 'SERP_NEWS_SUMMARY', 'SERP_NEWS_SUMMARY_NEGATIVE', 'CUSTOM', name='researchpointtype', create_type=False)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkedin_initial_message_template_library')
    # ### end Alembic commands ###
