""" Add adversary fine tune history table

Revision ID: 0f891a6753d5
Revises: a6b98b512bd7
Create Date: 2022-12-23 16:17:27.231716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f891a6753d5'
down_revision = 'a6b98b512bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adversary_fine_tune_history',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('new_training_points', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("INSERT INTO adversary_fine_tune_history (model_name, new_training_points, active) VALUES ('davinci:ft-sellscale:baseline-adversary-5-2022-12-23-23-06-29', NULL, true);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adversary_fine_tune_history')
    # ### end Alembic commands ###
