"""empty message

Revision ID: 122862e737c1
Revises: c331ef60533b
Create Date: 2022-09-29 10:51:41.411138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122862e737c1'
down_revision = 'c331ef60533b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gnlp_models', sa.Column('model_description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gnlp_models', 'model_description')
    # ### end Alembic commands ###
