"""Added client_pod table

Revision ID: 127e3e58a027
Revises: df1674d1839a
Create Date: 2023-03-24 12:07:07.560491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "127e3e58a027"
down_revision = "df1674d1839a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_pod",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client_pod")
    # ### end Alembic commands ###
