"""Add EmailLinkClicked to Notifications and Smartlead Webhooks

Revision ID: 127e350a5c8f
Revises: 11c476b47cdd
Create Date: 2024-02-01 15:28:18.799087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "127e350a5c8f"
down_revision = "11c476b47cdd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype ADD VALUE 'EMAIL_LINK_CLICKED'")
    op.execute("ALTER TYPE smartleadwebhooktype ADD VALUE 'EMAIL_LINK_CLICKED'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype DROP VALUE 'EMAIL_LINK_CLICKED'")
    op.execute("ALTER TYPE smartleadwebhooktype DROP VALUE 'EMAIL_LINK_CLICKED'")

    # ### end Alembic commands ###
