"""Add Prospect Notes

Revision ID: 1333b5a9d398
Revises: 1f94bf1b123f
Create Date: 2022-11-14 18:11:20.501179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1333b5a9d398"
down_revision = "1f94bf1b123f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prospect_note",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prospect_note")
    # ### end Alembic commands ###
