"""Updated tables to support individuals better

Revision ID: 14c119f45f61
Revises: a3af0b47eccf
Create Date: 2023-08-09 11:08:34.693746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c119f45f61'
down_revision = 'a3af0b47eccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('li_public_id', sa.String(), nullable=True))
    op.add_column('individual', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('individual_email_key', 'individual', type_='unique')
    op.drop_constraint('individual_linkedin_url_key', 'individual', type_='unique')
    op.create_index(op.f('ix_individual_email'), 'individual', ['email'], unique=True)
    op.create_index(op.f('ix_individual_li_public_id'), 'individual', ['li_public_id'], unique=True)
    op.create_index(op.f('ix_individual_li_urn_id'), 'individual', ['li_urn_id'], unique=True)
    op.create_foreign_key(None, 'individual', 'company', ['company_id'], ['id'])
    op.drop_column('individual', 'company_url')
    op.drop_column('individual', 'company_description')
    op.drop_column('individual', 'company_size')
    op.add_column('prospect', sa.Column('individual_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prospect', 'individual', ['individual_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospect', type_='foreignkey')
    op.drop_column('prospect', 'individual_id')
    op.add_column('individual', sa.Column('company_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('individual', sa.Column('company_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('individual', sa.Column('company_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'individual', type_='foreignkey')
    op.drop_index(op.f('ix_individual_li_urn_id'), table_name='individual')
    op.drop_index(op.f('ix_individual_li_public_id'), table_name='individual')
    op.drop_index(op.f('ix_individual_email'), table_name='individual')
    op.create_unique_constraint('individual_linkedin_url_key', 'individual', ['linkedin_url'])
    op.create_unique_constraint('individual_email_key', 'individual', ['email'])
    op.drop_column('individual', 'company_id')
    op.drop_column('individual', 'li_public_id')
    # ### end Alembic commands ###
