"""Added include_in_analytics column to client

Revision ID: 15af11e1fa56
Revises: 907744af903e
Create Date: 2024-09-02 21:18:41.392960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15af11e1fa56'
down_revision = '907744af903e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('include_in_analytics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'include_in_analytics')
    # ### end Alembic commands ###
