"""added mode and rules to icp_routing

Revision ID: 17713c0655da
Revises: 7c3ef3ad6e29
Create Date: 2024-07-25 10:59:56.161123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17713c0655da'
down_revision = '7c3ef3ad6e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_routing', sa.Column('ai_mode', sa.Boolean(), nullable=False))
    op.add_column('icp_routing', sa.Column('rules', sa.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icp_routing', 'rules')
    op.drop_column('icp_routing', 'ai_mode')
    # ### end Alembic commands ###
