"""add strategies table

Revision ID: 1ce2c4478743
Revises: 26da319a7962
Create Date: 2024-07-01 14:38:14.072892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce2c4478743'
down_revision = '26da319a7962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stragegies',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tagged_campaigns', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('FAILED', 'IN_PROGRESS', 'SUCCESS', name='strategystatuses'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stragegies')
    # ### end Alembic commands ###
