"""Add canonical name to outbound campaign

Revision ID: 1e5a2218f619
Revises: e0a275cb6c56
Create Date: 2023-02-17 10:21:50.782424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5a2218f619'
down_revision = 'e0a275cb6c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_campaign', sa.Column('canonical_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_campaign', 'canonical_name')
    # ### end Alembic commands ###
