"""Updated outbound_campaign and prospect_email

Revision ID: 200820e2ecc8
Revises: dc475066e655
Create Date: 2023-02-28 14:43:05.880861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "200820e2ecc8"
down_revision = "dc475066e655"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect_email",
        sa.Column("vessel_sequence_payload_str", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect_email", "vessel_sequence_payload_str")
    # ### end Alembic commands ###
