"""Add source to sales_engagement_interaction_raw

Revision ID: 2111eb191a4e
Revises: 6f5a1a529455
Create Date: 2023-02-02 14:36:21.913137

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2111eb191a4e"
down_revision = "6f5a1a529455"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    salesengagementinteractionsource = postgresql.ENUM(
        "OUTREACH",
        "SALESLOFT",
        name="salesengagementinteractionsource",
    )
    salesengagementinteractionsource.create(op.get_bind())
    op.add_column(
        "sales_engagement_interaction_raw",
        sa.Column(
            "source",
            postgresql.ENUM(
                "OUTREACH", "SALESLOFT", name="salesengagementinteractionsource"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales_engagement_interaction_raw", "source")
    # ### end Alembic commands ###
