"""Added ProspectAI request table

Revision ID: 212e09b83a5c
Revises: 7915c9c054e6
Create Date: 2023-12-27 14:48:43.531128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "212e09b83a5c"
down_revision = "7915c9c054e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prospect_ai_requests",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("percent_complete", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "IN_PROGRESS", "COMPLETED", "FAILED", name="airequeststatus"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prospect_ai_requests")
    # ### end Alembic commands ###
