"""empty message

Revision ID: 21fa5bd1de00
Revises: 936ab0fa8034
Create Date: 2024-01-29 14:33:04.139688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "21fa5bd1de00"
down_revision = "936ab0fa8034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auto_delete_message_analytics")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_delete_message_analytics",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("prospect", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sdr_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "send_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("problem", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
