"""Add manual_trigger to ICPScoringJobQueue

Revision ID: 22de285659c6
Revises: eca974e4ba79
Create Date: 2023-09-29 13:06:39.126680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22de285659c6'
down_revision = 'eca974e4ba79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_scoring_job_queue', sa.Column('manual_trigger', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icp_scoring_job_queue', 'manual_trigger')
    # ### end Alembic commands ###
