"""empty message

Revision ID: 25ca6a8444f7
Revises: b8a2ad902f2f
Create Date: 2024-05-20 12:12:26.226083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ca6a8444f7'
down_revision = 'b8a2ad902f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_researcher',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id_created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_id_created_by'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_researcher_question',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('relevancy', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['ai_researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_researcher_question')
    op.drop_table('ai_researcher')
    # ### end Alembic commands ###
