"""Added personalized subject line and body to prospect email

Revision ID: 25d98ee3ad41
Revises: efee0d8775a8
Create Date: 2023-05-12 12:18:46.915393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25d98ee3ad41"
down_revision = "efee0d8775a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect_email",
        sa.Column("personalized_subject_line", sa.Integer(), nullable=True),
    )
    op.add_column(
        "prospect_email", sa.Column("personalized_body", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "prospect_email",
        "generated_message",
        ["personalized_subject_line"],
        ["id"],
    )
    op.create_foreign_key(
        None, "prospect_email", "generated_message", ["personalized_body"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prospect_email", type_="foreignkey")
    op.drop_constraint(None, "prospect_email", type_="foreignkey")
    op.drop_column("prospect_email", "personalized_body")
    op.drop_column("prospect_email", "personalized_subject_line")
    # ### end Alembic commands ###
