"""Added timezone to sdrs

Revision ID: 25fc3fc80536
Revises: ef0415c35f16
Create Date: 2023-04-27 17:28:34.395148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fc3fc80536'
down_revision = 'ef0415c35f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('timezone', sa.String(), server_default='America/Los_Angeles', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'timezone')
    # ### end Alembic commands ###
