"""Add DomainSetupTracker

Revision ID: 260e3d05b497
Revises: a148a90ff16f
Create Date: 2024-05-01 10:42:50.904819

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "260e3d05b497"
down_revision = "a148a90ff16f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_setup_tracker",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "PURCHASE_DOMAIN",
                "SETUP_DNS_RECORDS",
                "SETUP_FORWARDING",
                "SETUP_MAILBOXES",
                "COMPLETED",
                name="domainsetupstatuses",
            ),
            nullable=False,
        ),
        sa.Column("stage_purchase_domain", sa.Boolean(), nullable=False),
        sa.Column("stage_setup_dns_records", sa.Boolean(), nullable=False),
        sa.Column("stage_setup_forwarding", sa.Boolean(), nullable=False),
        sa.Column("setup_mailboxes", sa.Boolean(), nullable=False),
        sa.Column("setup_mailboxes_usernames", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("stage_setup_mailboxes", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "client",
        "contract_size",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("10000"),
    )
    op.add_column(
        "domain", sa.Column("domain_setup_tracker_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "domain", "domain_setup_tracker", ["domain_setup_tracker_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "domain", type_="foreignkey")
    op.drop_column("domain", "domain_setup_tracker_id")
    op.alter_column(
        "client",
        "contract_size",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("10000"),
    )
    op.drop_table("domain_setup_tracker")
    # ### end Alembic commands ###
