"""Made typo fix in prospect_email table

Revision ID: 268caa231761
Revises: cb504321dc35
Create Date: 2023-03-14 11:02:47.725091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268caa231761'
down_revision = 'cb504321dc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email', sa.Column('outbound_campaign_id', sa.Integer(), nullable=True))
    op.drop_constraint('prospect_email_oubound_campaign_id_fkey', 'prospect_email', type_='foreignkey')
    op.create_foreign_key(None, 'prospect_email', 'outbound_campaign', ['outbound_campaign_id'], ['id'])
    op.drop_column('prospect_email', 'oubound_campaign_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email', sa.Column('oubound_campaign_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prospect_email', type_='foreignkey')
    op.create_foreign_key('prospect_email_oubound_campaign_id_fkey', 'prospect_email', 'outbound_campaign', ['oubound_campaign_id'], ['id'])
    op.drop_column('prospect_email', 'outbound_campaign_id')
    # ### end Alembic commands ###
