"""Add automated flag to PESR

Revision ID: 2712f3f704c1
Revises: f91874d06f1b
Create Date: 2024-04-17 12:03:44.917822

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2712f3f704c1"
down_revision = "f91874d06f1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect_email_status_records",
        sa.Column("automated", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect_email_status_records", "automated")
    # ### end Alembic commands ###
