"""Added is_prefilter to saved_apollo_query

Revision ID: 284f18b26458
Revises: d7ac92c56e1c
Create Date: 2024-01-30 13:59:06.964117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "284f18b26458"
down_revision = "d7ac92c56e1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saved_apollo_query", sa.Column("is_prefilter", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("saved_apollo_query", "is_prefilter")
    # ### end Alembic commands ###
