"""Added linkedin msg urn id to conversation entry

Revision ID: 2b6f4e27b8d8
Revises: 87650f7d1bf3
Create Date: 2023-03-29 11:19:53.914085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6f4e27b8d8'
down_revision = '87650f7d1bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_conversation_entry', sa.Column('urn_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_conversation_entry', 'urn_id')
    # ### end Alembic commands ###
