"""Add manual warning message to client sdr

Revision ID: 2e11a2288366
Revises: 882f2f7b384a
Create Date: 2023-01-04 16:24:14.654421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e11a2288366"
down_revision = "882f2f7b384a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sdr", sa.Column("manual_warning_message", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "manual_warning_message")
    # ### end Alembic commands ###
