"""Add problems and highlighted words to Voice Builder

Revision ID: 2eb16dfa4fc4
Revises: 22de285659c6
Create Date: 2023-10-02 11:37:29.475118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb16dfa4fc4'
down_revision = '22de285659c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_builder_samples', sa.Column('sample_problems', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('voice_builder_samples', sa.Column('sample_highlighted_words', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_builder_samples', 'sample_highlighted_words')
    op.drop_column('voice_builder_samples', 'sample_problems')
    # ### end Alembic commands ###
