"""Add auto_generate_li_messages and auto_send_li_messages to Client

Revision ID: 2f8aedd174c4
Revises: f6ee0e1ba58b
Create Date: 2023-11-15 16:21:55.464899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8aedd174c4'
down_revision = 'f6ee0e1ba58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('auto_generate_li_messages', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('auto_send_li_messages', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'auto_send_li_messages')
    op.drop_column('client', 'auto_generate_li_messages')
    # ### end Alembic commands ###
