"""Add aws_autorenew_enabled

Revision ID: 302da5c7ecec
Revises: c2dbc69beed7
Create Date: 2024-04-08 15:40:48.527467

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "302da5c7ecec"
down_revision = "c2dbc69beed7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domain", sa.Column("aws_autorenew_enabled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain", "aws_autorenew_enabled")
    # ### end Alembic commands ###
