"""Added demo_date to prospect

Revision ID: 3101caedb4f8
Revises: 38a35ef58059
Create Date: 2023-05-04 16:19:51.139998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3101caedb4f8"
down_revision = "38a35ef58059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prospect", sa.Column("demo_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "demo_date")
    # ### end Alembic commands ###
