"""empty message

Revision ID: 3117503de947
Revises: 50ce74b4052c
Create Date: 2022-09-29 14:48:14.485882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3117503de947'
down_revision = '50ce74b4052c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('contacted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'contacted')
    # ### end Alembic commands ###
