"""Added template mode

Revision ID: 31367ab167d6
Revises: 5331be668060
Create Date: 2023-10-31 12:37:59.039397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31367ab167d6'
down_revision = '5331be668060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('template_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'template_mode')
    # ### end Alembic commands ###
