"""Added Bump Framework

Revision ID: 31c85cdb232d
Revises: 0622452f2501
Create Date: 2023-03-28 15:46:40.041269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "31c85cdb232d"
down_revision = "0622452f2501"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bump_framework",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("client_sdr_id", sa.Integer(), nullable=False),
        sa.Column(
            "overall_status",
            postgresql.ENUM(
                "PROSPECTED",
                "SENT_OUTREACH",
                "ACCEPTED",
                "BUMPED",
                "ACTIVE_CONVO",
                "DEMO",
                "REMOVED",
                name="prospectoverallstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["client_sdr_id"],
            ["client_sdr.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bump_framework")
    # ### end Alembic commands ###
