"""empty message

Revision ID: 3265f54af86c
Revises: f72cab7a3639
Create Date: 2022-10-01 18:29:57.832921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3265f54af86c"
down_revision = "f72cab7a3639"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    prospectstatus = sa.Enum(
        "PROSPECTED",
        "NOT_QUALIFIED",
        "SENT_OUTREACH",
        "RESPONDED",
        "NOT_INTERESTED",
        "DEMO_SET",
        "DEMO_WON",
        "DEMO_LOSS",
        name="prospectstatus",
    )
    prospectstatus.create(op.get_bind())

    op.add_column(
        "prospect",
        sa.Column(
            "status",
            sa.Enum(
                "PROSPECTED",
                "NOT_QUALIFIED",
                "SENT_OUTREACH",
                "RESPONDED",
                "NOT_INTERESTED",
                "DEMO_SET",
                "DEMO_WON",
                "DEMO_LOSS",
                name="prospectstatus",
            ),
            nullable=True,
        ),
    )

    op.drop_column("prospect", "contacted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect",
        sa.Column("contacted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("prospect", "status")
    # ### end Alembic commands ###
