"""Add email_blocks_configuration to ClientArchetype

Revision ID: 3270144660f6
Revises: 0fcc7ca9f8e7
Create Date: 2023-06-07 17:31:44.276133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3270144660f6'
down_revision = '0fcc7ca9f8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('email_blocks_configuration', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'email_blocks_configuration')
    # ### end Alembic commands ###
