"""Add SDREmailBank

Revision ID: 33104a9d9e38
Revises: e7465cf48c8a
Create Date: 2023-10-06 13:06:57.345292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33104a9d9e38'
down_revision = 'e7465cf48c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdr_email_bank',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('email_type', sa.Enum('ANCHOR', 'SELLSCALE', 'ALIAS', name='emailtype'), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=False),
    sa.Column('nylas_auth_code', sa.String(), nullable=True),
    sa.Column('nylas_account_id', sa.String(), nullable=True),
    sa.Column('nylas_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdr_email_bank')
    # ### end Alembic commands ###
