"""Added message_generation_captivate_mode to client_sdr

Revision ID: 33b8e517687c
Revises: f6154585adfd
Create Date: 2023-06-12 11:28:39.445969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33b8e517687c"
down_revision = "f6154585adfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sdr",
        sa.Column("message_generation_captivate_mode", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "message_generation_captivate_mode")
    # ### end Alembic commands ###
