"""Create EmailReplyFramework

Revision ID: 34058102582e
Revises: 92d48ebbfbc1
Create Date: 2024-01-09 15:31:33.512126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "34058102582e"
down_revision = "92d48ebbfbc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_reply_framework",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("client_sdr_id", sa.Integer(), nullable=True),
        sa.Column("client_archetype_id", sa.Integer(), nullable=True),
        sa.Column(
            "overall_status",
            postgresql.ENUM(
                "PROSPECTED",
                "SENT_OUTREACH",
                "ACCEPTED",
                "BUMPED",
                "ACTIVE_CONVO",
                "DEMO",
                "REMOVED",
                "NURTURE",
                name="prospectoverallstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("substatus", sa.String(length=255), nullable=True),
        sa.Column("reply_prompt", sa.String(), nullable=True),
        sa.Column("times_used", sa.Integer(), nullable=True),
        sa.Column("times_accepted", sa.Integer(), nullable=True),
        sa.Column(
            "research_blocklist",
            postgresql.ENUM(
                "CURRENT_JOB_DESCRIPTION",
                "CURRENT_JOB_SPECIALTIES",
                "CURRENT_JOB_INDUSTRY",
                "CURRENT_EXPERIENCE_DESCRIPTION",
                "LINKEDIN_BIO_SUMMARY",
                "YEARS_OF_EXPERIENCE",
                "YEARS_OF_EXPERIENCE_AT_CURRENT_JOB",
                "LIST_OF_PAST_JOBS",
                "RECENT_PATENTS",
                "RECENT_RECOMMENDATIONS",
                "GENERAL_WEBSITE_TRANSFORMER",
                "COMMON_EDUCATION",
                "SERP_NEWS_SUMMARY",
                "SERP_NEWS_SUMMARY_NEGATIVE",
                "CUSTOM",
                name="researchpointtype",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("use_account_research", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_archetype_id"],
            ["client_archetype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_sdr_id"],
            ["client_sdr.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_reply_framework")
    # ### end Alembic commands ###
