"""Change reply_prompt to reply_instructions and add description

Revision ID: 3478a7fcd78d
Revises: 34058102582e
Create Date: 2024-01-10 12:43:29.701624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3478a7fcd78d"
down_revision = "34058102582e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_reply_framework",
        sa.Column("description", sa.String(length=4000), nullable=True),
    )
    op.add_column(
        "email_reply_framework",
        sa.Column("reply_instructions", sa.String(), nullable=True),
    )
    op.drop_column("email_reply_framework", "reply_prompt")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_reply_framework",
        sa.Column("reply_prompt", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("email_reply_framework", "reply_instructions")
    op.drop_column("email_reply_framework", "description")
    # ### end Alembic commands ###
