""" Add adversary training point table.

Revision ID: 348209d8437f
Revises: 38826ce0bf0a
Create Date: 2022-12-20 10:55:31.341462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348209d8437f'
down_revision = '38826ce0bf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adversary_training_point',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_message_id', sa.Integer(), nullable=False),
    sa.Column('generated_message_type', sa.Enum('LINKEDIN', 'EMAIL', name='generatedmessagetype'), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('completion', sa.String(), nullable=False),
    sa.Column('mistake_description', sa.String(), nullable=False),
    sa.Column('fix_instuctions', sa.String(), nullable=False),
    sa.Column('use_in_training', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generated_message_id'], ['generated_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adversary_training_point')
    # ### end Alembic commands ###
