"""Added vessel_personalization_field_name to client

Revision ID: 35af94f00826
Revises: 07525d3c963b
Create Date: 2023-03-02 13:25:31.189757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35af94f00826"
down_revision = "07525d3c963b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column("vessel_personalization_field_name", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "vessel_personalization_field_name")
    # ### end Alembic commands ###
