"""Adds column to bump_framework, generated_message_cta, stack_ranked_message_generation_configuration,
to include the internal_default_voice_id
For generated_message_cta, add constraint

Revision ID: 35b16decb4c0
Revises: f5ea22278265
Create Date: 2024-07-29 19:19:08.021699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b16decb4c0'
down_revision = 'f5ea22278265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bump_framework', sa.Column('internal_default_voice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bump_framework', 'internal_default_voices', ['internal_default_voice_id'], ['id'])
    op.add_column('generated_message_cta', sa.Column('internal_default_voice_id', sa.Integer(), nullable=True))
    op.alter_column('generated_message_cta', 'archetype_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'generated_message_cta', 'internal_default_voices', ['internal_default_voice_id'], ['id'])
    op.add_column('stack_ranked_message_generation_configuration', sa.Column('internal_default_voice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stack_ranked_message_generation_configuration', 'internal_default_voices', ['internal_default_voice_id'], ['id'])
    op.create_check_constraint('archetype_id_or_internal_default_voice_id_not_null', 'generated_message_cta', '(archetype_id IS NOT NULL OR internal_default_voice_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stack_ranked_message_generation_configuration', type_='foreignkey')
    op.drop_column('stack_ranked_message_generation_configuration', 'internal_default_voice_id')
    op.drop_constraint(None, 'generated_message_cta', type_='foreignkey')
    op.alter_column('generated_message_cta', 'archetype_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('generated_message_cta', 'internal_default_voice_id')
    op.drop_constraint(None, 'bump_framework', type_='foreignkey')
    op.drop_column('bump_framework', 'internal_default_voice_id')
    op.drop_constraint('archetype_id_or_internal_default_voice_id_not_null', 'generated_message_cta')
    # ### end Alembic commands ###
