"""Added ai_voice table

Revision ID: 36ca895f6903
Revises: 82071d29d971
Create Date: 2024-06-27 11:02:37.416520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ca895f6903'
down_revision = '82071d29d971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_voice',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_created_by'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client_archetype', sa.Column('ai_voice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_archetype', 'ai_voice', ['ai_voice_id'], ['id'])
    op.add_column('few_shot', sa.Column('ai_voice_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'few_shot', 'ai_voice', ['ai_voice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'few_shot', type_='foreignkey')
    op.drop_column('few_shot', 'ai_voice_id')
    op.drop_constraint(None, 'client_archetype', type_='foreignkey')
    op.drop_column('client_archetype', 'ai_voice_id')
    op.drop_table('ai_voice')
    # ### end Alembic commands ###
