"""Switched scrape queue column with prospect urn id

Revision ID: 377a62b961c3
Revises: 00bb365573b8
Create Date: 2023-04-20 01:27:00.192680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377a62b961c3'
down_revision = '00bb365573b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_conversation_scrape_queue', sa.Column('prospect_urn_id', sa.String(), nullable=True))
    op.drop_constraint('linkedin_conversation_scrape_queue_prospect_id_fkey', 'linkedin_conversation_scrape_queue', type_='foreignkey')
    op.drop_column('linkedin_conversation_scrape_queue', 'prospect_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_conversation_scrape_queue', sa.Column('prospect_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('linkedin_conversation_scrape_queue_prospect_id_fkey', 'linkedin_conversation_scrape_queue', 'prospect', ['prospect_id'], ['id'])
    op.drop_column('linkedin_conversation_scrape_queue', 'prospect_urn_id')
    # ### end Alembic commands ###
