"""Create Domain table

Revision ID: 385cc0fbc605
Revises: d4ddcb53240f
Create Date: 2023-12-27 12:15:05.734596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "385cc0fbc605"
down_revision = "d4ddcb53240f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("forward_to", sa.String(length=255), nullable=True),
        sa.Column("aws", sa.Boolean(), nullable=False),
        sa.Column("aws_hosted_zone_id", sa.String(), nullable=True),
        sa.Column("dmarc_record", sa.String(), nullable=True),
        sa.Column("dmarc_record_valid", sa.Boolean(), nullable=True),
        sa.Column("spf_record", sa.String(), nullable=True),
        sa.Column("spf_record_valid", sa.Boolean(), nullable=True),
        sa.Column("dkim_record", sa.String(), nullable=True),
        sa.Column("dkim_record_valid", sa.Boolean(), nullable=True),
        sa.Column("forwarding_enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("domain")
    # ### end Alembic commands ###
