"""Added company identify api and payload to track event

Revision ID: 39eab9df99a0
Revises: 5b1ae87816d7
Create Date: 2024-01-20 17:25:46.584391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39eab9df99a0"
down_revision = "5b1ae87816d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_event", sa.Column("company_identify_api", sa.String(), nullable=True)
    )
    op.add_column(
        "track_event", sa.Column("company_identify_payload", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track_event", "company_identify_payload")
    op.drop_column("track_event", "company_identify_api")
    # ### end Alembic commands ###
