"""add custom_name to saved_apollo_query

Revision ID: 3a9df595161a
Revises: 1a1de7b30e5c
Create Date: 2024-07-18 12:46:45.492222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9df595161a'
down_revision = '1a1de7b30e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_apollo_query', sa.Column('custom_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_apollo_query', 'custom_name')
    # ### end Alembic commands ###
