"""Add ProspectInSmartlead logger model

Revision ID: 3ad59488f9da
Revises: db961dab9c48
Create Date: 2024-03-15 12:47:58.168607

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ad59488f9da"
down_revision = "db961dab9c48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prospect_in_smartlead",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=True),
        sa.Column("in_smartlead", sa.Boolean(), nullable=True),
        sa.Column("log", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prospect_in_smartlead")
    # ### end Alembic commands ###
