"""empty message

Revision ID: 3b971ac45a6c
Revises: 942dd43c03e4
Create Date: 2023-10-03 12:04:06.388388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b971ac45a6c"
down_revision = "942dd43c03e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_archetype", sa.Column("persona_filters", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_archetype", "persona_filters")
    # ### end Alembic commands ###
