"""empty message

Revision ID: 3be2527f1609
Revises: 109daae1613f
Create Date: 2022-11-02 10:33:43.679217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be2527f1609'
down_revision = '109daae1613f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('notification_allowlist', sa.ARRAY(sa.Enum('PROSPECTED', 'NOT_QUALIFIED', 'SENT_OUTREACH', 'ACCEPTED', 'RESPONDED', 'ACTIVE_CONVO', 'SCHEDULING', 'NOT_INTERESTED', 'DEMO_SET', 'DEMO_WON', 'DEMO_LOSS', name='prospectstatus')), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'notification_allowlist')
    # ### end Alembic commands ###
