"""Added draft_session column to selix_session

Revision ID: 3e2f162ed528
Revises: 0dbf27eb084b
Create Date: 2024-08-12 17:37:36.508840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2f162ed528'
down_revision = '0dbf27eb084b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selix_session', sa.Column('draft_session', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selix_session', 'draft_session')
    # ### end Alembic commands ###
