"""add few shot table

Revision ID: 3fd3b47fae9e
Revises: e8c08a4b9896
Create Date: 2024-06-25 22:50:55.400250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fd3b47fae9e'
down_revision = 'e8c08a4b9896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('few_shot', sa.Column('client_archetype_id', sa.Integer(), nullable=False))
    op.add_column('few_shot', sa.Column('original_string', sa.String(), nullable=False))
    op.add_column('few_shot', sa.Column('edited_string', sa.String(), nullable=False))
    op.add_column('few_shot', sa.Column('nuance', sa.String(), nullable=False))
    op.alter_column('few_shot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'few_shot', 'client_archetype', ['client_archetype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'few_shot', type_='foreignkey')
    op.drop_column('few_shot', 'nuance')
    op.drop_column('few_shot', 'edited_string')
    op.drop_column('few_shot', 'original_string')
    op.drop_column('few_shot', 'client_archetype_id')
    # ### end Alembic commands ###
