"""add is_setting_up to archetype

Revision ID: 4067613eb8e1
Revises: 0b30fa9e409c
Create Date: 2024-06-03 14:53:01.919750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4067613eb8e1'
down_revision = '0b30fa9e409c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('is_setting_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'is_setting_up')
    # ### end Alembic commands ###
