"""Add several columns to icp_score_ruleset table
to support market map scoring and AI filters

Revision ID: 406e81fa5ab2
Revises: e4a2af977467
Create Date: 2024-08-02 11:09:14.702841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406e81fa5ab2'
down_revision = 'e4a2af977467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_scoring_ruleset', sa.Column('dealbreakers', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('icp_scoring_ruleset', sa.Column('individual_personalizers', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('icp_scoring_ruleset', sa.Column('company_personalizers', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('icp_scoring_ruleset', sa.Column('individual_ai_filters', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('icp_scoring_ruleset', sa.Column('company_ai_filters', sa.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icp_scoring_ruleset', 'company_ai_filters')
    op.drop_column('icp_scoring_ruleset', 'individual_ai_filters')
    op.drop_column('icp_scoring_ruleset', 'company_personalizers')
    op.drop_column('icp_scoring_ruleset', 'individual_personalizers')
    op.drop_column('icp_scoring_ruleset', 'dealbreakers')
    # ### end Alembic commands ###
