"""Creating a new table that represents the internal default voices
that is used as a template to create new campaigns.

Revision ID: 40eb6778d331
Revises: 940bee508f59
Create Date: 2024-07-29 18:37:42.695805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40eb6778d331'
down_revision = '940bee508f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_default_voices',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_default_voices')
    # ### end Alembic commands ###
