"""Added territory_name column to client_sdr

Revision ID: 41530d7728d3
Revises: 7afc2ac47f89
Create Date: 2024-02-07 08:49:44.863238

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41530d7728d3"
down_revision = "7afc2ac47f89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client_sdr", sa.Column("territory_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "territory_name")
    # ### end Alembic commands ###
