"""Added last_slack_msg_date to client

Revision ID: 45b5ac9ac641
Revises: 5fca5c77e7e7
Create Date: 2023-11-28 17:10:05.910990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45b5ac9ac641"
down_revision = "5fca5c77e7e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client", sa.Column("last_slack_msg_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "last_slack_msg_date")
    # ### end Alembic commands ###
