"""linkedin-ai-reply

Revision ID: 45c457cdc025
Revises: 925e22b59d69
Create Date: 2024-02-13 00:40:01.259276

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45c457cdc025"
down_revision = "58a21c4b7e80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype ADD VALUE 'LINKEDIN_AI_REPLY'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype DROP VALUE 'LINKEDIN_AI_REPLY'")

    # ### end Alembic commands ###
