"""Added trigger_run and trigger_prospect tables

Revision ID: 461f48632ce2
Revises: 2c62d4015f7e
Create Date: 2023-11-21 12:46:49.090656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "461f48632ce2"
down_revision = "2c62d4015f7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trigger_run",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger_id", sa.Integer(), nullable=False),
        sa.Column("run_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("run_status", sa.String(), nullable=False),
        sa.Column("run_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["trigger.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trigger_prospect",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("linkedin_url", sa.String(), nullable=True),
        sa.Column("custom_data", sa.String(), nullable=True),
        sa.Column("trigger_run_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trigger_run_id"],
            ["trigger_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trigger_prospect")
    op.drop_table("trigger_run")
    # ### end Alembic commands ###
