"""Added last_li_at_token

Revision ID: 4a6d475091eb
Revises: 8128a1de61a6
Create Date: 2024-07-26 13:36:16.431013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6d475091eb'
down_revision = '8128a1de61a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('last_li_at_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'last_li_at_token')
    # ### end Alembic commands ###
