"""Added client_archetype_id to phantom_buster_sales_navigator_config

Revision ID: 4acbc5cb82e7
Revises: b8e1c7c9eaa6
Create Date: 2023-09-06 21:33:55.165784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4acbc5cb82e7"
down_revision = "b8e1c7c9eaa6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phantom_buster_sales_navigator_config",
        sa.Column("client_archetype_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "phantom_buster_sales_navigator_config",
        "client_archetype",
        ["client_archetype_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "phantom_buster_sales_navigator_config", type_="foreignkey"
    )
    op.drop_column("phantom_buster_sales_navigator_config", "client_archetype_id")
    # ### end Alembic commands ###
