"""Added do not contact fields

Revision ID: 4b278a47ff33
Revises: 0622d9cf2fa3
Create Date: 2023-11-13 13:21:32.241305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b278a47ff33'
down_revision = '0622d9cf2fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('do_not_contact_industries', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('client', sa.Column('do_not_contact_location_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('client', sa.Column('do_not_contact_titles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('client_sdr', sa.Column('do_not_contact_industries', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('client_sdr', sa.Column('do_not_contact_location_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('client_sdr', sa.Column('do_not_contact_titles', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'do_not_contact_titles')
    op.drop_column('client_sdr', 'do_not_contact_location_keywords')
    op.drop_column('client_sdr', 'do_not_contact_industries')
    op.drop_column('client', 'do_not_contact_titles')
    op.drop_column('client', 'do_not_contact_location_keywords')
    op.drop_column('client', 'do_not_contact_industries')
    # ### end Alembic commands ###
