"""Added company table

Revision ID: 4b42dd8bc6ce
Revises: ef733e235c86
Create Date: 2023-05-11 12:01:22.284943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b42dd8bc6ce'
down_revision = 'ef733e235c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('universal_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('img_cover_url', sa.String(), nullable=True),
    sa.Column('img_logo_url', sa.String(), nullable=True),
    sa.Column('li_followers', sa.Integer(), nullable=True),
    sa.Column('li_company_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('websites', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('specialities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('industries', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('locations', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('career_page_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_li_company_id'), 'company', ['li_company_id'], unique=True)
    op.create_index(op.f('ix_company_universal_name'), 'company', ['universal_name'], unique=True)
    op.create_table('company_relation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id_pair', sa.Integer(), nullable=False),
    sa.Column('company_id_1', sa.Integer(), nullable=False),
    sa.Column('company_id_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id_1'], ['company.id'], ),
    sa.ForeignKeyConstraint(['company_id_2'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_relation')
    op.drop_index(op.f('ix_company_universal_name'), table_name='company')
    op.drop_index(op.f('ix_company_li_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
