"""EmailMessageThread takes Nylas data

Revision ID: 4b63bd246295
Revises: fb790d01bce6
Create Date: 2023-05-04 11:23:42.018586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b63bd246295'
down_revision = 'fb790d01bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_conversation_thread', sa.Column('first_message_timestamp', sa.DateTime(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('last_message_received_timestamp', sa.DateTime(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('last_message_sent_timestamp', sa.DateTime(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('last_message_timestamp', sa.DateTime(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('participants', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('has_attachments', sa.Boolean(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('unread', sa.Boolean(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('nylas_message_ids', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('email_conversation_thread', sa.Column('nylas_data_raw', sa.JSON(), nullable=False))
    op.drop_column('email_conversation_thread', 'nylas_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_conversation_thread', sa.Column('nylas_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('email_conversation_thread', 'nylas_data_raw')
    op.drop_column('email_conversation_thread', 'nylas_message_ids')
    op.drop_column('email_conversation_thread', 'version')
    op.drop_column('email_conversation_thread', 'unread')
    op.drop_column('email_conversation_thread', 'has_attachments')
    op.drop_column('email_conversation_thread', 'participants')
    op.drop_column('email_conversation_thread', 'last_message_timestamp')
    op.drop_column('email_conversation_thread', 'last_message_sent_timestamp')
    op.drop_column('email_conversation_thread', 'last_message_received_timestamp')
    op.drop_column('email_conversation_thread', 'first_message_timestamp')
    # ### end Alembic commands ###
