"""Added apollo uuid

Revision ID: 4c38312bd780
Revises: 7fcff8ed74e8
Create Date: 2024-05-17 18:16:37.011492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c38312bd780'
down_revision = '7fcff8ed74e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('apollo_uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_company_apollo_uuid'), 'company', ['apollo_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_apollo_uuid'), table_name='company')
    op.drop_column('company', 'apollo_uuid')
    # ### end Alembic commands ###
