""" Add questionnaire column to SDR

Revision ID: 4cd0cf89ab71
Revises: b7e38d32625b
Create Date: 2023-03-09 12:30:07.384613

"""
from alembic import op
import sqlalchemy as sa

from src.client.models import SDRQuestionaireColumn


# revision identifiers, used by Alembic.
revision = '4cd0cf89ab71'
down_revision = 'b7e38d32625b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('questionnaire', SDRQuestionaireColumn(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'questionaire')
    # ### end Alembic commands ###
