"""Added active column to editor

Revision ID: 4e1feddd28a3
Revises: ce28ddf317e7
Create Date: 2023-01-18 17:16:43.367353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e1feddd28a3"
down_revision = "ce28ddf317e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("editor", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("editor", "active")
    # ### end Alembic commands ###
