"""ai_task_completed

Revision ID: 4e8c385149ba
Revises: fb39ffe22036
Create Date: 2024-02-09 01:10:10.152421

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e8c385149ba"
down_revision = "6f4d8de57436"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype ADD VALUE 'AI_TASK_COMPLETED'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype DROP VALUE 'AI_TASK_COMPLETED'")

    # ### end Alembic commands ###
