"""Added highlighted_words to generated_message

Revision ID: 4ebf8bc0eca8
Revises: ffb0db601585
Create Date: 2023-02-01 17:27:40.710647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ebf8bc0eca8"
down_revision = "ffb0db601585"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_message",
        sa.Column("highlighted_words", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_message", "highlighted_words")
    # ### end Alembic commands ###
