"""empty message

Revision ID: 4fe7a934767e
Revises: 1333b5a9d398
Create Date: 2022-11-14 19:32:56.044574

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "4fe7a934767e"
down_revision = "1333b5a9d398"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_campaign",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("prospect_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "campaign_type",
            postgresql.ENUM(
                "LINKEDIN", "EMAIL", name="generatedmessagetype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("ctas", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("client_archetype_id", sa.Integer(), nullable=False),
        sa.Column("client_sdr_id", sa.Integer(), nullable=False),
        sa.Column("campaign_start_date", sa.DateTime(), nullable=False),
        sa.Column("campaign_end_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "NEEDS_REVIEW",
                "IN_PROGRESS",
                "COMPLETE",
                "CANCELLED",
                name="outboundcampaignstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_archetype_id"],
            ["client_archetype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_sdr_id"],
            ["client_sdr.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbound_campaign")
    # ### end Alembic commands ###
