"""Add EmailStore (Hunter) and email_store_id to Prospect

Revision ID: 5043fb310a7e
Revises: d6665ef816e9
Create Date: 2023-08-07 14:43:29.549235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5043fb310a7e'
down_revision = 'd6665ef816e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_store',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('hunter_status', sa.String(), nullable=True),
    sa.Column('hunter_score', sa.Integer(), nullable=True),
    sa.Column('hunter_regexp', sa.Boolean(), nullable=True),
    sa.Column('hunter_gibberish', sa.Boolean(), nullable=True),
    sa.Column('hunter_disposable', sa.Boolean(), nullable=True),
    sa.Column('hunter_webmail', sa.Boolean(), nullable=True),
    sa.Column('hunter_mx_records', sa.Boolean(), nullable=True),
    sa.Column('hunter_smtp_server', sa.Boolean(), nullable=True),
    sa.Column('hunter_smtp_check', sa.Boolean(), nullable=True),
    sa.Column('hunter_accept_all', sa.Boolean(), nullable=True),
    sa.Column('hunter_block', sa.Boolean(), nullable=True),
    sa.Column('hunter_sources', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('verification_status_hunter', sa.Enum('COMPLETE', 'IN_PROGRESS', 'PENDING', 'FAILED', name='hunterverifystatus'), nullable=True),
    sa.Column('verification_status_hunter_attempts', sa.Integer(), nullable=True),
    sa.Column('verification_status_hunter_error', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_store_email'), 'email_store', ['email'], unique=True)
    op.add_column('prospect', sa.Column('email_store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prospect', 'email_store', ['email_store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospect', type_='foreignkey')
    op.drop_column('prospect', 'email_store_id')
    op.drop_index(op.f('ix_email_store_email'), table_name='email_store')
    op.drop_table('email_store')
    # ### end Alembic commands ###
