"""empty message

Revision ID: 50ce74b4052c
Revises: dcc232b5aee1
Create Date: 2022-09-29 14:21:42.251598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ce74b4052c'
down_revision = 'dcc232b5aee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('batch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'batch')
    # ### end Alembic commands ###
