"""empty message

Revision ID: 5115e7613ffe
Revises: e67f50d2d3ad
Create Date: 2024-08-22 12:12:04.294226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5115e7613ffe'
down_revision = 'e67f50d2d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selix_session', 'widget_type')
    op.add_column('selix_session_task', sa.Column('widget_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selix_session_task', 'widget_type')
    op.add_column('selix_session', sa.Column('widget_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
