"""Add SDREmailSendSchedule table

Revision ID: 51de00f7f479
Revises: d1617d0da11c
Create Date: 2023-10-10 16:19:37.901787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51de00f7f479'
down_revision = 'd1617d0da11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdr_email_send_schedule',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=False),
    sa.Column('email_bank_id', sa.Integer(), nullable=False),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.Column('days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.ForeignKeyConstraint(['email_bank_id'], ['sdr_email_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdr_email_send_schedule')
    # ### end Alembic commands ###
