"""Added role

Revision ID: 52cd802c9576
Revises: f5fa0ef6aecf
Create Date: 2024-05-08 11:13:56.478365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cd802c9576'
down_revision = 'f5fa0ef6aecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('prospect', 'contract_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prospect', 'contract_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('client_sdr', 'role')
    # ### end Alembic commands ###
