"""Added email new inbox created slack notification

Revision ID: 53ecb4f66b11
Revises: 292bfc6879f6
Create Date: 2024-03-06 11:29:45.423014

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53ecb4f66b11"
down_revision = "292bfc6879f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype ADD VALUE 'EMAIL_NEW_INBOX_CREATED'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype DROP VALUE 'EMAIL_NEW_INBOX_CREATED'")

    # ### end Alembic commands ###
