"""Added linkedin_initial_message_to_asset_mapping table

Revision ID: 55a524e88e5d
Revises: 15386a5f1b93
Create Date: 2024-03-10 21:59:43.638109

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55a524e88e5d"
down_revision = "15386a5f1b93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linkedin_initial_message_to_asset_mapping",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("linkedin_initial_message_id", sa.Integer(), nullable=False),
        sa.Column("client_assets_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_assets_id"],
            ["client_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linkedin_initial_message_id"],
            ["linkedin_initial_message_template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linkedin_initial_message_to_asset_mapping")
    # ### end Alembic commands ###
