"""empty message

Revision ID: 58a21c4b7e80
Revises: 62c382110a13
Create Date: 2024-02-15 13:28:21.923792

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58a21c4b7e80"
down_revision = "62c382110a13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_archetype_asset_reason_mapping",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_archetype_asset_id", sa.Integer(), nullable=False),
        sa.Column("client_archetype_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_archetype_asset_id"],
            ["client_archetype_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_archetype_id"],
            ["client_archetype.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("client_archetype_assets", "asset_reason")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_archetype_assets",
        sa.Column("asset_reason", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("client_archetype_asset_reason_mapping")
    # ### end Alembic commands ###
