"""Added setup_status column to client_archetype

Revision ID: 5a907be7da9b
Revises: 4067613eb8e1
Create Date: 2024-06-07 11:44:49.534469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a907be7da9b'
down_revision = '4067613eb8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    setup_status_enum = sa.Enum('SETUP', 'ACTIVE', 'INACTIVE', name='clientarchetypesetupenum')
    setup_status_enum.create(op.get_bind())

    op.add_column('client_archetype', sa.Column('setup_status', sa.Enum('SETUP', 'ACTIVE', 'INACTIVE', name='clientarchetypesetupenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'setup_status')
    # ### end Alembic commands ###
