"""Restructure SlackNotification (add, edit)


Revision ID: 5ac2c4b99dd2
Revises: e3f80d41821b
Create Date: 2024-01-18 15:27:44.834056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ac2c4b99dd2"
down_revision = "e3f80d41821b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_notification",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum("AI_REPLY_TO_EMAIL", name="slacknotificationtype"),
            nullable=False,
        ),
        sa.Column("notification_name", sa.String(length=255), nullable=False),
        sa.Column("notification_description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "sent_slack_notification",
        sa.Column(
            "notification_type",
            sa.Enum("AI_REPLY_TO_EMAIL", name="slacknotificationtype"),
            nullable=False,
        ),
    )
    op.drop_column("sent_slack_notification", "type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sent_slack_notification",
        sa.Column("type", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("sent_slack_notification", "notification_type")
    op.drop_table("slack_notification")
    # ### end Alembic commands ###
