"""Added last_li_conversation_scrape_date to client_sdr

Revision ID: 5acc1b4d5c67
Revises: 311dc37b9275
Create Date: 2023-01-26 10:12:39.337824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5acc1b4d5c67"
down_revision = "311dc37b9275"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sdr",
        sa.Column("last_li_conversation_scrape_date", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "last_li_conversation_scrape_date")
    # ### end Alembic commands ###
