"""Vessel model removal, vessel id removal from archetype

Revision ID: 5aed1b44c6a6
Revises: b5fa4bdb550f
Create Date: 2023-09-07 12:01:03.350948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5aed1b44c6a6'
down_revision = 'b5fa4bdb550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_mailboxes')
    op.drop_table('vessel_api_cached_responses')
    op.drop_table('vessel_sequences')
    op.drop_column('client_archetype', 'vessel_sequence_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('vessel_sequence_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('vessel_sequences',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sequence_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='vessel_sequences_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vessel_sequences_pkey')
    )
    op.create_table('vessel_api_cached_responses',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vessel_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequence_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vessel_api_cached_responses_pkey')
    )
    op.create_table('vessel_mailboxes',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mailbox_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='vessel_mailboxes_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vessel_mailboxes_pkey')
    )
    # ### end Alembic commands ###
