"""Added vessel_sequence_id to client_archetype and prospect_email

Revision ID: 5b2d89569c2a
Revises: f72921f36f36
Create Date: 2023-04-17 19:55:03.416171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b2d89569c2a"
down_revision = "f72921f36f36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_archetype", sa.Column("vessel_sequence_id", sa.String(), nullable=True)
    )
    op.add_column(
        "prospect_email", sa.Column("vessel_sequence_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect_email", "vessel_sequence_id")
    op.drop_column("client_archetype", "vessel_sequence_id")
    # ### end Alembic commands ###
