"""Added vessel_api_cached_responses table

Revision ID: 5caaaa9c5cff
Revises: 9ff3910b9f48
Create Date: 2023-03-12 18:45:04.002638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caaaa9c5cff'
down_revision = '9ff3910b9f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_api_cached_responses',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_access_token', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('sequence_id', sa.String(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_api_cached_responses')
    # ### end Alembic commands ###
