"""Added cookies field in the DB

Revision ID: 5d5142d9ae9a
Revises: c19658cb4cf4
Create Date: 2023-03-22 12:53:06.351961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5142d9ae9a'
down_revision = 'c19658cb4cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('li_cookies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'li_cookies')
    # ### end Alembic commands ###
