"""Added labels and tone to bump_framework_templates

Revision ID: 5e001a47d779
Revises: a086b91b2bc1
Create Date: 2023-10-23 14:23:47.694732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e001a47d779"
down_revision = "a086b91b2bc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bump_framework_templates",
        sa.Column("labels", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "bump_framework_templates", sa.Column("tone", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bump_framework_templates", "tone")
    op.drop_column("bump_framework_templates", "labels")
    # ### end Alembic commands ###
