"""Add last_reply_time onto Prospect Email

Revision ID: 5e6baac18a86
Revises: 4a4e12c3d40c
Create Date: 2023-12-06 10:08:54.971130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e6baac18a86"
down_revision = "4a4e12c3d40c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect_email", sa.Column("last_reply_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect_email", "last_reply_time")
    # ### end Alembic commands ###
