"""Added active column to stack_ranked_message_generation_configuration

Revision ID: 601320b93d78
Revises: bd032c2696a2
Create Date: 2023-02-09 16:18:54.200923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "601320b93d78"
down_revision = "bd032c2696a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("active", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stack_ranked_message_generation_configuration", "active")
    # ### end Alembic commands ###
