"""empty message

Revision ID: 6067fd01c3dd
Revises: ff56be6da497
Create Date: 2023-04-18 21:28:27.841752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6067fd01c3dd'
down_revision = 'ff56be6da497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linkedin_conversation_entry_thread_urn_id', table_name='linkedin_conversation_entry')
    op.create_index(op.f('ix_linkedin_conversation_entry_thread_urn_id'), 'linkedin_conversation_entry', ['thread_urn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_conversation_entry_thread_urn_id'), table_name='linkedin_conversation_entry')
    op.create_index('ix_linkedin_conversation_entry_thread_urn_id', 'linkedin_conversation_entry', ['thread_urn_id'], unique=False)
    # ### end Alembic commands ###
