"""empty message

Revision ID: 608abe9a1293
Revises: faa7da6b6210
Create Date: 2023-04-17 20:05:07.072034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608abe9a1293'
down_revision = 'faa7da6b6210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'vessel_sequence_id')
    op.drop_column('prospect_email', 'vessel_sequence_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email', sa.Column('vessel_sequence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client_archetype', sa.Column('vessel_sequence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
