""" Remove prospect_id from iscraper_payload_cache

Revision ID: 6107ed195d81
Revises: afecc7fa2015
Create Date: 2023-02-24 16:25:34.235477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6107ed195d81'
down_revision = 'afecc7fa2015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('iscraper_payload_cache_prospect_id_fkey', 'iscraper_payload_cache', type_='foreignkey')
    op.drop_column('iscraper_payload_cache', 'prospect_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iscraper_payload_cache', sa.Column('prospect_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('iscraper_payload_cache_prospect_id_fkey', 'iscraper_payload_cache', 'prospect', ['prospect_id'], ['id'])
    # ### end Alembic commands ###
