"""empty message

Revision ID: 614d5711dfa9
Revises: 185785396819
Create Date: 2022-11-02 18:25:20.490907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "614d5711dfa9"
down_revision = "185785396819"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    generatedmessagetype = postgresql.ENUM(
        "LINKEDIN",
        "EMAIL",
        name="generatedmessagetype",
    )
    generatedmessagetype.create(op.get_bind())
    op.add_column(
        "generated_message",
        sa.Column(
            "message_type",
            postgresql.ENUM("LINKEDIN", "EMAIL", name="generatedmessagetype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_message", "message_type")
    # ### end Alembic commands ###
