"""total_sent_count and previous_total_sent_count nullable

Revision ID: 618cb6b24fca
Revises: c8ac0083d73a
Create Date: 2023-11-30 17:25:25.052252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "618cb6b24fca"
down_revision = "c8ac0083d73a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "warmup_snapshot", "total_sent_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "warmup_snapshot",
        "previous_total_sent_count",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "warmup_snapshot",
        "previous_total_sent_count",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "warmup_snapshot",
        "total_sent_count",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
