"""Added slack_user_id to client_sdr

Revision ID: 620b94fc9d7b
Revises: 27d1778a372a
Create Date: 2023-12-29 11:42:02.830725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "620b94fc9d7b"
down_revision = "27d1778a372a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client_sdr", sa.Column("slack_user_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "slack_user_id")
    # ### end Alembic commands ###
