"""Add asset_type and asset_tags to client_archetype_assets

Revision ID: 62c382110a13
Revises: 6fe2b0db1332
Create Date: 2024-02-15 12:53:38.922206

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62c382110a13"
down_revision = "6fe2b0db1332"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    clientarchetypeassettype = sa.Enum(
        "PDF", "TEXT", "URL", name="clientarchetypeassettype"
    )
    clientarchetypeassettype.create(op.get_bind())

    op.add_column(
        "client_archetype_assets",
        sa.Column(
            "asset_type",
            sa.Enum("PDF", "TEXT", "URL", name="clientarchetypeassettype"),
            nullable=True,
        ),
    )
    op.add_column(
        "client_archetype_assets",
        sa.Column("asset_tags", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_archetype_assets", "asset_tags")
    op.drop_column("client_archetype_assets", "asset_type")
    # ### end Alembic commands ###
