"""Added automatically_added_timezone to client_sdr and blocks to trigger

Revision ID: 63870d807951
Revises: 56a1c76dda95
Create Date: 2023-12-27 16:49:31.330303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63870d807951"
down_revision = "56a1c76dda95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sdr",
        sa.Column("automatically_added_timezone", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "automatically_added_timezone")
    # ### end Alembic commands ###
