"""Added upload_id to individual

Revision ID: 639f5fc3ca75
Revises: 70213754c38a
Create Date: 2023-11-13 15:31:02.429076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639f5fc3ca75'
down_revision = '70213754c38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'individual', 'individuals_upload', ['upload_id'], ['id'])
    op.add_column('individuals_upload', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('individuals_upload', sa.Column('client_archetype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'individuals_upload', 'client_archetype', ['client_archetype_id'], ['id'])
    op.create_foreign_key(None, 'individuals_upload', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'individuals_upload', type_='foreignkey')
    op.drop_constraint(None, 'individuals_upload', type_='foreignkey')
    op.drop_column('individuals_upload', 'client_archetype_id')
    op.drop_column('individuals_upload', 'client_id')
    op.drop_constraint(None, 'individual', type_='foreignkey')
    op.drop_column('individual', 'upload_id')
    # ### end Alembic commands ###
