"""Added AI Researcher Answer table

Revision ID: 63e2329969b8
Revises: 8ce4df0e103f
Create Date: 2024-05-20 12:19:59.904302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e2329969b8'
down_revision = '8ce4df0e103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_researcher_answer',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_yes_response', sa.Boolean(), nullable=False),
    sa.Column('short_summary', sa.String(), nullable=False),
    sa.Column('raw_response', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['ai_researcher_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_researcher_answer')
    # ### end Alembic commands ###
