"""Added parent segment and blocks

Revision ID: 667474cfa1ce
Revises: 8684c6b44000
Create Date: 2024-01-16 12:44:16.241851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "667474cfa1ce"
down_revision = "8684c6b44000"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segment", sa.Column("parent_segment_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "segment", "segment", ["parent_segment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "segment", type_="foreignkey")
    op.drop_column("segment", "parent_segment_id")
    # ### end Alembic commands ###
