"""empty message

Revision ID: 67b82f8d92ae
Revises: c484139c5303
Create Date: 2022-12-04 16:22:20.803802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b82f8d92ae'
down_revision = 'c484139c5303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_configuration',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('li_first_follow_up', sa.String(), nullable=True),
    sa.Column('li_second_follow_up', sa.String(), nullable=True),
    sa.Column('li_third_follow_up', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['client_archetype.id'], ),
    sa.PrimaryKeyConstraint('archetype_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_configuration')
    # ### end Alembic commands ###
