"""empty message

Revision ID: 68ec1a54b4d1
Revises: 7e4ee584d203
Create Date: 2023-01-29 18:14:06.380591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ec1a54b4d1'
down_revision = '7e4ee584d203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('seat_expansion_opportunity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'seat_expansion_opportunity')
    # ### end Alembic commands ###
