"""Added transformer blocklist to bump framework template

Revision ID: 68f1d4cf527d
Revises: 3e2c210ca30a
Create Date: 2023-10-17 20:47:05.940962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68f1d4cf527d"
down_revision = "3e2c210ca30a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bump_framework_templates",
        sa.Column(
            "transformer_blocklist",
            sa.ARRAY(
                sa.Enum(
                    "CURRENT_JOB_DESCRIPTION",
                    "CURRENT_JOB_SPECIALTIES",
                    "CURRENT_JOB_INDUSTRY",
                    "CURRENT_EXPERIENCE_DESCRIPTION",
                    "LINKEDIN_BIO_SUMMARY",
                    "YEARS_OF_EXPERIENCE",
                    "YEARS_OF_EXPERIENCE_AT_CURRENT_JOB",
                    "LIST_OF_PAST_JOBS",
                    "RECENT_PATENTS",
                    "RECENT_RECOMMENDATIONS",
                    "GENERAL_WEBSITE_TRANSFORMER",
                    "COMMON_EDUCATION",
                    "SERP_NEWS_SUMMARY",
                    "SERP_NEWS_SUMMARY_NEGATIVE",
                    "CUSTOM",
                    name="researchpointtype",
                )
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bump_framework_templates", "transformer_blocklist")
    # ### end Alembic commands ###
