"""Added deanonymized_contact table

Revision ID: 6a4353a1512c
Revises: 3b6467197679
Create Date: 2024-06-26 12:57:32.870725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4353a1512c'
down_revision = '3b6467197679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deanonymized_contact',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('visited_date', sa.DateTime(), nullable=False),
    sa.Column('linkedin', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('track_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_event_id'], ['track_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deanonymized_contact')
    # ### end Alembic commands ###
