"""Made the urn_id an index in linkedin_conversation_entry

Revision ID: 6a7b093ccb34
Revises: b79dcba4b5bd
Create Date: 2023-03-29 11:28:24.111501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7b093ccb34'
down_revision = 'b79dcba4b5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('linkedin_conversation_entry_urn_id_key', 'linkedin_conversation_entry', type_='unique')
    op.create_index(op.f('ix_linkedin_conversation_entry_urn_id'), 'linkedin_conversation_entry', ['urn_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_conversation_entry_urn_id'), table_name='linkedin_conversation_entry')
    op.create_unique_constraint('linkedin_conversation_entry_urn_id_key', 'linkedin_conversation_entry', ['urn_id'])
    # ### end Alembic commands ###
