"""empty message

Revision ID: 6b82615378fa
Revises: 3811358fe1e7
Create Date: 2022-10-26 12:13:02.359303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b82615378fa'
down_revision = '3811358fe1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('weekly_li_outbound_target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'weekly_li_outbound_target')
    # ### end Alembic commands ###
