"""Add last_message to ProspectEmail

Revision ID: 6c008981ec31
Revises: b1d64b325625
Create Date: 2023-12-19 14:58:13.747502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c008981ec31"
down_revision = "b1d64b325625"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect_email", sa.Column("last_message", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect_email", "last_message")
    # ### end Alembic commands ###
