"""empty message

Revision ID: 74456f223c06
Revises: 
Create Date: 2022-08-13 22:00:14.958674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74456f223c06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('echo',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('echo')
    # ### end Alembic commands ###
