"""Added rewind_img column to selix_session_task

Revision ID: 74e3eac47eed
Revises: 5115e7613ffe
Create Date: 2024-08-22 12:19:20.698130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e3eac47eed'
down_revision = '5115e7613ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selix_session_task', sa.Column('rewind_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selix_session_task', 'rewind_img')
    # ### end Alembic commands ###
