"""empty message

Revision ID: 75e9aaa0f9bd
Revises: 341f8a899aee
Create Date: 2022-10-21 14:33:49.034504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "75e9aaa0f9bd"
down_revision = "341f8a899aee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    phantombustertype = postgresql.ENUM(
        "INBOX_SCRAPER",
        "OUTBOUND_ENGINE",
        name="phantombustertype",
    )
    phantombustertype.create(op.get_bind())

    op.add_column(
        "phantom_buster_config",
        sa.Column(
            "pb_type",
            postgresql.ENUM(
                "INBOX_SCRAPER",
                "OUTBOUND_ENGINE",
                name="phantombustertype",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phantom_buster_config", "pb_type")
    # ### end Alembic commands ###
