"""empty message

Revision ID: 76c00f799e79
Revises: c4668beb85c8
Create Date: 2024-07-11 13:55:06.275340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c00f799e79'
down_revision = 'c4668beb85c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_contact', sa.Column('crm_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_contact', 'crm_id')
    # ### end Alembic commands ###
