"""Add SlackNotificationClassLogger

Revision ID: 76f8bf1e04ad
Revises: e89842acea95
Create Date: 2024-02-15 09:56:00.062458

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "76f8bf1e04ad"
down_revision = "e89842acea95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_notification_class_logger",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "LINKEDIN_INVITE_ACCEPTED",
                "LINKEDIN_PROSPECT_RESPONDED",
                "LINKEDIN_PROSPECT_SCHEDULING",
                "LINKEDIN_PROSPECT_REMOVED",
                "LINKEDIN_DEMO_SET",
                "AI_REPLY_TO_EMAIL",
                "EMAIL_LINK_CLICKED",
                "EMAIL_PROSPECT_REPLIED",
                "EMAIL_MULTICHANNELED",
                "DEMO_FEEDBACK_COLLECTED",
                "DEMO_FEEDBACK_UPDATED",
                "AI_TASK_COMPLETED",
                name="slacknotificationtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slack_notification_class_logger")
    # ### end Alembic commands ###
