""" Add client_sdr_id to client_archetype

Revision ID: 79304a8117c1
Revises: 9c9ef309692b
Create Date: 2022-12-12 17:45:07.138429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79304a8117c1'
down_revision = '9c9ef309692b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('client_sdr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_archetype', 'client_sdr', ['client_sdr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_archetype', type_='foreignkey')
    op.drop_column('client_archetype', 'client_sdr_id')
    # ### end Alembic commands ###
