"""Added onboarding for sdrs

Revision ID: 7b62bd31c151
Revises: cc8e97582ae0
Create Date: 2023-05-22 14:51:41.491219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b62bd31c151'
down_revision = 'cc8e97582ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('public_title', sa.String(), nullable=True))
    op.add_column('client_sdr', sa.Column('onboarded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'onboarded')
    op.drop_column('client_sdr', 'public_title')
    # ### end Alembic commands ###
