"""Added assets mapping table

Revision ID: 7c06b77e1f9c
Revises: af1d5045e06f
Create Date: 2024-03-08 17:18:48.011595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c06b77e1f9c'
down_revision = 'af1d5045e06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bump_framework_to_asset_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bump_framework_id', sa.Integer(), nullable=False),
    sa.Column('client_assets_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bump_framework_id'], ['bump_framework.id'], ),
    sa.ForeignKeyConstraint(['client_assets_id'], ['client_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bump_framework_to_asset_mapping')
    # ### end Alembic commands ###
