"""add prospect_id to track_event

Revision ID: 7c3ef3ad6e29
Revises: 0feaa16000cb
Create Date: 2024-07-24 13:46:23.279322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3ef3ad6e29'
down_revision = '0feaa16000cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_event', sa.Column('prospect_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'track_event', 'prospect', ['prospect_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track_event', type_='foreignkey')
    op.drop_column('track_event', 'prospect_id')
    # ### end Alembic commands ###
