"""Add times_bumped to Prospect Email

Revision ID: 7c3ec51152c5
Revises: fef5e4848ce9
Create Date: 2023-08-22 15:32:33.168753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3ec51152c5'
down_revision = 'fef5e4848ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email', sa.Column('times_bumped', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect_email', 'times_bumped')
    # ### end Alembic commands ###
