"""Added prospect_id to samples

Revision ID: 7d581e435a3e
Revises: a179ababa0a5
Create Date: 2023-06-14 18:21:08.979018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d581e435a3e'
down_revision = 'a179ababa0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_builder_samples', sa.Column('prospect_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'voice_builder_samples', 'prospect', ['prospect_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_builder_samples', type_='foreignkey')
    op.drop_column('voice_builder_samples', 'prospect_id')
    # ### end Alembic commands ###
