"""Added inject calendar

Revision ID: 7ddfc813a9a4
Revises: e61646aac55e
Create Date: 2024-01-10 15:27:25.575500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddfc813a9a4'
down_revision = 'e61646aac55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bump_framework', sa.Column('inject_calendar_times', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bump_framework', 'inject_calendar_times')
    # ### end Alembic commands ###
