""" Add pb_csv_count to generated_message

Revision ID: 7ea6b81a0612
Revises: 7340cb4bf4f2
Create Date: 2023-04-25 11:48:48.291154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea6b81a0612'
down_revision = '7340cb4bf4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('pb_csv_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_message', 'pb_csv_count')
    # ### end Alembic commands ###
