"""Add initial message data into LIConvoEntry

Revision ID: 801b4615bbed
Revises: 383dbcabcd84
Create Date: 2023-07-24 12:55:18.040836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801b4615bbed'
down_revision = '383dbcabcd84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_conversation_entry', sa.Column('initial_message_id', sa.Integer(), nullable=True))
    op.add_column('linkedin_conversation_entry', sa.Column('initial_message_cta_id', sa.Integer(), nullable=True))
    op.add_column('linkedin_conversation_entry', sa.Column('initial_message_cta_text', sa.String(), nullable=True))
    op.add_column('linkedin_conversation_entry', sa.Column('initial_message_research_points', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('linkedin_conversation_entry', sa.Column('initial_message_stack_ranked_config_id', sa.Integer(), nullable=True))
    op.add_column('linkedin_conversation_entry', sa.Column('initial_message_stack_ranked_config_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'linkedin_conversation_entry', 'generated_message_cta', ['initial_message_cta_id'], ['id'])
    op.create_foreign_key(None, 'linkedin_conversation_entry', 'generated_message', ['initial_message_id'], ['id'])
    op.create_foreign_key(None, 'linkedin_conversation_entry', 'stack_ranked_message_generation_configuration', ['initial_message_stack_ranked_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'linkedin_conversation_entry', type_='foreignkey')
    op.drop_constraint(None, 'linkedin_conversation_entry', type_='foreignkey')
    op.drop_constraint(None, 'linkedin_conversation_entry', type_='foreignkey')
    op.drop_column('linkedin_conversation_entry', 'initial_message_stack_ranked_config_name')
    op.drop_column('linkedin_conversation_entry', 'initial_message_stack_ranked_config_id')
    op.drop_column('linkedin_conversation_entry', 'initial_message_research_points')
    op.drop_column('linkedin_conversation_entry', 'initial_message_cta_text')
    op.drop_column('linkedin_conversation_entry', 'initial_message_cta_id')
    op.drop_column('linkedin_conversation_entry', 'initial_message_id')
    # ### end Alembic commands ###
