"""Added task type and data to operator dashboard entry

Revision ID: 808ac38c3df6
Revises: 7cfa5577b4b9
Create Date: 2024-01-23 10:14:07.235353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "808ac38c3df6"
down_revision = "7cfa5577b4b9"
branch_labels = None
depends_on = None


def upgrade():
    task_type = sa.Enum(
        "LINKEDIN_DISCONNECTED",
        "EMAIL_CAMPAIGN_REVIEW",
        "LINKEDIN_CAMPAIGN_REVIEW",
        "DEMO_FEEDBACK_NEEDED",
        "SCHEDULING_NEEDED",
        name="operatordashboardtasktype",
    )
    task_type.create(op.get_bind())

    op.add_column(
        "operator_dashboard_entry",
        sa.Column(
            "task_type",
            sa.Enum(
                "LINKEDIN_DISCONNECTED",
                "EMAIL_CAMPAIGN_REVIEW",
                "LINKEDIN_CAMPAIGN_REVIEW",
                "DEMO_FEEDBACK_NEEDED",
                "SCHEDULING_NEEDED",
                name="operatordashboardtasktype",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "operator_dashboard_entry", sa.Column("task_data", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operator_dashboard_entry", "task_data")
    op.drop_column("operator_dashboard_entry", "task_type")
    # ### end Alembic commands ###
