"""Added individual id to sdr

Revision ID: 818638d933ca
Revises: 59ddc813dbc9
Create Date: 2024-04-01 16:00:32.239782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818638d933ca'
down_revision = '59ddc813dbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('individual_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_sdr', 'individual', ['individual_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_sdr', type_='foreignkey')
    op.drop_column('client_sdr', 'individual_id')
    # ### end Alembic commands ###
