"""Changed reported tiem in hours to float

Revision ID: 81e2f10b7ad7
Revises: 49ec56201a17
Create Date: 2023-01-11 15:32:11.037236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81e2f10b7ad7"
down_revision = "49ec56201a17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbound_campaign",
        sa.Column("reported_time_in_hours", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbound_campaign", "reported_time_in_hours")
    # ### end Alembic commands ###
