"""empty message

Revision ID: 82071d29d971
Revises: 0000c2f26cd7
Create Date: 2024-06-27 11:00:19.785339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82071d29d971'
down_revision = '0000c2f26cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_archetype_ai_voice_id_fkey', 'client_archetype', type_='foreignkey')
    op.drop_column('client_archetype', 'ai_voice_id')
    op.drop_constraint('few_shot_ai_voice_id_fkey', 'few_shot', type_='foreignkey')
    op.drop_column('few_shot', 'ai_voice_id')
    op.drop_table('ai_voice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('few_shot', sa.Column('ai_voice_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('few_shot_ai_voice_id_fkey', 'few_shot', 'ai_voice', ['ai_voice_id'], ['id'])
    op.add_column('client_archetype', sa.Column('ai_voice_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_archetype_ai_voice_id_fkey', 'client_archetype', 'ai_voice', ['ai_voice_id'], ['id'])
    op.create_table('ai_voice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_sdr_created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='ai_voice_client_id_fkey'),
    sa.ForeignKeyConstraint(['client_sdr_created_by'], ['client_sdr.id'], name='ai_voice_client_sdr_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_voice_pkey')
    )
    # ### end Alembic commands ###
