"""Add linkedin_warmup_status column AND table

Revision ID: 82694f2ef483
Revises: 0395830de173
Create Date: 2023-09-05 10:48:59.758186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82694f2ef483'
down_revision = '0395830de173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_warmup_status_change',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Enum('WARM_UP_5', 'WARM_UP_25', 'WARM_UP_50', 'WARM_UP_75', 'WARM_UP_90', 'CUSTOM_WARM_UP', name='linkedinwarmupstatus'), nullable=True),
    sa.Column('old_sla_value', sa.Integer(), nullable=True),
    sa.Column('new_status', sa.Enum('WARM_UP_5', 'WARM_UP_25', 'WARM_UP_50', 'WARM_UP_75', 'WARM_UP_90', 'CUSTOM_WARM_UP', name='linkedinwarmupstatus'), nullable=False),
    sa.Column('new_sla_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client_sdr', sa.Column('linkedin_warmup_status', sa.Enum('WARM_UP_5', 'WARM_UP_25', 'WARM_UP_50', 'WARM_UP_75', 'WARM_UP_90', 'CUSTOM_WARM_UP', name='linkedinwarmupstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'linkedin_warmup_status')
    op.drop_table('warmup_status_change')
    # ### end Alembic commands ###
