"""Added do_not_contact_people_names and do_not_contact_emails columns

Revision ID: 85fcc3af3a18
Revises: 41530d7728d3
Create Date: 2024-02-07 09:39:03.880069

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85fcc3af3a18"
down_revision = "41530d7728d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column("do_not_contact_people_names", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "client",
        sa.Column("do_not_contact_emails", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "client_sdr",
        sa.Column("do_not_contact_people_names", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "client_sdr",
        sa.Column("do_not_contact_emails", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "do_not_contact_emails")
    op.drop_column("client_sdr", "do_not_contact_people_names")
    op.drop_column("client", "do_not_contact_emails")
    op.drop_column("client", "do_not_contact_people_names")
    # ### end Alembic commands ###
