"""Added email validation

Revision ID: 8684c6b44000
Revises: 7dcdbcbab4da
Create Date: 2024-01-16 12:10:50.162121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8684c6b44000'
down_revision = '7dcdbcbab4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('valid_primary_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'valid_primary_email')
    # ### end Alembic commands ###
