"""Added autopilot_enabled to client_sdr

Revision ID: 87325abf54cf
Revises: 200820e2ecc8
Create Date: 2023-03-01 09:27:31.602482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87325abf54cf"
down_revision = "200820e2ecc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sdr", sa.Column("autopilot_enabled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sdr", "autopilot_enabled")
    # ### end Alembic commands ###
