"""Added prompts and completions to ranked message generation configuration

Revision ID: 89e80ca71ff7
Revises: e5012f40896d
Create Date: 2023-07-11 11:37:50.553751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89e80ca71ff7"
down_revision = "e5012f40896d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_1", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_1", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_2", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_2", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_3", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_3", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_4", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_4", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_5", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_5", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_6", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_6", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("prompt_7", sa.String(), nullable=True),
    )
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("completion_7", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stack_ranked_message_generation_configuration", "completion_7")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_7")
    op.drop_column("stack_ranked_message_generation_configuration", "completion_6")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_6")
    op.drop_column("stack_ranked_message_generation_configuration", "completion_5")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_5")
    op.drop_column("stack_ranked_message_generation_configuration", "completion_4")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_4")
    op.drop_column("stack_ranked_message_generation_configuration", "completion_3")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_3")
    op.drop_column("stack_ranked_message_generation_configuration", "completion_2")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_2")
    op.drop_column("stack_ranked_message_generation_configuration", "completion_1")
    op.drop_column("stack_ranked_message_generation_configuration", "prompt_1")
    # ### end Alembic commands ###
