"""Added plg_product_leads table

Revision ID: 8b5cc3659753
Revises: 32bb8996565d
Create Date: 2023-07-31 16:52:55.598209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b5cc3659753"
down_revision = "32bb8996565d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plg_product_leads",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("user_linkedin_url", sa.String(), nullable=True),
        sa.Column("prospect_linkedin_url", sa.String(), nullable=True),
        sa.Column("blocks", sa.JSON(), nullable=True),
        sa.Column("is_test", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plg_product_leads")
    # ### end Alembic commands ###
