"""Change bytea type to a jsonb type

Revision ID: 8bad6a70da12
Revises: d060da6d3dbd
Create Date: 2023-01-23 14:46:31.555311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bad6a70da12'
down_revision = 'd060da6d3dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_uploads_raw_csv', sa.Column('csv_data_hash', sa.String(), nullable=False))
    op.drop_column('prospect_uploads_raw_csv', 'prospect_uploads_raw_csv')
    op.drop_column('prospect_uploads_raw_csv', 'prospect_upload_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_uploads_raw_csv', sa.Column('prospect_upload_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('prospect_uploads_raw_csv', sa.Column('prospect_uploads_raw_csv', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('prospect_uploads_raw_csv', 'csv_data_hash')
    # ### end Alembic commands ###
