""" Add nylas_active to client_sdr

Revision ID: 8c3c946761b1
Revises: d4f8155936f4
Create Date: 2023-03-30 15:33:27.712858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3c946761b1'
down_revision = 'd4f8155936f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('nylas_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'nylas_active')
    # ### end Alembic commands ###
