"""Added ai_researcher_id to client_archetype

Revision ID: 8ce4df0e103f
Revises: 25ca6a8444f7
Create Date: 2024-05-20 12:13:20.277411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce4df0e103f'
down_revision = '25ca6a8444f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('ai_researcher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_archetype', 'ai_researcher', ['ai_researcher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_archetype', type_='foreignkey')
    op.drop_column('client_archetype', 'ai_researcher_id')
    # ### end Alembic commands ###
