"""EmailMessage takes Nylas data

Revision ID: 8d4e334b8320
Revises: 4b63bd246295
Create Date: 2023-05-04 11:30:56.147468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d4e334b8320'
down_revision = '4b63bd246295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_conversation_message', sa.Column('body', sa.String(), nullable=False))
    op.add_column('email_conversation_message', sa.Column('bcc', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_message', sa.Column('cc', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_message', sa.Column('date_received', sa.DateTime(), nullable=False))
    op.add_column('email_conversation_message', sa.Column('files', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_message', sa.Column('message_from', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_message', sa.Column('message_to', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_message', sa.Column('reply_to', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('email_conversation_message', sa.Column('nylas_data_raw', sa.JSON(), nullable=False))
    op.drop_column('email_conversation_message', 'nylas_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_conversation_message', sa.Column('nylas_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('email_conversation_message', 'nylas_data_raw')
    op.drop_column('email_conversation_message', 'reply_to')
    op.drop_column('email_conversation_message', 'message_to')
    op.drop_column('email_conversation_message', 'message_from')
    op.drop_column('email_conversation_message', 'files')
    op.drop_column('email_conversation_message', 'date_received')
    op.drop_column('email_conversation_message', 'cc')
    op.drop_column('email_conversation_message', 'bcc')
    op.drop_column('email_conversation_message', 'body')
    # ### end Alembic commands ###
