"""Add nylas IDs into the EmailMessageSchedule

Revision ID: 8da7d9beb704
Revises: cbcedb29763a
Create Date: 2023-10-12 10:28:12.006521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da7d9beb704'
down_revision = 'cbcedb29763a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messaging_schedule', sa.Column('nylas_message_id', sa.String(), nullable=True))
    op.add_column('email_messaging_schedule', sa.Column('nylas_thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messaging_schedule', 'nylas_thread_id')
    op.drop_column('email_messaging_schedule', 'nylas_message_id')
    # ### end Alembic commands ###
