"""Added notification type and blocks

Revision ID: 8dcdac4d5202
Revises: f71c0c300bb0
Create Date: 2024-01-03 15:56:00.779883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8dcdac4d5202"
down_revision = "f71c0c300bb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # create notification_type enum
    op.execute(
        "CREATE TYPE operatornotificationtype AS ENUM ('REVIEW_NEW_CAMPAIGN', 'DEMO_FEEDBACK_NEEDED', 'SCHEDULE_MEETING')"
    )

    op.add_column(
        "operator_notification",
        sa.Column(
            "notification_type",
            sa.Enum(
                "REVIEW_NEW_CAMPAIGN",
                "DEMO_FEEDBACK_NEEDED",
                "SCHEDULE_MEETING",
                name="operatornotificationtype",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operator_notification", "notification_type")
    # ### end Alembic commands ###
