""" Add outbound_enabled columns to client for email and linkedin.
This is used for onboarding purposes.

Revision ID: 8e29bba080a0
Revises: 5acc5ef294f3
Create Date: 2022-12-12 10:17:10.033942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e29bba080a0'
down_revision = '5acc5ef294f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('linkedin_outbound_enabled', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('email_outbound_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'email_outbound_enabled')
    op.drop_column('client', 'linkedin_outbound_enabled')
    # ### end Alembic commands ###
