""" Create SightOnboarding table.

Revision ID: 8e94b0f44ce5
Revises: 8e29bba080a0
Create Date: 2022-12-12 12:39:31.427138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e94b0f44ce5'
down_revision = '8e29bba080a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sight_onboarding',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=False),
    sa.Column('is_onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('completed_credentials', sa.Boolean(), nullable=True),
    sa.Column('completed_first_persona', sa.Boolean(), nullable=True),
    sa.Column('completed_ai_behavior', sa.Boolean(), nullable=True),
    sa.Column('completed_first_campaign', sa.Boolean(), nullable=True),
    sa.Column('completed_go_live', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sight_onboarding')
    # ### end Alembic commands ###
