"""Added activity_date column to retention_activity_logs

Revision ID: 907744af903e
Revises: 81b8f754e9ff
Create Date: 2024-08-30 21:40:05.804110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907744af903e'
down_revision = '81b8f754e9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retention_activity_logs', sa.Column('activity_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retention_activity_logs', 'activity_date')
    # ### end Alembic commands ###
