"""Added img_expire to linkedin_conversation_entry

Revision ID: 91ba89e68f6d
Revises: 294817995026
Create Date: 2023-04-06 13:37:26.047183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ba89e68f6d'
down_revision = '294817995026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_conversation_entry', sa.Column('img_expire', sa.Numeric(precision=20, scale=0), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_conversation_entry', 'img_expire')
    # ### end Alembic commands ###
