"""Added auto archive field

Revision ID: 92d48ebbfbc1
Revises: 73ac00be725d
Create Date: 2024-01-08 11:34:28.499275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d48ebbfbc1'
down_revision = '73ac00be725d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('auto_archive_convos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'auto_archive_convos')
    # ### end Alembic commands ###
