"""Add campaign UUID as a column

Revision ID: 93c62a4c179e
Revises: 74746ecb6f7f
Create Date: 2022-12-15 10:22:30.939464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93c62a4c179e"
down_revision = "74746ecb6f7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbound_campaign", sa.Column("uuid", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbound_campaign", "uuid")
    # ### end Alembic commands ###
