"""empty message

Revision ID: 94b2542263ed
Revises: 614d5711dfa9
Create Date: 2022-11-02 19:42:58.463186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "94b2542263ed"
down_revision = "614d5711dfa9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    emailcustomizedfieldtypes = postgresql.ENUM(
        "EMAIL_FIRST_LINE",
        name="emailcustomizedfieldtypes",
    )
    emailcustomizedfieldtypes.create(op.get_bind())
    op.add_column(
        "email_customized_field",
        sa.Column(
            "email_customized_field_type",
            sa.Enum("EMAIL_FIRST_LINE", name="emailcustomizedfieldtypes"),
            nullable=False,
        ),
    )

    op.execute("COMMIT")
    op.execute("ALTER TYPE gnlpmodeltype ADD VALUE 'EMAIL_FIRST_LINE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_customized_field", "email_customized_field_type")
    # ### end Alembic commands ###
