""" Add phantom buster payload table

Revision ID: 9577826b30f6
Revises: 598e15245979
Create Date: 2023-04-28 09:44:12.907682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9577826b30f6'
down_revision = '598e15245979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phantom_buster_payload',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=True),
    sa.Column('pb_payload', sa.JSON(), nullable=True),
    sa.Column('pb_type', sa.Enum('INBOX_SCRAPER', 'OUTBOUND_ENGINE', name='phantombustertype'), nullable=True),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('email_conversation_message', 'from_sdr',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('email_conversation_message', 'email_conversation_thread_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_conversation_message', 'email_conversation_thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_conversation_message', 'from_sdr',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('phantom_buster_payload')
    # ### end Alembic commands ###
