"""empty message

Revision ID: 972f333eb440
Revises: 95794edbe5ee
Create Date: 2022-10-29 16:43:13.227862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972f333eb440'
down_revision = '95794edbe5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('auth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'auth_token')
    # ### end Alembic commands ###
