"""Added upload table

Revision ID: 992b41391ce3
Revises: 9227e1b52d56
Create Date: 2023-10-16 15:02:21.375104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992b41391ce3'
down_revision = '9227e1b52d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individuals_upload',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('upload_size', sa.Integer(), nullable=False),
    sa.Column('payload_data', sa.ARRAY(sa.JSON()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individuals_upload')
    # ### end Alembic commands ###
