"""add sequence generation in progress flags

Revision ID: 9a95fb4bd932
Revises: 406e81fa5ab2
Create Date: 2024-08-02 11:45:12.623427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a95fb4bd932'
down_revision = '406e81fa5ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('li_seq_generation_in_progress', sa.Boolean(), nullable=True))
    op.add_column('client_archetype', sa.Column('email_seq_generation_in_progress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'email_seq_generation_in_progress')
    op.drop_column('client_archetype', 'li_seq_generation_in_progress')
    # ### end Alembic commands ###
