""" Add prospect email status records table and add NOT_INTERESTED status

Revision ID: 9aa781bff104
Revises: ffb924852640
Create Date: 2023-01-17 17:10:02.174156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9aa781bff104'
down_revision = 'ffb924852640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE prospectemailoutreachstatus ADD VALUE 'NOT_INTERESTED'")
    op.create_table('prospect_email_status_records',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_email_id', sa.Integer(), nullable=True),
    sa.Column('from_status', postgresql.ENUM('UNKNOWN', 'NOT_SENT', 'SENT_OUTREACH', 'EMAIL_OPENED', 'ACCEPTED', 'ACTIVE_CONVO', 'SCHEDULING', 'DEMO_SET', 'DEMO_WON', 'DEMO_LOST', 'NOT_INTERESTED', name='prospectemailoutreachstatus', create_type=False), nullable=False),
    sa.Column('to_status', postgresql.ENUM('UNKNOWN', 'NOT_SENT', 'SENT_OUTREACH', 'EMAIL_OPENED', 'ACCEPTED', 'ACTIVE_CONVO', 'SCHEDULING', 'DEMO_SET', 'DEMO_WON', 'DEMO_LOST', 'NOT_INTERESTED', name='prospectemailoutreachstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['prospect_email_id'], ['prospect_email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE prospectemailoutreachstatus RENAME TO status_old")
    op.execute("CREATE TYPE prospectemailoutreachstatus AS ENUM('UNKNOWN', 'NOT_SENT', 'SENT_OUTREACH', 'EMAIL_OPENED', 'ACCEPTED', 'ACTIVE_CONVO', 'SCHEDULING', 'DEMO_SET', 'DEMO_WON', 'DEMO_LOST')")
    op.execute((
        "ALTER TABLE prospect_email ALTER COLUMN outreach_status TYPE prospectemailoutreachstatus USING "
        "outreach_status::text::prospectemailoutreachstatus"
    ))
    op.execute("DROP TYPE status_old")
    op.drop_table('prospect_email_status_records')
    # ### end Alembic commands ###
