"""Added bump framework details

Revision ID: 9ae7af5c4169
Revises: 3270144660f6
Create Date: 2023-06-09 14:40:18.505021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae7af5c4169'
down_revision = '3270144660f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message_auto_bump', sa.Column('bump_framework_id', sa.Integer(), nullable=True))
    op.add_column('generated_message_auto_bump', sa.Column('bump_framework_title', sa.String(), nullable=True))
    op.add_column('generated_message_auto_bump', sa.Column('bump_framework_description', sa.String(), nullable=True))
    op.add_column('generated_message_auto_bump', sa.Column('bump_framework_length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='bumplength'), nullable=True))
    op.add_column('generated_message_auto_bump', sa.Column('account_research_points', sa.ARRAY(sa.String()), nullable=True))
    op.create_foreign_key(None, 'generated_message_auto_bump', 'bump_framework', ['bump_framework_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_message_auto_bump', type_='foreignkey')
    op.drop_column('generated_message_auto_bump', 'account_research_points')
    op.drop_column('generated_message_auto_bump', 'bump_framework_length')
    op.drop_column('generated_message_auto_bump', 'bump_framework_description')
    op.drop_column('generated_message_auto_bump', 'bump_framework_title')
    op.drop_column('generated_message_auto_bump', 'bump_framework_id')
    # ### end Alembic commands ###
