"""Add new fields to SDREmailBank

Revision ID: 9c7c5c0af619
Revises: 747ae29e0df0
Create Date: 2023-12-29 17:11:41.217704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c7c5c0af619"
down_revision = "747ae29e0df0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sdr_email_bank", sa.Column("domain_id", sa.Integer(), nullable=True))
    op.add_column(
        "sdr_email_bank", sa.Column("aws_workmail_user_id", sa.String(), nullable=True)
    )
    op.add_column(
        "sdr_email_bank", sa.Column("aws_username", sa.String(), nullable=True)
    )
    op.add_column(
        "sdr_email_bank", sa.Column("aws_password", sa.String(), nullable=True)
    )
    op.add_column(
        "sdr_email_bank", sa.Column("smartlead_account_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "sdr_email_bank", "domain", ["domain_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sdr_email_bank", type_="foreignkey")
    op.drop_column("sdr_email_bank", "smartlead_account_id")
    op.drop_column("sdr_email_bank", "aws_password")
    op.drop_column("sdr_email_bank", "aws_username")
    op.drop_column("sdr_email_bank", "aws_workmail_user_id")
    op.drop_column("sdr_email_bank", "domain_id")
    # ### end Alembic commands ###
