""" Create sight_onboarding table, modify client table.
For self onboarding.

Revision ID: 9c9ef309692b
Revises: 5acc5ef294f3
Create Date: 2022-12-12 17:36:39.752576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9ef309692b'
down_revision = '5acc5ef294f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sight_onboarding',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=False),
    sa.Column('is_onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('completed_credentials', sa.Boolean(), nullable=True),
    sa.Column('completed_first_persona', sa.Boolean(), nullable=True),
    sa.Column('completed_ai_behavior', sa.Boolean(), nullable=True),
    sa.Column('completed_first_campaign', sa.Boolean(), nullable=True),
    sa.Column('completed_go_live', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('linkedin_outbound_enabled', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('email_outbound_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'email_outbound_enabled')
    op.drop_column('client', 'linkedin_outbound_enabled')
    op.drop_table('sight_onboarding')
    # ### end Alembic commands ###
