"""Add ICPScoringJobQueue

Revision ID: 9dac7b767c42
Revises: cdd926b564eb
Create Date: 2023-09-26 14:28:41.827837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dac7b767c42'
down_revision = 'cdd926b564eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_scoring_job_queue',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_archetype_id', sa.Integer(), nullable=False),
    sa.Column('prospect_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_archetype_id'], ['client_archetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icp_scoring_job_queue')
    # ### end Alembic commands ###
