"""Added proof_of_work_img column to selix_session_task

Revision ID: 9dd0d1ff9ab9
Revises: 9a95fb4bd932
Create Date: 2024-08-02 19:13:12.029846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd0d1ff9ab9'
down_revision = '9a95fb4bd932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selix_session_task', sa.Column('proof_of_work_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selix_session_task', 'proof_of_work_img')
    # ### end Alembic commands ###
