"""Add SDR blacklist words

Revision ID: 9e23084a0108
Revises: 487b29ba48eb
Create Date: 2023-08-15 14:46:38.207964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e23084a0108'
down_revision = '487b29ba48eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('blacklisted_words', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'blacklisted_words')
    # ### end Alembic commands ###
