"""empty message

Revision ID: 9e34e68298c0
Revises: 5ba0209e342d
Create Date: 2022-10-12 12:20:21.386061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e34e68298c0'
down_revision = '5ba0209e342d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phantom_buster_config',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_sdr_id', sa.Integer(), nullable=True),
    sa.Column('google_sheets_uuid', sa.String(), nullable=True),
    sa.Column('phantom_name', sa.String(), nullable=True),
    sa.Column('phantom_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phantom_buster_config')
    # ### end Alembic commands ###
