"""Add nullable segment_id column in Research point type

Revision ID: 9e4757c6eff6
Revises: c2113e31b20d
Create Date: 2024-08-21 13:28:17.421812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4757c6eff6'
down_revision = 'c2113e31b20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_point_type', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'research_point_type', 'segment', ['segment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_point_type', type_='foreignkey')
    op.drop_column('research_point_type', 'segment_id')
    # ### end Alembic commands ###
