"""Add LINKEDIN_INVITE_ACCEPTED to SlackNotificationType

Revision ID: 9e4c2e43dfc4
Revises: b3dd4e09f8e8
Create Date: 2024-01-29 12:25:00.275950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e4c2e43dfc4"
down_revision = "b3dd4e09f8e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype ADD VALUE 'LINKEDIN_INVITE_ACCEPTED'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype DROP VALUE 'LINKEDIN_INVITE_ACCEPTED'")

    # ### end Alembic commands ###
