"""added analytics activation and deactivation dates

Revision ID: 9f1e86cddbe5
Revises: bfe5bdf81210
Create Date: 2023-07-03 21:54:09.236434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f1e86cddbe5"
down_revision = "bfe5bdf81210"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("analytics_activation_date", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("analytics_deactivation_date", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("client_sdr", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("analytics_activation_date", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("analytics_deactivation_date", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_sdr", schema=None) as batch_op:
        batch_op.drop_column("analytics_deactivation_date")
        batch_op.drop_column("analytics_activation_date")

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_column("analytics_deactivation_date")
        batch_op.drop_column("analytics_activation_date")

    # ### end Alembic commands ###
