"""Add times_used and times_accepted to EmailSequenceStep

Revision ID: a086b91b2bc1
Revises: d7d38d1f45b7
Create Date: 2023-10-23 13:18:37.373979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a086b91b2bc1'
down_revision = 'd7d38d1f45b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_sequence_step', sa.Column('times_used', sa.Integer(), nullable=False))
    op.add_column('email_sequence_step', sa.Column('times_accepted', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_sequence_step', 'times_accepted')
    op.drop_column('email_sequence_step', 'times_used')
    # ### end Alembic commands ###
