"""empty message

Revision ID: a148a90ff16f
Revises: 91d11cb53ccb
Create Date: 2024-04-30 18:21:16.436283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a148a90ff16f'
down_revision = '91d11cb53ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('autoscrape_enabled', sa.Boolean(), nullable=True))
    op.add_column('segment', sa.Column('current_scrape_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'current_scrape_page')
    op.drop_column('segment', 'autoscrape_enabled')
    # ### end Alembic commands ###
