"""Removed persona description

Revision ID: a179ababa0a5
Revises: 33b8e517687c
Create Date: 2023-06-13 20:29:35.163770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a179ababa0a5'
down_revision = '33b8e517687c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'persona_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('persona_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
