"""Added sequence table

Revision ID: a1d23e5869fd
Revises: 5aaf85ee8fa7
Create Date: 2023-04-10 13:32:10.216254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d23e5869fd'
down_revision = '5aaf85ee8fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=True),
    sa.Column('archetype_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IMPORTED', 'CANCELLED', name='sequencestatus'), nullable=False),
    sa.Column('sales_engagement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['client_archetype.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence')
    # ### end Alembic commands ###
