"""Added account_name to channel_warmup

Revision ID: a41a135b3bd5
Revises: f9e2a7006efe
Create Date: 2023-11-02 12:55:03.047101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a41a135b3bd5"
down_revision = "f9e2a7006efe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel_warmup", sa.Column("account_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_warmup", "account_name")
    # ### end Alembic commands ###
