"""Add last_refreshed to Domain

Revision ID: a453cff36242
Revises: bbdd2f344aab
Create Date: 2024-01-05 11:38:23.351387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a453cff36242"
down_revision = "bbdd2f344aab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("domain", sa.Column("last_refreshed", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain", "last_refreshed")
    # ### end Alembic commands ###
