"""empty message

Revision ID: a45950254fc8
Revises: cde30ed4d32f
Create Date: 2022-10-27 16:10:39.026952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45950254fc8'
down_revision = 'cde30ed4d32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('pipeline_notifications_webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'pipeline_notifications_webhook_url')
    # ### end Alembic commands ###
