"""Add sequence_name to sales_engagement_interaction_raw

Revision ID: a572a9ed25b0
Revises: 2111eb191a4e
Create Date: 2023-02-03 10:08:38.131589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a572a9ed25b0'
down_revision = '2111eb191a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_engagement_interaction_raw', sa.Column('sequence_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_engagement_interaction_raw', 'sequence_name')
    # ### end Alembic commands ###
