"""empty message

Revision ID: a5e03d9cac6f
Revises: 1d19c3a456fd
Create Date: 2024-05-22 15:08:30.299730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e03d9cac6f'
down_revision = '1d19c3a456fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('testing_volume', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'testing_volume')
    # ### end Alembic commands ###
