"""Added client_sync_crm

Revision ID: a7db8b1e3b7d
Revises: 58a21c4b7e80
Create Date: 2024-02-16 17:56:23.788052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7db8b1e3b7d'
down_revision = '58a21c4b7e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_sync_crm',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('status_mapping', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_sync_crm')
    # ### end Alembic commands ###
