"""Add use_account_research to bump_framework

Revision ID: a81be24af31c
Revises: d1db38a7bdf8
Create Date: 2023-07-14 09:59:28.281466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81be24af31c'
down_revision = 'd1db38a7bdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bump_framework', sa.Column('use_account_research', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bump_framework', 'use_account_research')
    # ### end Alembic commands ###
