""" Add nylas_auth_code to client_sdr

Revision ID: a8627d070b7c
Revises: 87650f7d1bf3
Create Date: 2023-03-29 16:28:09.031821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8627d070b7c'
down_revision = '87650f7d1bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('nylas_auth_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'nylas_auth_code')
    # ### end Alembic commands ###
