"""empty message

Revision ID: a95d3536f47d
Revises: f4ead65767c1
Create Date: 2022-11-04 13:36:49.029351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95d3536f47d'
down_revision = 'f4ead65767c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('approved_prospect_email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prospect', 'prospect_email', ['approved_prospect_email_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospect', type_='foreignkey')
    op.drop_column('prospect', 'approved_prospect_email_id')
    # ### end Alembic commands ###
