""" Add persona_contact_objective to client_archetype

Revision ID: aa688f9d5655
Revises: dd6781ad1dec
Create Date: 2023-05-26 10:03:13.796615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa688f9d5655'
down_revision = 'dd6781ad1dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('persona_contact_objective', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'persona_contact_objective')
    # ### end Alembic commands ###
