"""Added field to store last message from prospect

Revision ID: ad2d982c047f
Revises: 3843bfbb60c8
Create Date: 2022-11-29 20:43:06.152702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad2d982c047f"
down_revision = "3843bfbb60c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect",
        sa.Column("li_last_message_from_prospect", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "li_last_message_from_prospect")
    # ### end Alembic commands ###
