"""Added account research point and account research payload

Revision ID: ae031c4bf580
Revises: 5b6685786205
Create Date: 2023-04-20 15:40:45.838217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae031c4bf580"
down_revision = "5b6685786205"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_research_point",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=True),
        sa.Column(
            "account_research_type",
            sa.Enum("GENERIC_RESEARCH", name="accountresearchtype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "bump_framework", "title", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "bump_framework",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "bump_framework", "default", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bump_framework", "default", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "bump_framework",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "bump_framework", "title", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_table("account_research_point")
    # ### end Alembic commands ###
