"""Added li_urn_id column to prospect table

Revision ID: ae37438647e6
Revises: 0622452f2501
Create Date: 2023-03-28 17:03:49.195595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae37438647e6"
down_revision = "31c85cdb232d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prospect", sa.Column("li_urn_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "li_urn_id")
    # ### end Alembic commands ###
