"""empty message

Revision ID: aed90c2b672b
Revises: 59ce094e96e5
Create Date: 2023-02-06 17:26:34.038644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed90c2b672b'
down_revision = '59ce094e96e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_ranked_message_generation_configuration', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stack_ranked_message_generation_configuration', 'priority')
    # ### end Alembic commands ###
