""" Manually fix model. No more client_sdr_id primary key.

Revision ID: afbb4830281e
Revises: 8e94b0f44ce5
Create Date: 2022-12-12 14:13:29.464440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbb4830281e'
down_revision = '8e94b0f44ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sight_onboarding', 'client_sdr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sight_onboarding', 'client_sdr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
