"""Make notification_type in SlackNotification unique

Revision ID: afc6ca2ca1b9
Revises: 5ac2c4b99dd2
Create Date: 2024-01-18 15:28:57.362860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "afc6ca2ca1b9"
down_revision = "5ac2c4b99dd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "slack_notification", ["notification_type"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slack_notification", type_="unique")
    # ### end Alembic commands ###
