"""Added autocorrect columns in generated_message table

Revision ID: b27f5fac657d
Revises: 7209a634e9d0
Create Date: 2023-05-09 11:15:05.801617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b27f5fac657d"
down_revision = "7209a634e9d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_message",
        sa.Column("autocorrect_run_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "generated_message",
        sa.Column("before_autocorrect_problems", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "generated_message",
        sa.Column("before_autocorrect_text", sa.String(), nullable=True),
    )
    op.add_column(
        "generated_message",
        sa.Column("after_autocorrect_text", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_message", "after_autocorrect_text")
    op.drop_column("generated_message", "before_autocorrect_text")
    op.drop_column("generated_message", "before_autocorrect_problems")
    op.drop_column("generated_message", "autocorrect_run_count")
    # ### end Alembic commands ###
