""" Add used_in_past_training to adversary_training_point.
This way we can keep track of which training points have been used in the past training iterations.

Revision ID: b2cbebbdb727
Revises: 16853d25c66e
Create Date: 2022-12-21 10:37:42.888363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cbebbdb727'
down_revision = '16853d25c66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adversary_training_point', sa.Column('used_in_past_training', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adversary_training_point', 'used_in_past_training')
    # ### end Alembic commands ###
