"""Added failed job talbe

Revision ID: b3527d5468e7
Revises: 171d51739888
Create Date: 2024-03-20 16:03:38.564008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3527d5468e7'
down_revision = '171d51739888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_queue_failed_job',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_date', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETE', 'RETRY', 'FAILED', name='processqueuestatus'), nullable=True),
    sa.Column('fail_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_queue_failed_job')
    # ### end Alembic commands ###
