"""Added emoji to client_archetype

Revision ID: b3dbb1397bcc
Revises: 66583d7c710d
Create Date: 2023-08-31 13:13:49.578922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3dbb1397bcc"
down_revision = "66583d7c710d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client_archetype", sa.Column("emoji", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_archetype", "emoji")
    # ### end Alembic commands ###
