"""Add notification_outbound_channel to SlackNotification

Revision ID: b3dd4e09f8e8
Revises: 92c403979a53
Create Date: 2024-01-29 12:14:46.365921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3dd4e09f8e8"
down_revision = "92c403979a53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_notification",
        sa.Column(
            "notification_outbound_channel", sa.String(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_notification", "notification_outbound_channel")
    # ### end Alembic commands ###
