"""Add column to get the count of CTAs and Bumps

Revision ID: b613521284d3
Revises: 35b16decb4c0
Create Date: 2024-07-30 18:43:35.440966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b613521284d3'
down_revision = '35b16decb4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_default_voices', sa.Column('count_ctas', sa.Integer(), nullable=False))
    op.add_column('internal_default_voices', sa.Column('count_bumps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_default_voices', 'count_bumps')
    op.drop_column('internal_default_voices', 'count_ctas')
    # ### end Alembic commands ###
