"""empty message

Revision ID: b772d8df7abc
Revises: 94b2542263ed
Create Date: 2022-11-02 20:37:35.755636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b772d8df7abc'
down_revision = '94b2542263ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('generated_message_email_customized_field_id_fkey', 'generated_message', type_='foreignkey')
    op.drop_column('generated_message', 'email_customized_field_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('email_customized_field_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('generated_message_email_customized_field_id_fkey', 'generated_message', 'email_customized_field', ['email_customized_field_id'], ['id'])
    # ### end Alembic commands ###
