"""Added super_sight_link to client

Revision ID: b782a1cf9eeb
Revises: 2e11a2288366
Create Date: 2023-01-04 17:59:46.911213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b782a1cf9eeb"
down_revision = "2e11a2288366"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("super_sight_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "super_sight_link")
    # ### end Alembic commands ###
