"""Add li_should_deep_scrape to prospect

Revision ID: b7e38d32625b
Revises: 79cebdbb8459
Create Date: 2023-03-08 13:28:33.743796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e38d32625b'
down_revision = '79cebdbb8459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('li_should_deep_scrape', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'li_should_deep_scrape')
    # ### end Alembic commands ###
