"""linkedin_prospect_responded

Revision ID: b89480148456
Revises: d231c62d103f
Create Date: 2024-02-09 01:34:04.201480

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b89480148456"
down_revision = "d231c62d103f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        "ALTER TYPE slacknotificationtype ADD VALUE 'LINKEDIN_PROSPECT_RESPONDED'"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        "ALTER TYPE slacknotificationtype DROP VALUE 'LINKEDIN_PROSPECT_RESPONDED'"
    )

    # ### end Alembic commands ###
