"""Add prospect_upload ID into Prospect

Revision ID: b8a2ad902f2f
Revises: 4c38312bd780
Create Date: 2024-05-20 11:36:22.256416

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8a2ad902f2f"
down_revision = "4c38312bd780"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect", sa.Column("prospect_upload_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "prospect", "prospect_uploads", ["prospect_upload_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prospect", type_="foreignkey")
    op.drop_column("prospect", "prospect_upload_id")
    # ### end Alembic commands ###
