"""Added question enrichment tables

Revision ID: b914a58d6051
Revises: 4b94768b7f23
Create Date: 2023-11-06 12:45:04.677043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b914a58d6051'
down_revision = '4b94768b7f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    questionenrichmentrowstatus = postgresql.ENUM('QUEUED', 'IN_PROGRESS', 'COMPLETE', 'ERROR', name='questionenrichmentrowstatus')
    questionenrichmentrowstatus.create(op.get_bind())

    op.add_column('question_enrichment_row', sa.Column('status', postgresql.ENUM('QUEUED', 'IN_PROGRESS', 'COMPLETE', 'ERROR', name='questionenrichmentrowstatus', create_type=True), nullable=False))
    op.alter_column('question_enrichment_row', 'output',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_enrichment_row', 'output',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('question_enrichment_row', 'status')
    # ### end Alembic commands ###
