"""Added num_results column to saved_apollo_query

Revision ID: bc54fcc7e065
Revises: 81f3b2d53ddf
Create Date: 2024-02-09 12:57:38.922168

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc54fcc7e065"
down_revision = "81f3b2d53ddf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saved_apollo_query", sa.Column("num_results", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("saved_apollo_query", "num_results")
    # ### end Alembic commands ###
