"""empty message

Revision ID: bd557d2930c4
Revises: f5a2b0c5b13f
Create Date: 2022-10-04 18:10:33.818794

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bd557d2930c4"
down_revision = "f5a2b0c5b13f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gnlp_models_fine_tune_jobs",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "INITIATED",
                "UPLOADED_JSONL_FILE",
                "STARTED_FINE_TUNE_JOB",
                "FAILED",
                "COMPLETED",
                name="gnlpfinetunejobstatuses",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("message_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("jsonl_file_id", sa.String(), nullable=True),
        sa.Column("jsonl_file_response", sa.JSON(), nullable=True),
        sa.Column("finetune_job_id", sa.String(), nullable=True),
        sa.Column("finetune_job_response", sa.JSON(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gnlp_models_fine_tune_jobs")
    # ### end Alembic commands ###
