"""empty message

Revision ID: be3d64e4be54
Revises: e4f2dfc457f1
Create Date: 2022-10-11 14:46:38.927748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "be3d64e4be54"
down_revision = "e4f2dfc457f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_archetype",
        sa.Column(
            "transformer_blocklist",
            sa.ARRAY(
                postgresql.ENUM(
                    "EXPERIENCE",
                    "CURRENT_JOB_DESCRIPTION",
                    "CURRENT_JOB_SPECIALTIES",
                    "CURRENT_EXPERIENCE_DESCRIPTION",
                    "YEARS_OF_EXPERIENCE",
                    "YEARS_OF_EXPERIENCE_AT_CURRENT_JOB",
                    "CURRENT_JOB",
                    "LIST_OF_PAST_JOBS",
                    "RECENT_PATENTS",
                    "RECENT_RECOMMENDATIONS",
                    "PROJECT",
                    "RECOMMENDATION",
                    name="researchpointtype",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_archetype", "transformer_blocklist")
    # ### end Alembic commands ###
