"""Added user-agent to sdr

Revision ID: c0f2a3066285
Revises: 264ea91054a8
Create Date: 2023-11-07 12:59:41.860750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f2a3066285'
down_revision = '264ea91054a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'user_agent')
    # ### end Alembic commands ###
