"""Add enum type

Revision ID: c2113e31b20d
Revises: 1e2a83990f83
Create Date: 2024-08-21 00:23:23.378476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2113e31b20d'
down_revision = '1e2a83990f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE researchtype ADD VALUE 'AI_QUESTION_DATA'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
