"""empty message

Revision ID: c35cfce54e46
Revises: 520bf2c3e0a4
Create Date: 2022-09-29 10:58:20.917362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35cfce54e46'
down_revision = '520bf2c3e0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('prospect_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_message', 'prospect', ['prospect_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_message', type_='foreignkey')
    op.drop_column('generated_message', 'prospect_id')
    # ### end Alembic commands ###
