"""Add SmartleadWebhookPayloads

Revision ID: c518fe5f4c61
Revises: de21f6c624a9
Create Date: 2023-12-15 10:53:35.358825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c518fe5f4c61"
down_revision = "de21f6c624a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smartlead_webhook_payloads",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("smartlead_payload", sa.JSON(), nullable=False),
        sa.Column(
            "smartlead_webhook_type",
            sa.Enum(
                "EMAIL_SENT",
                "EMAIL_OPENED",
                "EMAIL_REPLIED",
                "EMAIL_BOUNCED",
                name="smartleadwebhooktype",
            ),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "INELIGIBLE",
                "FAILED",
                name="smartleadwebhookprocessingstatus",
            ),
            nullable=False,
        ),
        sa.Column("processing_fail_reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("smartlead_webhook_payloads")
    # ### end Alembic commands ###
