"""Made linkedin_conversation_entry unique

Revision ID: c78b2b8520ad
Revises: 7b052a40bbc5
Create Date: 2023-05-24 23:23:23.980154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78b2b8520ad'
down_revision = '7b052a40bbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_generated_message_auto_bump_latest_li_message_id'), 'generated_message_auto_bump', ['latest_li_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_message_auto_bump_latest_li_message_id'), table_name='generated_message_auto_bump')
    # ### end Alembic commands ###
