""" Add email_conversation_thread_id and from_sdr to email_conversation_message

Revision ID: c797e5fb1cc8
Revises: 43e2b6667747
Create Date: 2023-04-20 11:50:42.425593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c797e5fb1cc8'
down_revision = '43e2b6667747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_conversation_message', sa.Column('from_sdr', sa.Boolean(), nullable=True))
    op.add_column('email_conversation_message', sa.Column('email_conversation_thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_conversation_message', 'email_conversation_thread', ['email_conversation_thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_conversation_message', type_='foreignkey')
    op.drop_column('email_conversation_message', 'email_conversation_thread_id')
    op.drop_column('email_conversation_message', 'from_sdr')
    # ### end Alembic commands ###
