""" Add li_conversation_urn_id to prospect and indexes it

Revision ID: c84152df8bba
Revises: ed3d59086240
Create Date: 2023-04-18 12:44:46.654788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84152df8bba'
down_revision = 'ed3d59086240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('li_conversation_urn_id', sa.String(), nullable=True))
    op.create_index('idx_li_urn_id', 'prospect', ['li_urn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_li_urn_id', table_name='prospect')
    op.drop_column('prospect', 'li_conversation_urn_id')
    # ### end Alembic commands ###
