""" Add adversary identified mistake and fix to generated message

Revision ID: c8ce70936a23
Revises: 0f891a6753d5
Create Date: 2022-12-27 10:59:01.983213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ce70936a23'
down_revision = '0f891a6753d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('adversary_identified_mistake', sa.String(), nullable=True))
    op.add_column('generated_message', sa.Column('adversary_identified_fix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_message', 'adversary_identified_fix')
    op.drop_column('generated_message', 'adversary_identified_mistake')
    # ### end Alembic commands ###
