""" Add outbound_campaign_id to prospect_email

Revision ID: cb504321dc35
Revises: 0fd23db5511a
Create Date: 2023-03-14 10:21:54.110772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb504321dc35'
down_revision = '0fd23db5511a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email', sa.Column('oubound_campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prospect_email', 'outbound_campaign', ['oubound_campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospect_email', type_='foreignkey')
    op.drop_column('prospect_email', 'oubound_campaign_id')
    # ### end Alembic commands ###
