"""Added vessel_sequence_id to client_archetype

Revision ID: cc6798dbbf10
Revises: dc53401e95e0
Create Date: 2023-04-05 16:21:12.820837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6798dbbf10'
down_revision = 'dc53401e95e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('vessel_sequence_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'vessel_sequence_id')
    # ### end Alembic commands ###
