""" Add outbound_campaign_id to generated_message

Revision ID: cd71170ba259
Revises: 19b132a8c36f
Create Date: 2023-03-13 14:30:02.500485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd71170ba259'
down_revision = '19b132a8c36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('outbound_campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_message', 'outbound_campaign', ['outbound_campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_message', type_='foreignkey')
    op.drop_column('generated_message', 'outbound_campaign_id')
    # ### end Alembic commands ###
