"""Added auto_send_campaigns_enabled to client_sdr

Revision ID: cdd926b564eb
Revises: b68c2b47bc01
Create Date: 2023-09-25 22:14:41.484463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd926b564eb'
down_revision = 'b68c2b47bc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('auto_send_campaigns_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'auto_send_campaigns_enabled')
    # ### end Alembic commands ###
