"""empty message

Revision ID: cde30ed4d32f
Revises: 0c4832ed4926
Create Date: 2022-10-27 14:04:59.575181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde30ed4d32f'
down_revision = '0c4832ed4926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_message', sa.Column('adversarial_ai_prediction', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_message', 'adversarial_ai_prediction')
    # ### end Alembic commands ###
