"""Create EmailMessagingSchedule

Revision ID: cfbed4351ddc
Revises: c17e73d84608
Create Date: 2023-10-11 12:05:52.893754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbed4351ddc'
down_revision = 'c17e73d84608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messaging_schedule',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=False),
    sa.Column('prospect_email_id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.Enum('INITIAL_EMAIL', 'FOLLOW_UP_EMAIL', name='emailmessagingtype'), nullable=False),
    sa.Column('subject_line_id', sa.Integer(), nullable=True),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.Column('email_subject_line_template_id', sa.Integer(), nullable=False),
    sa.Column('email_body_template_id', sa.Integer(), nullable=False),
    sa.Column('send_status', sa.Enum('NEEDS_GENERATION', 'SCHEDULED', 'SENT', 'FAILED', name='emailmessagingstatus'), nullable=False),
    sa.Column('send_status_error', sa.String(), nullable=True),
    sa.Column('date_scheduled', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['generated_message.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.ForeignKeyConstraint(['email_body_template_id'], ['email_sequence_step.id'], ),
    sa.ForeignKeyConstraint(['email_subject_line_template_id'], ['email_subject_line_template.id'], ),
    sa.ForeignKeyConstraint(['prospect_email_id'], ['prospect_email.id'], ),
    sa.ForeignKeyConstraint(['subject_line_id'], ['generated_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_messaging_schedule')
    # ### end Alembic commands ###
