"""empty message

Revision ID: d0180fca74b9
Revises: 3be2527f1609
Create Date: 2022-11-02 17:54:11.351986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0180fca74b9'
down_revision = '3be2527f1609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_schema',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_archetype_id', sa.Integer(), nullable=False),
    sa.Column('email_firstline_gnlp_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_archetype_id'], ['client_archetype.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['email_firstline_gnlp_model_id'], ['gnlp_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_schema')
    # ### end Alembic commands ###
