""" Create tables and enums for prospect uploads v2. 

New Table: ProspectUploads (individual rows)
New Table: ProspectUploadsRawCSV (entire CSV)
New Enum: ProspectUploadsStatus (UPLOAD_COMPLETE, UPLOAD_IN_PROGRESS, UPLOAD_FAILED, UPLOAD_NOT_STARTED, DISQUALIFIED)
New Enum: ProspectUploadsErrorType (DUPLICATE, ISCRAPER_FAILED)

Revision ID: d060da6d3dbd
Revises: dfaab7128909
Create Date: 2023-01-23 12:29:18.801034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd060da6d3dbd'
down_revision = 'dfaab7128909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect_uploads_raw_csv',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_archetype_id', sa.Integer(), nullable=True),
    sa.Column('client_sdr_id', sa.Integer(), nullable=True),
    sa.Column('prospect_upload_id', sa.Integer(), nullable=True),
    sa.Column('csv_data', sa.LargeBinary(), nullable=False),
    sa.Column('prospect_uploads_raw_csv', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_archetype_id'], ['client_archetype.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect_uploads',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_archetype_id', sa.Integer(), nullable=True),
    sa.Column('client_sdr_id', sa.Integer(), nullable=True),
    sa.Column('prospect_uploads_raw_csv_id', sa.Integer(), nullable=True),
    sa.Column('csv_row_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('csv_row_hash', sa.String(), nullable=False),
    sa.Column('upload_attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOAD_COMPLETE', 'UPLOAD_QUEUED', 'UPLOAD_IN_PROGRESS', 'UPLOAD_FAILED', 'UPLOAD_NOT_STARTED', 'DISQUALIFIED', name='prospectuploadsstatus'), nullable=False),
    sa.Column('error_type', sa.Enum('DUPLICATE', 'ISCRAPER_FAILED', name='prospectuploadserrortype'), nullable=True),
    sa.Column('iscraper_error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_archetype_id'], ['client_archetype.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.ForeignKeyConstraint(['prospect_uploads_raw_csv_id'], ['prospect_uploads_raw_csv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect_uploads')
    op.drop_table('prospect_uploads_raw_csv')
    op.execute("DROP TYPE prospectuploadsstatus")
    op.execute("DROP TYPE prospectuploadserrortype")
    # ### end Alembic commands ###
