"""Add sales_engagement_interaction_ss_id to prospect_email_status_records

Revision ID: d076167ecfbf
Revises: aed90c2b672b
Create Date: 2023-02-07 09:46:20.928933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd076167ecfbf'
down_revision = 'aed90c2b672b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email_status_records', sa.Column('sales_engagement_interaction_ss_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prospect_email_status_records', 'sales_engagement_interaction_ss', ['sales_engagement_interaction_ss_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospect_email_status_records', type_='foreignkey')
    op.drop_column('prospect_email_status_records', 'sales_engagement_interaction_ss_id')
    # ### end Alembic commands ###
