"""empty message

Revision ID: d0d7b7081d56
Revises: d5393de141fd
Create Date: 2022-10-25 14:14:14.086490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d7b7081d56'
down_revision = 'd5393de141fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'last_reviewed')
    # ### end Alembic commands ###
