"""Added website metadata cache table

Revision ID: d1617d0da11c
Revises: 24688361e9cf
Create Date: 2023-10-06 23:05:32.351215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1617d0da11c"
down_revision = "24688361e9cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "website_metadata_cache",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("website_url", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("products", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("industries", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("target_profiles", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("company_type", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("highlights", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("linkedin_url", sa.String(), nullable=False),
        sa.Column("twitter_url", sa.String(), nullable=False),
        sa.Column("crunchbase_url", sa.String(), nullable=False),
        sa.Column("instagram_url", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("website_metadata_cache")
    # ### end Alembic commands ###
