""" Remove client archetype from sales engagement interaction (raw and ss)

client_archetype_id is no longer used in outreach analytics attribution, we apply across the board.

Revision ID: d18acc0f8e88
Revises: fdd6c47ca33d
Create Date: 2023-02-07 14:21:36.400110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18acc0f8e88'
down_revision = 'fdd6c47ca33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_engagement_interaction_raw_client_archetype_id_fkey', 'sales_engagement_interaction_raw', type_='foreignkey')
    op.drop_column('sales_engagement_interaction_raw', 'client_archetype_id')
    op.drop_constraint('sales_engagement_interaction_ss_client_archetype_id_fkey', 'sales_engagement_interaction_ss', type_='foreignkey')
    op.drop_column('sales_engagement_interaction_ss', 'client_archetype_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_engagement_interaction_ss', sa.Column('client_archetype_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sales_engagement_interaction_ss_client_archetype_id_fkey', 'sales_engagement_interaction_ss', 'client_archetype', ['client_archetype_id'], ['id'])
    op.add_column('sales_engagement_interaction_raw', sa.Column('client_archetype_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sales_engagement_interaction_raw_client_archetype_id_fkey', 'sales_engagement_interaction_raw', 'client_archetype', ['client_archetype_id'], ['id'])
    # ### end Alembic commands ###
