"""linkedin_prospect_removed

Revision ID: d231c62d103f
Revises: 4e8c385149ba
Create Date: 2024-02-09 01:24:06.473219

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d231c62d103f"
down_revision = "4e8c385149ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE slacknotificationtype ADD VALUE 'LINKEDIN_PROSPECT_REMOVED'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        "ALTER TYPE slacknotificationtype DROP VALUE 'LINKEDIN_PROSPECT_REMOVED'"
    )

    # ### end Alembic commands ###
