""" Add nylas_account_id to client_sdr

Revision ID: d4f8155936f4
Revises: a77c8033009f
Create Date: 2023-03-30 07:20:49.547493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f8155936f4'
down_revision = 'a77c8033009f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_sdr', sa.Column('nylas_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_sdr', 'nylas_account_id')
    # ### end Alembic commands ###
