"""Add Last convo from me and datetime to prospect model

Revision ID: d5393de141fd
Revises: a6f9f4fb6282
Create Date: 2022-10-24 10:31:37.974251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d5393de141fd"
down_revision = "a6f9f4fb6282"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect", sa.Column("li_last_message_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "prospect",
        sa.Column("li_is_last_message_from_sdr", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "li_is_last_message_from_sdr")
    op.drop_column("prospect", "li_last_message_timestamp")
    # ### end Alembic commands ###
