"""Add attached_segment_tag_ids column to segment table

Revision ID: d675be6176b6
Revises: e32335b3f460
Create Date: 2024-05-07 14:09:58.829421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd675be6176b6'
down_revision = 'e32335b3f460'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('segment', sa.Column('attached_segment_tag_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'attached_segment_tag_ids')
    # ### end Alembic commands ###
