"""Add scrape name

Revision ID: d6814335ece9
Revises: cd940faff997
Create Date: 2023-07-27 15:47:25.661895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6814335ece9'
down_revision = 'cd940faff997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phantom_buster_sales_navigator_launch', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phantom_buster_sales_navigator_launch', 'name')
    # ### end Alembic commands ###
