"""Add client_sdr_id to ICPScoringJobQueue

Revision ID: d750c246b990
Revises: 9dac7b767c42
Create Date: 2023-09-26 14:49:12.314339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd750c246b990'
down_revision = '9dac7b767c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_scoring_job_queue', sa.Column('client_sdr_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'icp_scoring_job_queue', 'client_sdr', ['client_sdr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'icp_scoring_job_queue', type_='foreignkey')
    op.drop_column('icp_scoring_job_queue', 'client_sdr_id')
    # ### end Alembic commands ###
