"""Added num_sends, num_opens, and num_replies to client_archetype_assets

Revision ID: d79233898e5a
Revises: 705b1d000549
Create Date: 2024-02-28 13:07:28.781697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d79233898e5a"
down_revision = "705b1d000549"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_archetype_assets", sa.Column("num_sends", sa.Integer(), nullable=True)
    )
    op.add_column(
        "client_archetype_assets", sa.Column("num_opens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "client_archetype_assets", sa.Column("num_replies", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_archetype_assets", "num_replies")
    op.drop_column("client_archetype_assets", "num_opens")
    op.drop_column("client_archetype_assets", "num_sends")
    # ### end Alembic commands ###
