"""Status is an enum

Revision ID: d89e740c04b2
Revises: d750c246b990
Create Date: 2023-09-26 15:18:26.433389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd89e740c04b2'
down_revision = 'd750c246b990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    icpscoringjobqueuestatus = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name="icpscoringjobqueuestatus")
    icpscoringjobqueuestatus.create(op.get_bind())
    op.add_column('icp_scoring_job_queue', sa.Column('run_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='icpscoringjobqueuestatus'), nullable=False))
    op.drop_column('icp_scoring_job_queue', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_scoring_job_queue', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('icp_scoring_job_queue', 'run_status')
    # ### end Alembic commands ###
