"""Added do_not_contact_company_names and do_not_contact_keywords_in_company_names to client

Revision ID: da3a3fdf394e
Revises: 3101caedb4f8
Create Date: 2023-05-04 18:20:47.405759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da3a3fdf394e"
down_revision = "3101caedb4f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "do_not_contact_keywords_in_company_names",
            sa.ARRAY(sa.String()),
            nullable=True,
        ),
    )
    op.add_column(
        "client",
        sa.Column("do_not_contact_company_names", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "do_not_contact_company_names")
    op.drop_column("client", "do_not_contact_keywords_in_company_names")
    # ### end Alembic commands ###
