"""empty message

Revision ID: da9ba7942056
Revises: afbb4830281e
Create Date: 2022-12-12 14:23:17.920997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9ba7942056'
down_revision = 'afbb4830281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sight_onboarding', 'client_sdr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sight_onboarding', 'client_sdr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
