"""Added company size

Revision ID: dae559efed7b
Revises: 567eb03415c5
Create Date: 2024-02-27 17:10:39.662072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae559efed7b'
down_revision = '567eb03415c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('company_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'company_size')
    # ### end Alembic commands ###
