"""Added sequence table

Revision ID: db4494bdb337
Revises: 485a1be98d03
Create Date: 2023-04-28 13:39:05.613828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db4494bdb337"
down_revision = "485a1be98d03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_builder_samples",
        sa.Column("research_point_ids", sa.ARRAY(sa.Integer()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_builder_samples", "research_point_ids")
    # ### end Alembic commands ###
