"""Updated outbound_campaign and prospect_email

Revision ID: dc475066e655
Revises: 96038d143a39
Create Date: 2023-02-28 14:35:30.776086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc475066e655"
down_revision = "96038d143a39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbound_campaign", "vessel_sequence_id")
    op.add_column(
        "prospect_email", sa.Column("vessel_sequence_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect_email", "vessel_sequence_id")
    op.add_column(
        "outbound_campaign",
        sa.Column(
            "vessel_sequence_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
