"""Add client_id to both VesselMailboxes and VesselSequences

Revision ID: dcfa365eace0
Revises: 6067fd01c3dd
Create Date: 2023-04-19 16:19:53.086544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfa365eace0'
down_revision = '6067fd01c3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_mailboxes', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vessel_mailboxes', 'client', ['client_id'], ['id'])
    op.add_column('vessel_sequences', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vessel_sequences', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vessel_sequences', type_='foreignkey')
    op.drop_column('vessel_sequences', 'client_id')
    op.drop_constraint(None, 'vessel_mailboxes', type_='foreignkey')
    op.drop_column('vessel_mailboxes', 'client_id')
    # ### end Alembic commands ###
