"""Added Start and End Date to Strategies.

Revision ID: dd82d1374006
Revises: 074ff15a4edf
Create Date: 2024-07-15 13:30:02.485769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd82d1374006'
down_revision = '074ff15a4edf'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('stragegies', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('stragegies', sa.Column('end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stragegies', 'end_date')
    op.drop_column('stragegies', 'start_date')
    # ### end Alembic commands ###
