"""Added process type

Revision ID: defe93ccd9af
Revises: a41a135b3bd5
Create Date: 2023-11-02 15:22:15.050311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defe93ccd9af'
down_revision = 'a41a135b3bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phantom_buster_sales_navigator_launch', sa.Column('process_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phantom_buster_sales_navigator_launch', 'process_type')
    # ### end Alembic commands ###
