"""Added prospect meta_data

Revision ID: df0c3ca8de30
Revises: 85fcc3af3a18
Create Date: 2024-02-07 15:23:40.023160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df0c3ca8de30"
down_revision = "85fcc3af3a18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prospect", sa.Column("meta_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "meta_data")
    # ### end Alembic commands ###
