"""Added always_enable to stack_ranked_message_generation_configuration table

Revision ID: e0a275cb6c56
Revises: 31a3d9ceec03
Create Date: 2023-02-16 10:26:06.846288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0a275cb6c56"
down_revision = "31a3d9ceec03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column("always_enable", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stack_ranked_message_generation_configuration", "always_enable")
    # ### end Alembic commands ###
