"""empty message

Revision ID: e1d78169ccfc
Revises: 03a36b63f090
Create Date: 2024-06-07 16:48:28.591538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d78169ccfc'
down_revision = '03a36b63f090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_team_messages', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_team_messages', 'display_name')
    # ### end Alembic commands ###
