"""empty message

Revision ID: e4f2dfc457f1
Revises: 9c8ba85e9d07
Create Date: 2022-10-11 12:52:25.636635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "e4f2dfc457f1"
down_revision = "9c8ba85e9d07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prospect_status_records",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=True),
        sa.Column(
            "from_status",
            postgresql.ENUM(
                "PROSPECTED",
                "NOT_QUALIFIED",
                "SENT_OUTREACH",
                "RESPONDED",
                "NOT_INTERESTED",
                "DEMO_SET",
                "DEMO_WON",
                "DEMO_LOSS",
                name="prospectstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            postgresql.ENUM(
                "PROSPECTED",
                "NOT_QUALIFIED",
                "SENT_OUTREACH",
                "RESPONDED",
                "NOT_INTERESTED",
                "DEMO_SET",
                "DEMO_WON",
                "DEMO_LOSS",
                name="prospectstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prospect_status_records")
    # ### end Alembic commands ###
