"""Add attr under Prospects for deactivating AI

Revision ID: e53e72a55a59
Revises: dc51fffdc1e7
Create Date: 2022-11-24 11:40:34.861907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e53e72a55a59"
down_revision = "dc51fffdc1e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect", sa.Column("deactivate_ai_engagement", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "deactivate_ai_engagement")
    # ### end Alembic commands ###
