"""reply_instructions -> template and add additional_instructions

Revision ID: e61646aac55e
Revises: a220c1a4c1a7
Create Date: 2024-01-10 14:00:19.588563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e61646aac55e"
down_revision = "a220c1a4c1a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_reply_framework",
        sa.Column("additional_instructions", sa.String(), nullable=True),
    )
    op.alter_column(
        "email_reply_framework", "reply_instructions", new_column_name="template"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_reply_framework", "template", new_column_name="reply_instructions"
    )
    op.drop_column("email_reply_framework", "additional_instructions")
    # ### end Alembic commands ###
