"""Added prospect events

Revision ID: e86485b15e65
Revises: 5bd145039bf2
Create Date: 2023-05-26 19:23:06.436987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86485b15e65'
down_revision = '5bd145039bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect_event',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('nylas_event_id', sa.String(), nullable=False),
    sa.Column('nylas_calendar_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('meeting_info', sa.JSON(), nullable=False),
    sa.Column('nylas_data_raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_event_nylas_event_id'), 'prospect_event', ['nylas_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospect_event_nylas_event_id'), table_name='prospect_event')
    op.drop_table('prospect_event')
    # ### end Alembic commands ###
