"""Apollo cookies

Revision ID: e8c08a4b9896
Revises: 0eff055f1e50
Create Date: 2024-06-21 10:56:02.168850

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e8c08a4b9896"
down_revision = "0eff055f1e50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apollo_cookies",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cookies", sa.String(), nullable=False),
        sa.Column("csrf_token", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apollo_cookies")
    # ### end Alembic commands ###
