"""Added additional_context to bump_framework

Revision ID: e986d39fb0a1
Revises: a5ea567621af
Create Date: 2023-09-19 12:15:13.773849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e986d39fb0a1"
down_revision = "a5ea567621af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bump_framework", sa.Column("additional_context", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bump_framework", "additional_context")
    # ### end Alembic commands ###
