"""Added persona split request tables

Revision ID: ef0415c35f16
Revises: 7ea6b81a0612
Create Date: 2023-04-26 13:48:22.703288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef0415c35f16"
down_revision = "7ea6b81a0612"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona_split_request",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_sdr_id", sa.Integer(), nullable=True),
        sa.Column("source_client_archetype_id", sa.Integer(), nullable=True),
        sa.Column(
            "destination_client_archetype_ids", sa.ARRAY(sa.Integer()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["client_sdr_id"],
            ["client_sdr.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_client_archetype_id"],
            ["client_archetype.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persona_split_request_task",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("persona_split_request_id", sa.Integer(), nullable=True),
        sa.Column("prospect_id", sa.Integer(), nullable=True),
        sa.Column(
            "destination_client_archetype_ids", sa.ARRAY(sa.Integer()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="personasplitrequesttaskstatus",
            ),
            nullable=True,
        ),
        sa.Column("tries", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_split_request_id"],
            ["persona_split_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persona_split_request_task")
    op.drop_table("persona_split_request")
    # ### end Alembic commands ###
