"""Added original company and title to prospect

Revision ID: ef43f9c9c6c4
Revises: 461f48632ce2
Create Date: 2023-11-21 17:05:58.417043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef43f9c9c6c4"
down_revision = "461f48632ce2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prospect", sa.Column("original_company", sa.String(), nullable=True))
    op.add_column("prospect", sa.Column("original_title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "original_title")
    op.drop_column("prospect", "original_company")
    # ### end Alembic commands ###
