"""Add model syncing flags onto ClientSyncCRM

Revision ID: f265561d3f4e
Revises: 0e6b2dc95c4a
Create Date: 2024-04-25 10:26:30.290390

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f265561d3f4e"
down_revision = "0e6b2dc95c4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client_sync_crm", sa.Column("lead_sync", sa.String(), nullable=True))
    op.add_column(
        "client_sync_crm", sa.Column("contact_sync", sa.String(), nullable=True)
    )
    op.add_column(
        "client_sync_crm", sa.Column("account_sync", sa.String(), nullable=True)
    )
    op.add_column(
        "client_sync_crm", sa.Column("opportunity_sync", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_sync_crm", "opportunity_sync")
    op.drop_column("client_sync_crm", "account_sync")
    op.drop_column("client_sync_crm", "contact_sync")
    op.drop_column("client_sync_crm", "lead_sync")
    # ### end Alembic commands ###
