"""Rename channel_warmup -> warmup_snapshot and drop client_warmup

Revision ID: f2913b944d10
Revises: 50e396996917
Create Date: 2023-11-08 13:09:38.452692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2913b944d10'
down_revision = '50e396996917'
branch_labels = None
depends_on = None

# This function will be used in both the upgrade and downgrade operations


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE channel_warmup RENAME TO warmup_snapshot")
    op.drop_table('client_warmup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_warmup',
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('client_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('date', sa.DATE(),
                              autoincrement=False, nullable=False),
                    sa.Column('linkedin_warmup_volume', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('email_warmup_volume', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('total_warmup_volume', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['client_id'], ['client.id'], name='client_warmup_client_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='client_warmup_pkey')
                    )
    op.execute("ALTER TABLE warmup_snapshot RENAME TO channel_warmup")
    # ### end Alembic commands ###
