"""empty message

Revision ID: f4caba3dd9de
Revises: 4fe7a934767e
Create Date: 2022-11-15 18:37:59.190688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4caba3dd9de'
down_revision = '4fe7a934767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_campaign', sa.Column('email_schema_id', sa.Integer(), nullable=True))
    op.alter_column('outbound_campaign', 'ctas',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.create_foreign_key(None, 'outbound_campaign', 'email_schema', ['email_schema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outbound_campaign', type_='foreignkey')
    op.alter_column('outbound_campaign', 'ctas',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.drop_column('outbound_campaign', 'email_schema_id')
    # ### end Alembic commands ###
