"""empty message

Revision ID: f4ead65767c1
Revises: b9967a788dd8
Create Date: 2022-11-03 17:54:20.858756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ead65767c1'
down_revision = 'b9967a788dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email', sa.Column('date_sent', sa.DateTime(), nullable=True))
    op.add_column('prospect_email', sa.Column('batch_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect_email', 'batch_id')
    op.drop_column('prospect_email', 'date_sent')
    # ### end Alembic commands ###
