"""Added selix session and task tables

Revision ID: f5ea22278265
Revises: 40eb6778d331
Create Date: 2024-07-29 18:58:39.439010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ea22278265'
down_revision = '40eb6778d331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selix_session',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdr_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETE', 'CANCELLED', 'PENDING_OPERATOR', name='selixsessionstatus'), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=True),
    sa.Column('estimated_completion_time', sa.DateTime(), nullable=True),
    sa.Column('actual_completion_time', sa.DateTime(), nullable=True),
    sa.Column('assistant_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_sdr_id'], ['client_sdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selix_session_task',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selix_session_id', sa.Integer(), nullable=False),
    sa.Column('actual_completion_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETE', 'CANCELLED', name='selixsessiontaskstatus'), nullable=False),
    sa.ForeignKeyConstraint(['selix_session_id'], ['selix_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selix_session_task')
    op.drop_table('selix_session')
    # ### end Alembic commands ###
