"""Added icp_fit_prompt_data column to prospect

Revision ID: f6154585adfd
Revises: 9ae7af5c4169
Create Date: 2023-06-12 09:29:13.896693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6154585adfd"
down_revision = "9ae7af5c4169"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prospect", sa.Column("icp_fit_prompt_data", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prospect", "icp_fit_prompt_data")
    # ### end Alembic commands ###
