"""Added sent_activation_notification to client_archetype

Revision ID: f6ee0e1ba58b
Revises: d46c556e53d4
Create Date: 2023-11-15 12:20:55.746722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6ee0e1ba58b'
down_revision = 'd46c556e53d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('sent_activation_notification', sa.Boolean(), nullable=True))
    op.alter_column('individuals_upload', 'status',
               existing_type=postgresql.ENUM('FILTER_AND_UPLOAD', 'COMPLETE', name='individualsuploadstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individuals_upload', 'status',
               existing_type=postgresql.ENUM('FILTER_AND_UPLOAD', 'COMPLETE', name='individualsuploadstatus'),
               nullable=False)
    op.drop_column('client_archetype', 'sent_activation_notification')
    # ### end Alembic commands ###
