"""empRemove generated_message_ids from stack_ranked_message_generation_configuration

Revision ID: f7514eb88322
Revises: f29ccf5d7d96
Create Date: 2023-02-23 09:17:48.643867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f7514eb88322"
down_revision = "f29ccf5d7d96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "stack_ranked_message_generation_configuration", "generated_message_ids"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stack_ranked_message_generation_configuration",
        sa.Column(
            "generated_message_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
