"""Add new fields and deprecate fields for ClientSyncCRM

Revision ID: f7ddb1c9c8ba
Revises: 2712f3f704c1
Create Date: 2024-04-18 12:14:40.764298

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7ddb1c9c8ba"
down_revision = "2712f3f704c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sync_crm",
        sa.Column("initiating_client_sdr_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "client_sync_crm", sa.Column("account_token", sa.String(), nullable=False)
    )
    op.add_column("client_sync_crm", sa.Column("crm_type", sa.String(), nullable=False))
    op.create_foreign_key(
        None, "client_sync_crm", "client_sdr", ["initiating_client_sdr_id"], ["id"]
    )
    op.drop_column("client_sync_crm", "sync_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_sync_crm",
        sa.Column("sync_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "client_sync_crm", type_="foreignkey")
    op.drop_column("client_sync_crm", "crm_type")
    op.drop_column("client_sync_crm", "account_token")
    op.drop_column("client_sync_crm", "initiating_client_sdr_id")
    # ### end Alembic commands ###
