"""Added persona description and good fit

Revision ID: fa15d37a8ef0
Revises: ae37438647e6
Create Date: 2023-03-28 17:31:17.846974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa15d37a8ef0'
down_revision = 'ae37438647e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_archetype', sa.Column('description', sa.String(), nullable=True))
    op.add_column('client_archetype', sa.Column('good_fit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_archetype', 'good_fit')
    op.drop_column('client_archetype', 'description')
    # ### end Alembic commands ###
