"""empty message

Revision ID: fb6bed62d598
Revises: f48ec1588973
Create Date: 2022-09-28 16:23:17.204021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6bed62d598'
down_revision = 'f48ec1588973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gnlp_models',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.Enum('OPENAI_GPT3', name='modelprovider'), nullable=False),
    sa.Column('model_type', sa.Enum('OUTREACH', name='gnlpmodeltype'), nullable=False),
    sa.Column('model_uuid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_message',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gnlp_model_id', sa.Integer(), nullable=True),
    sa.Column('research_points', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('completion', sa.String(), nullable=False),
    sa.Column('message_status', sa.Enum('DRAFT', 'BLOCKED', 'SENT', name='generatedmessagestatus'), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gnlp_model_id'], ['gnlp_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_message')
    op.drop_table('gnlp_models')
    # ### end Alembic commands ###
