"""empty message

Revision ID: fe14d52cf325
Revises: 7d4cf3f53696
Create Date: 2022-09-28 12:55:11.553856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe14d52cf325'
down_revision = '7d4cf3f53696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('linkedin_bio', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['client_archetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect')
    # ### end Alembic commands ###
