"""Add not qualified to Email Outreach Statuses

Revision ID: ff2743a4ebf5
Revises: 5e6baac18a86
Create Date: 2023-12-07 11:01:19.938585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff2743a4ebf5"
down_revision = "5e6baac18a86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE prospectemailoutreachstatus ADD VALUE IF NOT EXISTS 'NOT_QUALIFIED';"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
