"""adding the additional context columns to the email and linkedin status records table, to record any
changes whenever we reset a client.

Revision ID: ff3e72a0db1c
Revises: 4e88eb0d94f5
Create Date: 2024-07-26 17:03:54.059589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3e72a0db1c'
down_revision = '4e88eb0d94f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_email_status_records', sa.Column('additional_context', sa.String(), nullable=True))
    op.add_column('prospect_status_records', sa.Column('additional_context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect_status_records', 'additional_context')
    op.drop_column('prospect_email_status_records', 'additional_context')
    # ### end Alembic commands ###
