"""Add entry_processed_manually to li_conversation

Revision ID: ff56be6da497
Revises: 4d40c073b1a6
Create Date: 2023-04-18 15:50:17.710167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff56be6da497'
down_revision = '4d40c073b1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_conversation_entry', sa.Column('entry_processed_manually', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_conversation_entry', 'entry_processed_manually')
    # ### end Alembic commands ###
