import datetime
from src.research.linkedin.extractors.recommendations import (
    get_recent_recommendation_summary,
)
import mock
import json


@mock.patch(
    "src.research.linkedin.extractors.recommendations.get_completion",
    return_value="testing response",
)
def test_get_recent_recommendation_summary(get_completion_patch):
    info_with_no_recommendation = {
        "personal": {
            "profile_id": "mark-grogan-94b0882a",
            "entity_urn": "ACoAAAYP40sB3KH9MWqQcwm9n4HSnRBmTd4TTwQ",
            "object_urn": "101704523",
            "first_name": "Mark",
            "last_name": "Grogan",
            "sub_title": "Senior Compensation Manager at Salesforce",
            "birth_date": None,
            "profile_picture": "https://media-exp1.licdn.com/dms/image/C4D03AQHKtFtVeAodoA/profile-displayphoto-shrink_400_400/0/1595898298718?e=1670457600&v=beta&t=MMOU0YFnFH2sztqyFir7-U_2QbFIQ8vqw2eNifNAlm0",
            "summary": "Strategic leader who partners closely with the executive team to design and develop compensation programming that advances business strategies and objectives.\n\nResults driven manager, focused on building developing high performing teams.\n\n10 plus years of experience at a Fortune 500 company.",
            "location": {
                "country": "United States",
                "short": "Kansas City, Missouri",
                "city": "Kansas City",
                "state": "Missouri",
                "default": "Kansas City, Missouri, United States",
            },
            "premium": False,
            "influencer": False,
            "treasury_media": [],
            "languages": {
                "primary_locale": {"country": "US", "language": "en"},
                "supported_locales": [{"country": "US", "language": "en"}],
                "profile_languages": [],
            },
            "industry": "Information Technology & Services",
            "education": [
                {
                    "date": {
                        "start": {"month": None, "year": None},
                        "end": {"month": None, "year": None},
                    },
                    "school": {
                        "name": "Missouri State University",
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHHRNEnG3Trpg/company-logo_400_400/0/1519855995282?e=1672876800&v=beta&t=VIFZzJWFaQbajEcQLkEJPio9iEgN0le8Qibkp1cOhRE",
                    },
                    "degree_name": "Bachelor's Degree",
                    "field_of_study": "Marketing- Advertising and Promotions",
                }
            ],
            "patents": [],
            "awards": [],
            "certifications": [],
            "organizations": [],
            "projects": [],
            "publications": [],
            "courses": [],
            "test_scores": [],
            "position_groups": [
                {
                    "company": {
                        "name": "Salesforce",
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHZ9xYomLW7zg/company-logo_400_400/0/1591198956689?e=1672876800&v=beta&t=JMElmvDj--xs2ilRrUtpBFCAo-_B2Bq6Thm4JFQ88I4",
                        "url": "https://www.linkedin.com/company/salesforce/",
                        "employees": {"start": 10001, "end": None},
                    },
                    "company_url": "https://www.linkedin.com/company/salesforce/",
                    "date": {
                        "start": {"month": 9, "year": 2021},
                        "end": {"month": None, "year": None},
                    },
                    "profile_positions": [
                        {
                            "location": None,
                            "date": {
                                "start": {"month": 9, "year": 2021},
                                "end": {"month": None, "year": None},
                            },
                            "company": "Salesforce",
                            "description": None,
                            "title": "Senior Manager Compensation",
                        }
                    ],
                },
                {
                    "company": {
                        "name": "Cerner Corporation",
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQGE9flTBMlYvA/company-logo_400_400/0/1654690655463?e=1672876800&v=beta&t=sYMZO9wxGBae-gutgsqb9iLSyoYA5qH257twlKz4QHg",
                        "url": "https://www.linkedin.com/company/cerner-corporation/",
                        "employees": {"start": 10001, "end": None},
                    },
                    "company_url": "https://www.linkedin.com/company/cerner-corporation/",
                    "date": {
                        "start": {"month": 2, "year": 2010},
                        "end": {"month": 9, "year": 2021},
                    },
                    "profile_positions": [
                        {
                            "location": None,
                            "date": {
                                "start": {"month": 7, "year": 2020},
                                "end": {"month": 9, "year": 2021},
                            },
                            "company": "Cerner Corporation",
                            "description": "Responsible for development, implementation, administration and maintenance of compensation programs, including implementing incentive compensation plans (sales and non-sales).  This includes competitively benchmarking base pay, performance pay, while maintaining compliance with pay practices.  Also responsible for equity administration, and executive compensation.",
                            "title": "Director Compensation",
                        },
                        {
                            "location": None,
                            "date": {
                                "start": {"month": 5, "year": 2017},
                                "end": {"month": 7, "year": 2020},
                            },
                            "company": "Cerner Corporation",
                            "description": None,
                            "title": "Senior Manager Compensation",
                        },
                        {
                            "location": None,
                            "date": {
                                "start": {"month": 3, "year": 2013},
                                "end": {"month": 5, "year": 2017},
                            },
                            "company": "Cerner Corporation",
                            "description": None,
                            "title": "Human Resources Manager",
                        },
                        {
                            "location": None,
                            "date": {
                                "start": {"month": 2, "year": 2010},
                                "end": {"month": 3, "year": 2013},
                            },
                            "company": "Cerner Corporation",
                            "description": None,
                            "title": "Human Resources Analyst",
                        },
                    ],
                },
            ],
            "volunteer_experiences": [
                {
                    "date": {
                        "start": {"month": 12, "year": 2014},
                        "end": {"month": 12, "year": 2016},
                    },
                    "role": "Board Member",
                    "company": {
                        "name": "Missouri State University Alumni Association Board of Directors",
                        "logo": None,
                        "url": None,
                    },
                    "cause": "EDUCATION",
                    "description": None,
                }
            ],
            "skills": [
                "PeopleSoft",
                "Management",
                "Leadership",
                "Time Management",
                "Process Improvement",
                "Business Intelligence",
                "College Recruiting",
            ],
            "network_info": {
                "followable": True,
                "followers_count": 958,
                "connections_count": 500,
            },
            "recommendations": [
                {
                    "first_name": "James",
                    "last_name": "von Gillern",
                    "occupation": "Realtor at Coldwell Banker Mid America Group",
                    "profile_id": "james-von-gillern-64830117",
                    "created_at": "2012-04-13T14:51:31.687000",
                    "updated_at": "2012-04-17T13:07:49.667000",
                    "text": "Mark and I started at Cerner at the same time and trained together in the Business Consultant program. He is a trustworthy guy that you could always rely on to give his best effort and to think outside the box. He is a tremendous asset to his team and to his company.\r\n\r\nPS-Congrats on the move to Team Lead Mark!",
                }
            ],
            "contact_info": {"websites": [], "email": None, "twitter": None},
            "related_profiles": [
                {
                    "profile_id": "sherry-tran-667546126",
                    "first_name": "Sherry",
                    "last_name": "Tran",
                    "title": "Compensation Manager at Salesforce",
                    "image_url": None,
                },
                {
                    "profile_id": "jeff-lallana-77666a",
                    "first_name": "Jeff",
                    "last_name": "Lallana",
                    "title": "Director Compensation at Salesforce",
                    "image_url": "https://media-exp1.licdn.com/dms/image/C4D03AQGZs1fIDemITQ/profile-displayphoto-shrink_400_400/0/1516246894333?e=1670457600&v=beta&t=uGyC_MReVwaPhGrn3E-JK5dQsrHfvVV1lR3KSn-26aI",
                },
                {
                    "profile_id": "sherri-ellerson-1b411895",
                    "first_name": "Sherri",
                    "last_name": "Ellerson",
                    "title": "Director of Compensation Programs at Salesforce",
                    "image_url": "https://media-exp1.licdn.com/dms/image/C4E03AQGwenaVJsWmDA/profile-displayphoto-shrink_400_400/0/1630168986755?e=1670457600&v=beta&t=8s7MJEVj-6W_kdL6INeQ3CHdUoEcZ6CvQqo6fEsB_wo",
                },
                {
                    "profile_id": "svasnaik",
                    "first_name": "Shwetha",
                    "last_name": "Vasnaik",
                    "title": "Compensation Manager at Salesforce",
                    "image_url": "https://media-exp1.licdn.com/dms/image/C5603AQHY-wGLpa0flw/profile-displayphoto-shrink_400_400/0/1516346403873?e=1670457600&v=beta&t=SkZVq2GRYoZg9S2V21WT0c497vQSho_Rq50n1cr6HlE",
                },
                {
                    "profile_id": "michele-pickle-total-rewards-leader",
                    "first_name": "Michele",
                    "last_name": "Pickle",
                    "title": "SR Director, Compensation at Salesforce",
                    "image_url": "https://media-exp1.licdn.com/dms/image/C5603AQErSldxACtaow/profile-displayphoto-shrink_400_400/0/1551311558864?e=1670457600&v=beta&t=bHlHGOzrptZ7tGL7tQ666ugSnSBi9pv-rH2lEzjITbU",
                },
                {
                    "profile_id": "leah-willert-ccp-091a172",
                    "first_name": "Leah",
                    "last_name": "Willert, CCP",
                    "title": "Sr Compensation Manager at Salesforce",
                    "image_url": "https://media-exp1.licdn.com/dms/image/C5603AQFoZarPKvzx6A/profile-displayphoto-shrink_400_400/0/1607038287006?e=1670457600&v=beta&t=-U_Ydtvt2AD9QhcX1ioDDe7B0LZQO_Shbmq4Ig3Rlyw",
                },
                {
                    "profile_id": "jennifer-johnson-aa62382",
                    "first_name": "Jennifer",
                    "last_name": "Johnson",
                    "title": "Senior Director, Compensation",
                    "image_url": "https://media-exp1.licdn.com/dms/image/C5603AQFE5Y7prBoUvg/profile-displayphoto-shrink_400_400/0/1516253796888?e=1670457600&v=beta&t=lo0BDNtJP7mrEAiI5jId9zgl4q_n-9uBNjFRVwepcI4",
                },
                {
                    "profile_id": "michael-julich-8730066",
                    "first_name": "Michael",
                    "last_name": "Julich",
                    "title": "Senior Manager, Incentive Compensation at Procore Technologies",
                    "image_url": None,
                },
                {
                    "profile_id": "kaleyaf",
                    "first_name": "Kaleya",
                    "last_name": "Ferguson, MBA, PHR",
                    "title": "Talent Leader",
                    "image_url": None,
                },
                {
                    "profile_id": "joel-sekuta-cebs-ccp-543810",
                    "first_name": "Joel",
                    "last_name": "Sekuta, CEBS, CCP",
                    "title": "Vice President Global Compensation",
                    "image_url": None,
                },
            ],
        },
        "company": {
            "details": {
                "name": "Salesforce",
                "universal_name": "salesforce",
                "company_id": "3185",
                "description": "We bring companies and customers together on the #1 CRM. Sharing the news, events, and innovation you need to change the world for good. \n\nPrivacy Statement: http://www.salesforce.com/company/privacy/",
                "tagline": None,
                "founded": None,
                "phone": None,
                "type": "Public Company",
                "staff": {"range": {"start": 10001}, "total": 72006},
                "followers": 3995264,
                "call_to_action": {
                    "url": "http://www.salesforce.com",
                    "text": "Visit website",
                },
                "locations": {
                    "headquarter": {
                        "country": "US",
                        "geographicArea": "CA",
                        "city": "San Francisco",
                        "postalCode": "94105",
                        "line1": "1 Market",
                    },
                    "other": [
                        {
                            "country": "US",
                            "geographicArea": "CA",
                            "city": "San Francisco",
                            "postalCode": "94105",
                            "description": "World Wide Corporate Headquarters",
                            "streetAddressOptOut": False,
                            "headquarter": True,
                            "line1": "1 Market",
                        },
                        {
                            "country": "CH",
                            "geographicArea": "Switzerland",
                            "city": "Staines",
                            "description": "salesforce.com S\u00e0rl (EMEA Regional Headquarters)",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "1 Market",
                        },
                        {
                            "country": "US",
                            "geographicArea": "Singapore",
                            "city": "Singapore",
                            "postalCode": "038989",
                            "description": "salesforce.com (APAC Regional Headquarters)",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "1 Market",
                        },
                        {
                            "country": "US",
                            "geographicArea": "Japan",
                            "city": "Tokyo",
                            "postalCode": "106-6139",
                            "description": "salesforce.com",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "1 Market",
                        },
                        {
                            "country": "DE",
                            "city": "Munich",
                            "postalCode": "80636",
                            "description": "Salesforce Germany",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "Erika-Mann.Stra\u00dfe 63",
                        },
                        {
                            "country": "GB",
                            "geographicArea": "England",
                            "city": "London",
                            "postalCode": "EC2N 3",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "9 Bishopsgate",
                        },
                        {
                            "country": "AU",
                            "geographicArea": "VIC",
                            "city": "Melbourne",
                            "postalCode": "3000",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "55 Collins St",
                        },
                        {
                            "country": "AU",
                            "geographicArea": "NSW",
                            "city": "Sydney",
                            "postalCode": "2000",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "201 Sussex St",
                        },
                        {
                            "country": "FR",
                            "geographicArea": "IdF",
                            "city": "Paris",
                            "postalCode": "75007",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "3 Avenue Octave Greard",
                        },
                        {
                            "country": "US",
                            "geographicArea": "IL",
                            "city": "Chicago",
                            "postalCode": "60654",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "111 W Illinois St",
                        },
                        {
                            "country": "US",
                            "geographicArea": "TX",
                            "city": "Dallas",
                            "postalCode": "75254",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "14902 Preston Rd",
                        },
                        {
                            "country": "US",
                            "geographicArea": "GA",
                            "city": "Atlanta",
                            "postalCode": "30326",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "950 E Paces Ferry Rd NE",
                        },
                        {
                            "country": "US",
                            "geographicArea": "MA",
                            "city": "Burlington",
                            "postalCode": "01803",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "5 Wall St",
                        },
                        {
                            "country": "IT",
                            "geographicArea": "Lomb.",
                            "city": "Milan",
                            "postalCode": "20125",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "Via Niccolo Copernico, 38",
                        },
                        {
                            "country": "DE",
                            "geographicArea": "BE",
                            "city": "Berlin",
                            "postalCode": "10707",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "Kurfurstendamm 194",
                        },
                        {
                            "country": "ES",
                            "geographicArea": "Community of Madrid",
                            "city": "Madrid",
                            "postalCode": "28046",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "Paseo de la Castellana, 79",
                        },
                        {
                            "country": "IL",
                            "geographicArea": "Tel Aviv",
                            "city": "Tel Aviv-Yafo",
                            "postalCode": "60000",
                            "streetAddressOptOut": False,
                            "headquarter": False,
                            "line1": "Derekh Menahem Begin 154",
                        },
                    ],
                },
                "urls": {
                    "company_page": "http://www.salesforce.com",
                    "li_url": "https://www.linkedin.com/company/salesforce",
                },
                "industries": ["Computer Software"],
                "images": {
                    "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHZ9xYomLW7zg/company-logo_400_400/0/1591198956689?e=1672876800&v=beta&t=JMElmvDj--xs2ilRrUtpBFCAo-_B2Bq6Thm4JFQ88I4",
                    "cover": "https://media-exp1.licdn.com/dms/image/D561BAQHVvGKwrT41Rg/company-background_10000/0/1659634072942?e=1665705600&v=beta&t=vU3Tg6d0Z-jctKE67tr3KuHPJWsXpcL-LV1wBkuUE24",
                },
                "specialities": [
                    "Enterprise Cloud Computing",
                    "Customer Relationship Management",
                ],
                "paid": True,
            },
            "related_companies": [
                {
                    "name": "Salesforce Work.com",
                    "universal_name": "workdotcom",
                    "company_id": "1022787",
                    "description": "Sell Better Together\r\nSales Performance Management from Salesforce. \r\n                                                                                                                                  \r\n\r\nPlease follow us for the latest updates on the Salesforce LinkedIn Page.",
                    "phone": None,
                    "followers": 8402,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/workdotcom",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHIcjD_4D3SNw/company-logo_400_400/0/1519890103925?e=1672876800&v=beta&t=URWVbzE46jIORwYoLRo4OAD8PxP0xVE6-exL7bEN4U0",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "GoInstant",
                    "universal_name": "goinstant",
                    "company_id": "2064433",
                    "description": "GoInstant is the first shared web browsing service. Within just a few seconds and with no downloads or plugins,  users can share an interactive browsing experience. \r\n\r\nGoInstant\u2019s unique technology unleashes new business opportunities to improve customer support and enhance sales on the web.",
                    "phone": None,
                    "followers": 1412,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/goinstant",
                    },
                    "industries": ["Internet"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQFNSxkfG4qi4Q/company-logo_400_400/0/1519874283141?e=1672876800&v=beta&t=4Z3gLgsEhss9vWpTfC0KC_xZSm3s1hw0slX6nJARXK8",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Manymoon",
                    "universal_name": "manymoon",
                    "company_id": "1258710",
                    "description": "Get work done together \u2013 on anything, with anyone and anywhere. \r\n\r\nManymooon is a social productivity tool that simplifies your work life by letting you organize group projects, tasks, documents, and conversations all in one place for your whole team. Trusted by over 50,000 organizations, Manymoon can be used for anything from planning an event, to launching a product to hiring new employees.",
                    "phone": None,
                    "followers": 1550,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/manymoon",
                    },
                    "industries": ["Internet"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQGzRSJbYw9qJg/company-logo_400_400/0/1519892850695?e=1672876800&v=beta&t=5RtcjirXhBspxdKmwLD9w-ohJg_fDaiuCpnhM674XdY",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "EntropySoft",
                    "universal_name": "entropysoft",
                    "company_id": "203929",
                    "description": "Unstructured data, such as documents, images and videos, is growing at an exponential rate. Within corporations, unstructured data currently accounts for 80% of overall data, and the amount of unstructured data is doubling every two years. Companies multiply the overall number of content silos being used; they are therefore faced with increasing content fragmentation. The proliferation of digital documents combined with content fragmentation is an unavoidable and unstoppable market trend, and certainly one of the biggest challenges companies are facing today.\r\n\r\nEntropySoft facilitates information access for companies of all sizes. Regardless where the document is stored, EntropySoft has the technology to connect to it. If, for whatever reason, the user or the application cannot access directly a document, EntropySoft transfers it to an accessible location.\r\n\r\nEntropySoft is helping enterprise software companies access and work with the many content silos of their customers; EntropySoft is helping SaaS companies to bridge the gap between their offers and the on-premises ECM systems and finally, EntropySoft is helping companies of all sizes tame the digital explosion.",
                    "phone": None,
                    "followers": 1018,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/entropysoft",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQEAAwz-CCJvEg/company-logo_400_400/0/1519912661487?e=1672876800&v=beta&t=7-7Cnm-XCtcUO8KJNq2ePSSW2HHkT0k7Rsm0ZOwIoQQ",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "\u00c4KTA",
                    "universal_name": "-kta",
                    "company_id": "1149432",
                    "description": "Salesforce Experience Design (formerly \u00c4KTA) is a team of passionate user champions who partner with influential companies to design and build transformational products and experiences. Our design-led approach turns human insights into business impact at Salesforce scale. (Acquired in 2015).",
                    "phone": None,
                    "followers": 1511,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/-kta",
                    },
                    "industries": ["Design"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4D0BAQFG1Pn9bcVGWQ/company-logo_400_400/0/1519892610277?e=1672876800&v=beta&t=Yhwvw8SBtsxIsmRBgksCPxW1niwkSLtKmdzOHfll_e8",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Salesforce Quip",
                    "universal_name": "salesforce-quip",
                    "company_id": "69314520",
                    "description": "Quip aligns teams to accelerate growth with real-time sales planning connected to live CRM data in Salesforce. Using collaborative documents, spreadsheets, and templates, Quip helps teams standardize sales processes like account planning, ramp reps faster with scalable best practices, and drive customer success \u2013 all while ensuring accurate CRM data.",
                    "phone": None,
                    "followers": 21238,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/salesforce-quip",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQFpJwHDmU0nEQ/company-logo_400_400/0/1631861876979?e=1672876800&v=beta&t=6z-ZdaV5n0dv4Vmy1NFsPHzpHPbmZlc707RUE8xKQcI",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Etacts Inc.",
                    "universal_name": "etacts-inc.",
                    "company_id": "1030556",
                    "description": "Etacts was born from the frustration of keeping in touch with our ever-growing list of friends (both business and personal), family, coworkers, and clients.\r\n\r\nIt's impossible to remember to stay in touch with all the people that matter. Etacts helps you maintain your relationships by doing three things:\r\n\r\n1) Showing you who you've lost touch with\r\n2) Letting you set reminders to stay in touch with people\r\n3) Helping you get back in touch meaningfully by giving you relevant context about your relationship with people, such as the last emails you exchanged, or their recent status updates.\r\n\r\nUse Etacts to build and maintain relationships with former friends, business partners, clients, and more!",
                    "phone": None,
                    "followers": 917,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/etacts-inc.",
                    },
                    "industries": ["Computer Networking"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQHUhUH0KC0Ndg/company-logo_400_400/0/1519893030834?e=1672876800&v=beta&t=OqN59exxP93vMuRQjQE5yyJ9DjjbEeNLlVcXs2Lsefc",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Ourglass.",
                    "universal_name": "plannedup",
                    "company_id": "2604869",
                    "description": "Who\u2019s in your inner circle?\r\n\r\nOurglass is an honest, private space to share your day with 12 best friends.\r\n\r\nBuild your inner circle and share the story of your day in high-definition. Snap pictures of events in your day, or upload from the camera roll.Your stories save, so you can travel back in time and relive life. Tap the shuffle-button to randomly browse stories from your friends\u2019 past.\r\n\r\nDo you know what your closest friends are actually doing right now? \r\nFind out, on Ourglass!",
                    "phone": None,
                    "followers": 867,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/plannedup",
                    },
                    "industries": ["Internet"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQEQg1ofSE5GYQ/company-logo_400_400/0/1519891053118?e=1672876800&v=beta&t=45ZhKOrwhSwnP7P1tlCxCf25mN9MjgztemCW_-q9rns",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Sendia Corporation",
                    "universal_name": "sendia-corporation",
                    "company_id": "56556",
                    "description": None,
                    "phone": None,
                    "followers": 832,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/sendia-corporation",
                    },
                    "industries": ["Wireless"],
                    "images": {"logo": None, "cover": None},
                    "paid": False,
                },
                {
                    "name": "Salesforce Trailhead Superbadges",
                    "universal_name": "salesforce-trailhead-superbadges",
                    "company_id": "10654776",
                    "description": "Trailhead is the fun way to learn Salesforce. \r\nEveryone can learn Salesforce. Whether you are an admin, user, or developer, there is a trail for you.\r\nEarn points and badges as you learn in-demand skills!",
                    "phone": None,
                    "followers": 14969,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/salesforce-trailhead-superbadges",
                    },
                    "industries": ["Information Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C510BAQFEj8y-jnltKg/company-logo_400_400/0/1519903545002?e=1672876800&v=beta&t=5yUHxAyfAxK6KL__7cf6HbxvN7yeI7sFaatHHc3Wl8E",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Dimdim",
                    "universal_name": "dimdim",
                    "company_id": "135413",
                    "description": "Meet the world's easiest web conference.\r\n\r\nDimdim lets anyone deliver synchronized live presentations, whiteboards and web pages and share their voice and video over the Internet - with no download required. \r\n\r\nRemember how hard it was to get your music into your pocket before the iPod? Well, you know how hard it is to get your web meetings started on time? We made it our mission to create a web conferencing system as easy to use as the iPod. With Dimdim, a single click is all it takes to meet.",
                    "phone": None,
                    "followers": 909,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/dimdim",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4D0BAQGMPmKPP-EePA/company-logo_400_400/0/1519896247291?e=1672876800&v=beta&t=sKZnp0CkRGFkZGd2nNJ0q1dLP5TChDO2BiqPT1_TXlg",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Activa Live",
                    "universal_name": "activa-live",
                    "company_id": "936478",
                    "description": "Activa Live is the leading cloud computing service provider of enterprise level, on-demand live chat software for customer service, support and online proactive sales interactions. Its innovative live chat software, Activa Live Chat, serves more than 300 leading companies worldwide including Best Buy, Procter & Gamble, Dun & Bradstreet, LexisNexis, American Apparel, TaylorMade Golf, Rooms To Go, and Hilton Grand Vacations. Activa Live Chat empowers organizations to monitor, identify and engage with online visitors in real-time, helping drive new sales and increase customer satisfaction levels, while decreasing support costs.",
                    "phone": None,
                    "followers": 595,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/activa-live",
                    },
                    "industries": ["Internet"],
                    "images": {"logo": None, "cover": None},
                    "paid": False,
                },
                {
                    "name": "Tableau",
                    "universal_name": "tableau-software",
                    "company_id": "206993",
                    "description": "About Tableau, a Salesforce Company\nTableau helps people see and understand data. Tableau\u2019s self-service analytics platform empowers people of any skill level to work with data. From individuals and non-profits to government agencies and the Fortune 500, tens of thousands of customers around the world rely on Tableau\u2019s advanced analytics capabilities to make impactful, data-driven decisions. See how Tableau can help your organization by starting your free trial at tableau.com/trial.",
                    "phone": None,
                    "followers": 782943,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/tableau-software",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQGbNutqXFCq8g/company-logo_400_400/0/1591199049957?e=1672876800&v=beta&t=GSpli3Fmo1KLtL53WsXXIu_QDUVjtaiWpOeWT0WpVYc",
                        "cover": None,
                    },
                    "paid": True,
                },
                {
                    "name": "Implisit",
                    "universal_name": "implisit",
                    "company_id": "3226614",
                    "description": "Implisit boosts Sales Managers and Reps\u2019 performance by automatically capturing, analyzing and acting on customer interactions. Sales professionals save countless hours of CRM updates and data entry, letting Implisit automatically capture the latest sales activity. Sales managers can trust their pipeline and get accurate forecasts.",
                    "phone": None,
                    "followers": 685,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/implisit",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C510BAQF2ud2R-ZQ12g/company-logo_400_400/0/1519899843816?e=1672876800&v=beta&t=5iILPt1QH74l73bchdiQYe4xShJRuAoayVVQEusSx9Y",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Navajo Systems",
                    "universal_name": "navajo-systems",
                    "company_id": "400245",
                    "description": "Navajo Systems'\u200b vision is to dramatically expand the use of SaaS applications by eliminating the barriers related to data security and regulatory concerns. Founded by experts in the fields of information security, infrastructure security and Web application security, Navajo has introduced a patent-pending technology which promises to revolutionize SaaS application data security. The company, based in Israel, is funded by Jerusalem Venture Partners (www.jvpvc.com), a leading Israeli venture capital fund with over $780 million under management.\r\n\r\nNavajo Systems\u2019 Virtual Private SaaS (VPS) is a revolutionary solution to cloud data security challenges, allowing organizations to adopt cloud applications without any concerns about data security, data privacy or regulatory restrictions. VPS transparently encrypts all sensitive data before it is transmitted from the client to the server, and allows the data to remain encrypted while at rest on the SaaS application server. End users remain completely unaware of the background encryption/decryption processes, yet their sensitive data is completely unreadable (and therefore meaningless) when stored on the SaaS provider's server. Database theft and identity theft becomes harmless, and regulatory compliance is ensured, as all sensitive data remains undecipherable when transmitted and stored outside the customer organization.\r\n\r\nWhile data encryption is not new, the innovations of VPS are threefold: (a) even while the sensitive data remains encrypted at all times on the SaaS application server, key application functionality (e.g., searching, sorting) remains intact; (b) the customer alone holds all the encryption keys (the SaaS vendor has no possibility of decrypting the data stored on their servers) and (c) no modifications whatsoever are required to the cloud application code.",
                    "phone": None,
                    "followers": 1025,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/navajo-systems",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4D0BAQFwbUC0fP4ryg/company-logo_400_400/0/1519863705933?e=1672876800&v=beta&t=W48mJcXq7vjArJjwGByt2xAZrDNTwGxQyEPzuyS4ZKI",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Model Metrics",
                    "universal_name": "model-metrics",
                    "company_id": "69468",
                    "description": "Model Metrics, a salesforce.com company, provides the world\u2019s leading businesses with transformational cloud solutions.  We bring corporate visions to life by combining our complete Salesforce deployment services with our expertise using cutting edge social and mobile technologies, complete with world-class design. As a result, we deliver solutions that not only help our customers exceed business goals, but also embody their brand throughout the solution. We offer employees the best of both worlds: small teams, entrepreneurial spirit, cutting edge projects, and fast execution backed by the vast resources of a market leader.    \r\n                       \r\nModel Metrics has received numerous awards ncluding being recognized as a Gartner Cool Vendor, Red Herring 100 winner, #9 on CRN's list of Fast Growth Companies, 2011 Illinois Technology Association Citylights Winner and ranked in the top two positions of the Chicago Tribune's Top Workplaces in '10 and '11.  Additionally, Salesforce.com was recognized in '12 as one of FORTUNE's 100 Best Companies to Work For (for the fourth consecutive year) and one of the 100 Fastest-Growing Companies, while Forbes ranked Salesforce.com #1 on their list of the World\u2019s Most Innovative Companies.  We encourage you to apply and become part of our iaward-winning team!",
                    "phone": None,
                    "followers": 4557,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/model-metrics",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQEj0437DbqK6g/company-logo_400_400/0/1519873673026?e=1672876800&v=beta&t=BdoSzeHYrIg5UF60w9-e98f19Ir3WwtGKwkQepnYdVk",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Salesforce Commerce Cloud",
                    "universal_name": "commercecloud-demandware",
                    "company_id": "22495",
                    "description": "The Salesforce Commerce Cloud, formerly Demandware, powers enterprise cloud commerce for the world's most innovative brands, enabling unified, 1-to-1 experiences across all points of commerce including web, mobile, social and store. \n\nFor more information, visit www.commercecloud.com, call +1-888-553-9216 or email info@commercecloud.com",
                    "phone": None,
                    "followers": 52950,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/commercecloud-demandware",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQFZG1K0cdoZKg/company-logo_400_400/0/1591199870696?e=1672876800&v=beta&t=xSiGn-ohjqEbpNf14Y6kuQjh3k3CgJDalT15ddkt8eM",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Radian6 Technologies",
                    "universal_name": "radian6-technologies",
                    "company_id": "167639",
                    "description": None,
                    "phone": None,
                    "followers": 868,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/radian6-technologies",
                    },
                    "industries": ["Computer Software"],
                    "images": {"logo": None, "cover": None},
                    "paid": False,
                },
                {
                    "name": "Salesforce Military",
                    "universal_name": "salesforcemilitary",
                    "company_id": "25733114",
                    "description": "Salesforce Military is a workforce development program that provides an onramp for the military community to tap into the booming Salesforce economy of high demand, high paying tech careers. Trailhead is Salesforce\u2019s free, online learning platform that empowers anyone to skill up for the future and learn in-demand skills that lead to top jobs. Through Salesforce Military, members also have the opportunity to take classes and earn up to 18 certifications for free.",
                    "phone": None,
                    "followers": 12937,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/school/salesforcemilitary/",
                    },
                    "industries": ["Professional Training & Coaching"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQGtIncSiZMBLQ/company-logo_400_400/0/1576598172395?e=1672876800&v=beta&t=d5b68eVkWf-rOLGxPr7mpMdb4Xv2vTdEhXD0R1_aD_A",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "ExactTarget",
                    "universal_name": "exacttarget",
                    "company_id": "9236",
                    "description": "ExactTarget is now the Salesforce Marketing Cloud - Visit them here: \nhttp://sforce.co/2nnCQU7\n\nThe Salesforce Marketing Cloud is the world\u2019s most powerful digital marketing 1:1 platform. We power customer journeys across every touchpoint\u2014email, social, mobile, web, and beyond\u2014helping marketers put customers at the center of everything they do. The Marketing Cloud is a salesforce.com company. For more information, visit www.salesforce.com/marketingcloud\n\nBy partnering state-of-the-art technology with the best and brightest employees in the industry, we foster a culture of constant innovation and growth. Consistently ranked by employees as one of the \u201cBest Places to Work,\u201d the Marketing Cloud team shows you what being Orange is all about!",
                    "phone": None,
                    "followers": 31735,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/exacttarget",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C510BAQGNrX0TE9d2Tw/company-logo_400_400/0/1519856135418?e=1672876800&v=beta&t=e9T4yZGHKRrnlUdnWSRqYZXl1sMdc1U3MMpv3nnDBQU",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Thinkfuse",
                    "universal_name": "thinkfuse",
                    "company_id": "1448138",
                    "description": "Thinkfuse is an Enterprise Software-as-a-Service platform that turns the dreaded weekly status report into a powerful business intelligence tool. The company was created by co-founders Brandon Bloom and Steve Krenzel and is a member of the TechStars Seattle class of 2010.",
                    "phone": None,
                    "followers": 883,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/thinkfuse",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4D0BAQE3kwyUOD_gqQ/company-logo_400_400/0/1519866653208?e=1672876800&v=beta&t=c7YQaqjSCS02tOa2NTZvbiT_io5RHdRebRhgs9pBEJA",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Prior Knowledge, Inc.",
                    "universal_name": "prior-knowledge-inc-",
                    "company_id": "2457115",
                    "description": "Prior Knowledge builds cloud services to provide insight into data. Prior Knowledge builds cloud services to provide insight into data. Prior Knowledge builds cloud services to provide insight into data.  Prior Knowledge builds cloud services to provide insight into data.",
                    "phone": None,
                    "followers": 760,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/prior-knowledge-inc-",
                    },
                    "industries": ["Computer Software"],
                    "images": {"logo": None, "cover": None},
                    "paid": False,
                },
                {
                    "name": "InStranet",
                    "universal_name": "instranet",
                    "company_id": "26031",
                    "description": None,
                    "phone": None,
                    "followers": 795,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/instranet",
                    },
                    "industries": ["Computer Software"],
                    "images": {"logo": None, "cover": None},
                    "paid": False,
                },
                {
                    "name": "Pardot",
                    "universal_name": "pardot",
                    "company_id": "120558",
                    "description": "Pardot is B2B Marketing Automation by Salesforce that allows marketing and sales teams to create, deploy, and manage online marketing campaigns that increase revenue and maximize efficiency.\r\n\r\nFeatures include:\r\n\u2022 CRM integration\r\n\u2022 Email marketing\r\n\u2022 Lead management\r\n\u2022 Lead nurturing\r\n\u2022 Social media marketing\r\n\u2022 Sales intelligence\r\n\u2022 ROI reporting\r\n\r\nFor more information, call 1-855-426-9213 or visit us at www.pardot.com.",
                    "phone": None,
                    "followers": 47311,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/pardot",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQFWQHGJTk-kPw/company-logo_400_400/0/1591199413607?e=1672876800&v=beta&t=aU8y1GBsJzDUepGiFdJDXsvx9vAIBMt8-aO89I_QfWM",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Trailhead",
                    "universal_name": "salesforce-trailhead",
                    "company_id": "10279937",
                    "description": "With Trailhead, anyone can learn in-demand skills, earn resume-worthy credentials, and connect with a community of Trailblazers for mentorship and employment opportunities.\n \nWith the free Trailhead GO mobile app, you can access all of the amazing Trailhead learning content that you love from the palm of your hand. Download on iOS or Android: https://sforce.co/trailheadgo",
                    "phone": None,
                    "followers": 168920,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/salesforce-trailhead",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQGXS7-SEokjig/company-logo_400_400/0/1591199421818?e=1672876800&v=beta&t=zYTL-XvsLUszHOdYqDItctUoiQ6rIYSUFGJmrZkRoYQ",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Stypi",
                    "universal_name": "stypi",
                    "company_id": "3232211",
                    "description": "Stypi is a San Francisco based tech company focusing on real-time collaboration. Its first product is a collaborative code editor that many companies such as Apple, Pinterest, and Palantir, have incorporated into their remote interview process.\r\n\r\nStypi was acquired by Salesforce.com in 2012, where the team still continues to build its real-time technology and platform.",
                    "phone": None,
                    "followers": 795,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/stypi",
                    },
                    "industries": ["Internet"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQEV1S96-oZpxg/company-logo_400_400/0/1519908768516?e=1672876800&v=beta&t=_lcP3Fc-pFmlX6CmGRmCA5G5MmAnc5QfNZLld_feT7Y",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "GroupSwim",
                    "universal_name": "groupswim",
                    "company_id": "167374",
                    "description": "GroupSwim offers community and collaboration software for businesses.  Our products offer a rare combination of innovation and ease-of-use.  The focus of our products is to help businesses connect with their employees and customers, and make productive use of the information they exchange and create every day.  GroupSwim solutions are also fast to implement and very affordable, giving our customers instant return on their investment.",
                    "phone": None,
                    "followers": 829,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/groupswim",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C560BAQFia3ZWEtrO0Q/company-logo_400_400/0/1519885193254?e=1672876800&v=beta&t=Mea4LJJvB0O4KfQBVz-Ti65Epnq_1b2MFT5fSSEpVSs",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "EdgeSpring (acquired by Salesforce)",
                    "universal_name": "edgespring",
                    "company_id": "1336391",
                    "description": "EdgeSpring delivers speed-of-thought business insight by enabling decision makers to ask any question of any data, anytime, anywhere. EdgeSpring is a rapidly growing Business Intelligence platform startup that is revolutionizing analytics in the enterprise with a search-based approach to BI that delivers breakthrough advances in flexibility, speed and ease of use. \r\n\r\nEdgeSpring is based in San Mateo, CA and backed by Kleiner Perkins and Lightspeed Venture Partners.",
                    "phone": None,
                    "followers": 1244,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/edgespring",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQF_G8aIbnJwMA/company-logo_400_400/0/1519882330948?e=1672876800&v=beta&t=biiSLRm_r-D7Y5CUd_55KC2Jpt-9iustmTCnQ5vRrog",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "BlueTail",
                    "universal_name": "bluetail",
                    "company_id": "2436592",
                    "description": ".                                                                                                                                                                                                                                                                                                                                                                                                  \r\n\r\n\r\n.",
                    "phone": None,
                    "followers": 899,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/bluetail",
                    },
                    "industries": ["Information Technology & Services"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C4E0BAQGNnI4KzCO1ZA/company-logo_400_400/0/1519897455207?e=1672876800&v=beta&t=_j8tJjnCsA5iET-h9-3q81wPzlAJ-dwJQ2QgKiommfI",
                        "cover": None,
                    },
                    "paid": False,
                },
                {
                    "name": "Sitemasher",
                    "universal_name": "sitemasher",
                    "company_id": "167690",
                    "description": "Sitemasher is a complete website platform for service providers for building, deploying and managing custom data driven websites and apps. Sitemasher is only available on Microsofts Azure cloud which takes advantage of its patent pending architecture and multitennant scalability.",
                    "phone": None,
                    "followers": 978,
                    "urls": {
                        "company_page": None,
                        "li_url": "https://www.linkedin.com/company/sitemasher",
                    },
                    "industries": ["Computer Software"],
                    "images": {
                        "logo": "https://media-exp1.licdn.com/dms/image/C510BAQFnYgtfTyWcSA/company-logo_400_400/0/1519903869306?e=1672876800&v=beta&t=SFa3QgKX5XDdFuh25M3aOERWZtdNwfxoz9myWvyscDk",
                        "cover": None,
                    },
                    "paid": False,
                },
            ],
        },
    }

    data = get_recent_recommendation_summary(info_with_no_recommendation)
    assert data == {}

    info_with_no_recommendation["personal"]["recommendations"][0][
        "created_at"
    ] = datetime.datetime.now().isoformat()
    data = get_recent_recommendation_summary(info_with_no_recommendation)
    assert data["response"] == "testing response"
